In [7]:
import os
print(os.getcwd())

c:\Users\Owner\Desktop\data science\OneDrive\Documents\IGP Project

In [8]:
import os

# Print your current working directory
print("Current working directory:", os.getcwd())

# List all files in the current directory
print("Files in current directory:")
print(os.listdir(os.getcwd()))

Current working directory: c:\Users\Owner\Desktop\data science\OneDrive\Documents\IGP Project
Files in current directory:
['script2.ipynb', 'script22.ipynb', 'UWE_Brsitol_IGP_Project']

In [9]:
import os
print(os.listdir('UWE_Brsitol_IGP_Project'))

import os
print(os.listdir('UWE_Brsitol_IGP_Project/python_folder'))

['.git', '.gitignore', 'python_folder', 'README.md', 'script2.ipynb']
['csv_data', 'demo.csv', 'demo_numeric.csv', 'demo_week_2.csv', 'eda.ipynb', 'etl_script.py', 'images', 'merged_df.csv', 'merged_df2.csv', 'merged_weeks.csv', 'notebook_report.html', 'requirements.md', 'Retrospective.csv', 'Retro_numeric.csv', 'students_info.csv']

In [10]:
import os
print(os.listdir('UWE_Brsitol_IGP_Project/python_folder/csv_data'))

['data1.xlsx', 'data2.xlsx', 'week1.csv', 'week1_demo.csv', 'week2.csv', 'week2_demo.csv']

In [11]:
import pandas as pd
import os

file_path = 'UWE_Brsitol_IGP_Project/python_folder/csv_data/data2.xlsx'
if not os.path.exists(file_path):
    raise FileNotFoundError(f"The file '{file_path}' does not exist.")
xls = pd.ExcelFile(file_path)
print(xls.sheet_names)  # Optional: to verify sheet names
demo_week_2 = pd.read_excel(xls, 'QUESTIONNAIRE', skiprows=1)
demo_week_2 = demo_week_2.iloc[:, 1:]

['QUESTIONNAIRE', 'QuestNumericValues', 'RetrospectiveNumeric', 'Week 1 ', 'Week 2', 'Week 3', 'Week 4', 'Week 5', 'Week 6', 'Week 7', 'Week8', 'Week 9', 'Week 10', '11 only 2']

In [12]:
import pandas as pd
import os

file_path = 'UWE_Brsitol_IGP_Project/python_folder/csv_data/data2.xlsx'
if not os.path.exists(file_path):
    raise FileNotFoundError(f"The file '{file_path}' does not exist.")
xls = pd.ExcelFile(file_path)
print(xls.sheet_names)  # Optional: to verify sheet names

# Use the exact sheet name as listed: 'QUESTIONNAIRE'
demo_week_2 = pd.read_excel(xls, 'QUESTIONNAIRE', skiprows=1)
demo_week_2 = demo_week_2.iloc[:, 1:]

['QUESTIONNAIRE', 'QuestNumericValues', 'RetrospectiveNumeric', 'Week 1 ', 'Week 2', 'Week 3', 'Week 4', 'Week 5', 'Week 6', 'Week 7', 'Week8', 'Week 9', 'Week 10', '11 only 2']

In [13]:
import pandas as pd
import os
from IPython.display import display  # For better table display in Jupyter

file_path = 'UWE_Brsitol_IGP_Project/python_folder/csv_data/data2.xlsx'
if not os.path.exists(file_path):
    raise FileNotFoundError(f"The file '{file_path}' does not exist.")
xls = pd.ExcelFile(file_path)
demo_week_2 = pd.read_excel(xls, 'QUESTIONNAIRE', skiprows=1)
demo_week_2 = demo_week_2.iloc[:, 1:]

# Display the first few rows in a nice table format
display(demo_week_2.head())

,List of Countries,What is your year of birth?,How do you describe yourself? - Selected Choice,How do you describe yourself? - Prefer to self-describe - Text,What is your first degree subject area?,How many years work experience do you have?,What sectors have you worked in?,Previous experiences of formative assessment and feedback,"Based on experience or feeling, my expectations for this module are that: - I will enjoy this module","Based on experience or feeling, my expectations for this module are that: - The formative assessment tasks will be highly effective for my learning",...,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 7. Because it is something that I have to do,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 8. I am doing this module but I am not sure if it is worth it,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 9. Because this module looks fun,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 10. By personal decision,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 11. Because I don’t have any choice,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 12. I don’t know; I don’t see what this module brings me,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 13. Because I feel good about this module,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 14. Because I believe that this module is important for me,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 15. Because I feel that I have to do it,"Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 16. I am doing this module, but I am not sure it is a good thing to pursue it"
0,United Kingdom of Great Britain and Northern I...,1999,Female,NaN,CAH11-01\tComputing,NaN,OTHER SERVICE ACTIVITIES,NaN,Somewhat agree,Somewhat agree,...,Enough,A Lot,A Lot,Not At All,Not At All,A Little,Moderately,Not At All,Not At All,Not At All
1,Nigeria,1992,Male,NaN,CAH11-01\tComputing,4.0,FINANCIAL AND INSURANCE ACTIVITIES,I have no prior experience of formative assess...,Strongly agree,Strongly agree,...,A Little,Moderately,Moderately,A Lot,Moderately,A Very Little,Exactly,Exactly,A Little,Not At All
2,Nigeria,1987,Male,NaN,CAH11-01\tComputing,8.0,FINANCIAL AND INSURANCE ACTIVITIES,I have some experience,Strongly agree,Strongly agree,...,Enough,Not At All,Exactly,A Lot,Enough,Not At All,Exactly,Exactly,Enough,Not At All
3,Nigeria,1993,Male,NaN,"CAH24-01\tMedia, journalism and communications",6.0,"AGRICULTURE, FORESTRY AND FISHING,INFORMATION ...",I have some experience,Strongly agree,Strongly agree,...,Exactly,Not At All,A Lot,Moderately,Moderately,Not At All,Exactly,Exactly,Exactly,Not At All
4,Pakistan,1996,Male,NaN,CAH11-01\tComputing,0.0,OTHER SERVICE ACTIVITIES,I have some experience,Strongly agree,Strongly agree,...,Exactly,Exactly,Exactly,Exactly,Exactly,Exactly,Exactly,Exactly,Exactly,Exactly

In [14]:
import pandas as pd
import os
from IPython.display import display  # For better table display in Jupyter

file_path = 'UWE_Brsitol_IGP_Project/python_folder/csv_data/data2.xlsx'
if not os.path.exists(file_path):
    raise FileNotFoundError(f"The file '{file_path}' does not exist.")
xls = pd.ExcelFile(file_path)

# Read the 'QuestNumericValues' sheet 
QuestNumericValues = pd.read_excel(xls, 'QuestNumericValues', skiprows=1, na_values='NA')
# Show the full table (remove display limit)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
display(QuestNumericValues)

,"Performance Analytics in Formative Assessment and Feedback\n\nThank you in advance for taking the time to read this information and considering your participation in this study exploring the impact of formative assessment on student performance. Formative assessment informs students about their learning, familiarise students with the expectations of summative assessments and provides feedback that guides the direction of student learning (Krasne et al. 2006).\n\n\n\nPlease ensure that you have read and understood the information contained in the Participant Information Sheet and asked any questions before you sign this form. If you have any questions please contact a member of the research team, whose details are set out on the Participant Information Sheet.\n\nPlease confirm\n\n\n \n \n \n \n \n I have read and understood the information in the Participant Information Sheet\n \n \n \n \n \n \n \n \n I am aware of what my participation will involve and the data collected will remain confidential and no information that identifies me will be made publicly available.\n \n \n \n \n \n \n \n \n I understand that my participation is voluntary, is not connected to my assessment and that I am free to withdraw from the study at any time, without having to give a reason and without consequences;",List of Countries,What is your year of birth?,How do you describe yourself? - Selected Choice,How do you describe yourself? - Prefer to self-describe - Text,What is your first degree subject area?,How many years work experience do you have?,What sectors have you worked in?,Previous experiences of formative assessment and feedback,"Based on experience or feeling, my expectations for this module are that: - I will enjoy this module","Based on experience or feeling, my expectations for this module are that: - The formative assessment tasks will be highly effective for my learning","Based on experience or feeling, my expectations for this module are that: - Communication with the instructor will be very frequent","Based on experience or feeling, my expectations for this module are that: - I will be able to identify my strengths and weaknesses within my own work","Based on experience or feeling, my expectations for this module are that: - I will collaborate with others to complete some of the tasks","Based on experience or feeling, my expectations for this module are that: - Formative assessment tasks will help me know how well I am doing","Based on experience or feeling, my expectations for this module are that: - I will be a more independent learner","Based on experience or feeling, my expectations for this module are that: - I will develop my writing skills and my approach to writing coursework as a result of the module","Based on experience or feeling, my expectations for this module are that: - I will adjust my work regularly as I go along","Based on experience or feeling, my expectations for this module are that: - I will stick to my original plan","Based on experience or feeling, my expectations for this module are that: - I will produce an end result which I am proud of","I see myself as... - Extraverted, enthusiastic","I see myself as... - Critical, quarrelsome","I see myself as... - Dependable, self-disciplined","I see myself as... - Anxious, easily upset","I see myself as... - Open to a new experiences, complex","I see myself as... - Reserved, quiet","I see myself as... - Sympathetic, warm","I see myself as... - Disorganised, careless","I see myself as... - Calm, emotionally stable","I see myself as... - Conventional, uncreative",Why are you doing this module?\nScore by the extent to which the statement corresponds with how you feel about it - 1. Because I think that this module is interesting,Why are you doing this module?\nScore by the extent to which the statement corresponds with how you feel about it - 2. Because I am doing it for my own good,Why are you doing this module?\nScore by the extent to which the statement corresponds with how you feel about it - 3. Because I am supposed to do it,"Why are you doing this module?\nScore by the extent to which the statement corresponds with how you feel about it - 4. There may be good reasons to do this module, but personally I don’t see any",Why are you doing this module?\nScore by the extent to which the statement corresponds with how you feel about it - 5. Because I think that this module is pleasant,Why are you doing this module?\nScore by the extent to which the statement corresponds with how you feel about it - 6. Because I think that this module is good for me,Why are you doing this module?\nScore by the extent to which the statement corresponds with how you feel about it - 7. Because it is something that I have to do,Why are you doing this module?\nScore by the extent to which the statement corresponds with how you feel about it - 8. I am doing this module but I am not sure if it is worth it,Why are you doing this module?\nScore by the extent to which the statement corresponds with how you feel about it - 9. Because this module looks fun,Why are you doing this module?\nScore by the extent to which the statement corresponds with how you feel about it - 10. By personal decision,Why are you doing this module?\nScore by the extent to which the statement corresponds with how you feel about it - 11. Because I don’t have any choice,Why are you doing this module?\nScore by the extent to which the statement corresponds with how you feel about it - 12. I don’t know; I don’t see what this module brings me,Why are you doing this module?\nScore by the extent to which the statement corresponds with how you feel about it - 13. Because I feel good about this module,Why are you doing this module?\nScore by the extent to which the statement corresponds with how you feel about it - 14. Because I believe that this module is important for me,Why are you doing this module?\nScore by the extent to which the statement corresponds with how you feel about it - 15. Because I feel that I have to do it,"Why are you doing this module?\nScore by the extent to which the statement corresponds with how you feel about it - 16. I am doing this module, but I am not sure it is a good thing to pursue it"
0,1,185,1999,2,NaN,17,NaN,19,NaN,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,5.0,5.0,5.0,NaN,5.0,6.0,6.0,6.0,5.0,6.0,1.0,3.0,7.0,6.0,5.0,5.0,5.0,6.0,6.0,1.0,1.0,3.0,4.0,1.0,1.0,1.0
1,2,126,1992,1,NaN,17,4.0,11,1.0,5.0,5.0,4.0,5.0,5.0,5.0,3.0,5.0,4.0,3.0,5.0,7.0,1.0,2.0,1.0,7.0,6.0,6.0,1.0,6.0,2.0,7.0,7.0,3.0,4.0,7.0,7.0,3.0,4.0,4.0,6.0,4.0,2.0,7.0,7.0,3.0,1.0
2,3,126,1987,1,NaN,17,8.0,11,2.0,5.0,5.0,5.0,5.0,5.0,5.0,2.0,5.0,5.0,2.0,5.0,7.0,5.0,7.0,2.0,7.0,7.0,6.0,1.0,6.0,1.0,7.0,6.0,5.0,1.0,7.0,7.0,5.0,1.0,7.0,6.0,5.0,1.0,7.0,7.0,5.0,1.0
3,4,126,1993,1,NaN,32,6.0,"1,10",2.0,5.0,5.0,4.0,5.0,5.0,5.0,4.0,4.0,4.0,NaN,5.0,6.0,2.0,NaN,1.0,7.0,6.0,7.0,1.0,7.0,1.0,7.0,7.0,7.0,1.0,6.0,7.0,7.0,1.0,6.0,4.0,4.0,1.0,7.0,7.0,7.0,1.0
4,5,130,1996,1,NaN,17,0.0,19,2.0,5.0,5.0,5.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,7.0,5.0,6.0,1.0,6.0,6.0,6.0,1.0,6.0,6.0,7.0,7.0,7.0,6.0,7.0,6.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0
5,6,130,1996,1,NaN,17,NaN,10,2.0,5.0,4.0,5.0,5.0,5.0,5.0,2.0,4.0,5.0,4.0,4.0,7.0,2.0,6.0,1.0,6.0,1.0,5.0,1.0,7.0,3.0,7.0,7.0,7.0,1.0,7.0,7.0,7.0,1.0,1.0,7.0,1.0,1.0,7.0,7.0,7.0,1.0
6,7,126,1993,1,NaN,11,4.0,10,2.0,5.0,5.0,5.0,5.0,4.0,5.0,4.0,5.0,4.0,4.0,5.0,7.0,4.0,4.0,4.0,5.0,3.0,7.0,1.0,7.0,1.0,4.0,5.0,4.0,1.0,5.0,5.0,5.0,1.0,4.0,4.0,4.0,1.0,4.0,5.0,5.0,1.0
7,8,66,1992,1,NaN,17,NaN,16,2.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,3.0,7.0,2.0,7.0,7.0,6.0,1.0,7.0,1.0,7.0,4.0,7.0,1.0,1.0,7.0,7.0,1.0,7.0,7.0,1.0,1.0,7.0,7.0,7.0,1.0
8,9,66,1992,1,NaN,10,NaN,1,1.0,5.0,5.0,4.0,5.0,3.0,5.0,5.0,5.0,5.0,4.0,5.0,4.0,4.0,6.0,3.0,6.0,7.0,6.0,2.0,7.0,5.0,7.0,7.0,7.0,1.0,7.0,7.0,7.0,1.0,4.0,7.0,7.0,1.0,7.0,7.0,7.0,1.0
9,10,126,1994,1,NaN,6,12.0,10,1.0,5.0,5.0,5.0,5.0,4.0,5.0,5.0,4.0,5.0,5.0,5.0,7.0,6.0,7.0,7.0,7.0,7.0,6.0,6.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0
10,11,126,1991,2,NaN,12,8.0,"10,13,16,18",1.0,5.0,5.0,4.0,5.0,5.0,5.0,4.0,4.0,5.0,2.0,5.0,7.0,1.0,7.0,6.0,7.0,6.0,7.0,6.0,7.0,1.0,6.0,7.0,7.0,1.0,6.0,7.0,7.0,1.0,6.0,1.0,7.0,1.0,6.0,7.0,6.0,1.0
11,12,66,1987,1,NaN,21,10.0,"10,16",1.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,4.0,5.0,7.0,5.0,6.0,1.0,7.0,4.0,5.0,2.0,6.0,4.0,7.0,7.0,4.0,1.0,5.0,7.0,5.0,1.0,7.0,5.0,1.0,1.0,7.0,7.0,7.0,1.0
12,13,126,1995,1,NaN,17,6.0,"1,10,13,16",2.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,3.0,4.0,3.0,5.0,3.0,5.0,7.0,1.0,7.0,6.0,6.0,4.0,6.0,5.0,5.0,5.0,6.0,1.0,5.0,5.0,5.0,3.0,5.0,7.0,1.0,2.0,5.0,5.0,2.0,1.0
13,14,126,1995,1,NaN,15,4.0,"6,11,12,16,18",2.0,5.0,5.0,3.0,4.0,4.0,4.0,4.0,5.0,5.0,3.0,5.0,3.0,4.0,6.0,6.0,7.0,5.0,6.0,6.0,5.0,6.0,7.0,7.0,6.0,1.0,6.0,7.0,7.0,1.0,7.0,7.0,1.0,1.0,7.0,7.0,7.0,1.0
14,15,126,1996,2,NaN,17,3.0,19,3.0,5.0,5.0,3.0,5.0,5.0,5.0,1.0,5.0,4.0,3.0,5.0,4.0,3.0,5.0,4.0,7.0,4.0,6.0,7.0,4.0,4.0,7.0,7.0,7.0,5.0,7.0,7.0,7.0,1.0,7.0,5.0,NaN,1.0,7.0,7.0,7.0,1.0
15,16,14,1993,1,NaN,17,6.0,16,2.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0
16,17,75,1998,1,NaN,17,1.5,10,2.0,3.0,4.0,4.0,4.0,4.0,5.0,4.0,4.0,4.0,5.0,4.0,4.0,4.0,4.0,3.0,4.0,5.0,4.0,4.0,4.0,4.0,5.0,5.0,4.0,5.0,4.0,5.0,4.0,3.0,4.0,5.0,5.0,4.0,5.0,5.0,5.0,4.0
17,18,14,1993,1,NaN,17,10.0,16,1.0,5.0,5.0,5.0,4.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,6.0,1.0,7.0,1.0,6.0,7.0,7.0,1.0,7.0,1.0,7.0,7.0,7.0,1.0,6.0,6.0,5.0,1.0,6.0,5.0,1.0,1.0,7.0,5.0,5.0,1.0
18,19,130,1997,2,NaN,17,NaN,NaN,1.0,4.0,4.0,4.0,4.0,3.0,3.0,4.0,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,126,1997,5,NaN,32,2.0,10,1.0,5.0,5.0,5.0,5.0,4.0,5.0,4.0,5.0,5.0,3.0,5.0,1.0,3.0,6.0,2.0,6.0,7.0,5.0,1.0,6.0,5.0,6.0,7.0,7.0,1.0,7.0,7.0,7.0,1.0,7.0,7.0,7.0,1.0,7.0,7.0,7.0,1.0
20,21,163,1995,1,NaN,17,0.0,"3,7,19",1.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,5.0,1.0,2.0,3.0,2.0,5.0,6.0,7.0,1.0,7.0,2.0,6.0,6.0,6.0,4.0,6.0,5.0,5.0,2.0,6.0,4.0,3.0,2.0,6.0,5.0,6.0,1.0
21,22,78,1996,2,NaN,13,NaN,19,1.0,4.0,5.0,3.0,5.0,5.0,5.0,2.0,3.0,5.0,3.0,3.0,6.0,2.0,6.0,3.0,7.0,5.0,2.0,1.0,6.0,2.0,4.0,7.0,1.0,1.0,3.0,6.0,4.0,1.0,6.0,6.0,1.0,6.0,6.0,5.0,4.0,4.0
22,23,126,1987,1,NaN,17,7.0,"10,11,19",2.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,5.0,7.0,3.0,7.0,1.0,7.0,5.0,7.0,2.0,7.0,2.0,7.0,7.0,4.0,1.0,7.0,7.0,5.0,1.0,4.0,7.0,5.0,1.0,7.0,7.0,7.0,3.0
23,24,78,2000,2,NaN,17,NaN,19,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,6.0,6.0,5.0,5.0,5.0,4.0,6.0,3.0,6.0,7.0,6.0,1.0,5.0,NaN,3.0,3.0,4.0,5.0,1.0,1.0,6.0,6.0,7.0,1.0
24,25,14,1994,1,NaN,17,4.5,19,3.0,5.0,4.0,3.0,5.0,4.0,5.0,3.0,4.0,5.0,3.0,5.0,7.0,4.0,6.0,1.0,6.0,2.0,5.0,1.0,5.0,2.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,130,1995,1,NaN,17,1.0,19,1.0,5.0,4.0,5.0,4.0,4.0,4.0,4.0,5.0,4.0,4.0,5.0,3.0,5.0,7.0,2.0,6.0,6.0,5.0,2.0,7.0,3.0,7.0,6.0,7.0,4.0,5.0,7.0,7.0,6.0,7.0,6.0,6.0,7.0,7.0,7.0,6.0,6.0
26,27,130,1995,2,NaN,17,NaN,NaN,1.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,89,1991,1,NaN,17,8.0,"3,13",3.0,NaN,4.0,4.0,3.0,4.0,NaN,3.0,4.0,4.0,3.0,4.0,3.0,6.0,4.0,NaN,4.0,NaN,5.0,5.0,6.0,7.0,5.0,5.0,5.0,4.0,5.0,4.0,6.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0
28,29,185,1981,1,NaN,20,18.0,"3,10,11",2.0,4.0,4.0,4.0,3.0,4.0,4.0,3.0,4.0,4.0,5.0,5.0,7.0,5.0,7.0,4.0,6.0,6.0,6.0,1.0,7.0,1.0,4.0,4.0,4.0,4.0,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
29,30,126,1981,1,NaN,29,12.0,11,1.0,4.0,4.0,4.0,5.0,4.0,4.0,3.0,4.0,4.0,3.0,4.0,3.0,2.0,6.0,5.0,5.0,6.0,7.0,2.0,6.0,4.0,3.0,3.0,1.0,3.0,4.0,4.0,1.0,4.0,3.0,5.0,1.0,4.0,2.0,2.0,1.0,3.0
30,31,126,1992,1,NaN,21,2.0,18,2.0,5.0,5.0,4.0,5.0,4.0,5.0,4.0,5.0,5.0,5.0,5.0,6.0,1.0,7.0,5.0,7.0,7.0,7.0,1.0,7.0,1.0,5.0,7.0,7.0,5.0,5.0,5.0,5.0,1.0,4.0,4.0,3.0,2.0,5.0,5.0,5.0,5.0
31,32,126,1994,1,NaN,17,4.0,"10,11,14,17",4.0,5.0,5.0,5.0,5.0,4.0,NaN,4.0,5.0,5.0,3.0,5.0,7.0,6.0,7.0,1.0,7.0,4.0,6.0,1.0,6.0,1.0,6.0,7.0,5.0,1.0,5.0,7.0,6.0,1.0,5.0,5.0,1.0,1.0,7.0,7.0,5.0,1.0
32,33,126,1989,1,NaN,18,NaN,NaN,1.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,34,126,1991,1,NaN,17,NaN,"8,10,11",1.0,5.0,5.0,4.0,5.0,5.0,5.0,1.0,5.0,5.0,3.0,5.0,4.0,4.0,6.0,3.0,7.0,5.0,5.0,3.0,5.0,2.0,7.0,6.0,5.0,2.0,7.0,7.0,4.0,2.0,7.0,2.0,2.0,2.0,7.0,7.0,7.0,1.0
34,35,126,1981,1,NaN,15,9.0,1,4.0,5.0,4.0,5.0,5.0,4.0,4.0,5.0,5.0,4.0,3.0,5.0,7.0,1.0,7.0,2.0,6.0,6.0,2.0,1.0,6.0,1.0,1.0,6.0,2.0,1.0,2.0,7.0,7.0,1.0,2.0,1.0,1.0,1.0,4.0,7.0,7.0,1.0
35,36,164,1994,1,NaN,17,3.0,10,1.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,7.0,1.0,7.0,2.0,7.0,6.0,7.0,1.0,7.0,6.0,7.0,7.0,7.0,1.0,1.0,7.0,7.0,1.0,7.0,7.0,1.0,1.0,7.0,7.0,6.0,1.0
36,37,78,1986,2,NaN,17,NaN,15,1.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,NaN,5.0,7.0,6.0,7.0,5.0,7.0,7.0,7.0,5.0,7.0,5.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,5.0,7.0,7.0,3.0,6.0,7.0,6.0,6.0,7.0
37,38,78,1992,2,NaN,17,7.0,19,1.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,7.0,1.0,7.0,1.0,7.0,6.0,3.0,1.0,7.0,1.0,7.0,7.0,7.0,1.0,7.0,7.0,7.0,1.0,7.0,7.0,1.0,1.0,7.0,7.0,1.0,1.0
38,39,78,1992,2,NaN,17,4.0,"10,16,17",2.0,4.0,4.0,4.0,5.0,5.0,5.0,4.0,4.0,5.0,4.0,5.0,6.0,1.0,7.0,2.0,7.0,6.0,7.0,1.0,7.0,1.0,7.0,7.0,4.0,1.0,6.0,6.0,6.0,1.0,6.0,6.0,4.0,1.0,7.0,7.0,7.0,1.0
39,40,164,1996,2,NaN,17,1.5,10,2.0,5.0,4.0,4.0,5.0,5.0,5.0,4.0,5.0,5.0,4.0,5.0,5.0,6.0,7.0,5.0,7.0,5.0,7.0,4.0,7.0,1.0,6.0,6.0,7.0,1.0,6.0,7.0,7.0,1.0,6.0,3.0,2.0,1.0,6.0,7.0,7.0,1.0
40,41,164,1997,1,NaN,17,4.0,19,4.0,5.0,5.0,5.0,5.0,4.0,NaN,3.0,5.0,3.0,3.0,5.0,6.0,5.0,6.0,4.0,7.0,7.0,6.0,3.0,5.0,2.0,7.0,7.0,6.0,1.0,6.0,7.0,6.0,1.0,6.0,4.0,1.0,1.0,7.0,7.0,7.0,1.0
41,42,187,1996,1,NaN,32,1.0,19,1.0,4.0,3.0,4.0,4.0,5.0,5.0,3.0,4.0,4.0,3.0,3.0,4.0,4.0,6.0,3.0,6.0,6.0,4.0,4.0,6.0,3.0,6.0,6.0,6.0,1.0,6.0,4.0,4.0,1.0,6.0,4.0,4.0,2.0,5.0,5.0,4.0,3.0
42,43,126,1991,1,NaN,15,4.0,10,2.0,5.0,4.0,4.0,3.0,4.0,4.0,4.0,5.0,5.0,2.0,5.0,5.0,4.0,5.0,4.0,6.0,6.0,4.0,4.0,4.0,4.0,7.0,4.0,5.0,3.0,4.0,4.0,1.0,1.0,5.0,6.0,1.0,1.0,7.0,7.0,1.0,1.0
43,44,18,1986,2,NaN,17,10.0,11,2.0,5.0,5.0,4.0,4.0,4.0,5.0,4.0,4.0,5.0,4.0,5.0,5.0,6.0,7.0,6.0,6.0,7.0,7.0,1.0,6.0,6.0,6.0,6.0,7.0,1.0,5.0,5.0,7.0,1.0,5.0,1.0,7.0,1.0,5.0,5.0,7.0,1.0
44,45,164,1989,1,NaN,17,12.0,"10,11",2.0,5.0,5.0,5.0,5.0,5.0,4.0,4.0,5.0,5.0,4.0,5.0,7.0,6.0,7.0,4.0,7.0,4.0,4.0,4.0,5.0,4.0,6.0,5.0,7.0,5.0,7.0,7.0,7.0,4.0,5.0,4.0,5.0,4.0,6.0,7.0,5.0,4.0
45,46,164,1992,2,NaN,17,6.0,10,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,1.0,7.0,7.0,7.0,1.0,6.0,6.0,1.0,1.0,7.0,7.0,6.0,1.0
46,47,66,1999,1,NaN,15,2.0,10,2.0,5.0,5.0,4.0,4.0,5.0,5.0,3.0,5.0,4.0,4.0,5.0,3.0,1.0,6.0,2.0,6.0,5.0,6.0,1.0,7.0,2.0,6.0,5.0,3.0,3.0,6.0,6.0,3.0,3.0,5.0,4.0,3.0,2.0,7.0,7.0,5.0,3.0
47,48,126,1989,1,NaN,15,NaN,10,1.0,5.0,5.0,4.0,4.0,4.0,5.0,4.0,5.0,4.0,1.0,5.0,6.0,1.0,6.0,2.0,7.0,4.0,4.0,1.0,6.0,1.0,6.0,6.0,1.0,1.0,5.0,7.0,5.0,1.0,5.0,4.0,1.0,1.0,5.0,6.0,2.0,1.0
48,49,151,1995,2,NaN,17,NaN,16,2.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,7.0,5.0,7.0,5.0,7.0,4.0,4.0,1.0,6.0,1.0,7.0,5.0,7.0,1.0,6.0,7.0,7.0,1.0,4.0,7.0,1.0,1.0,7.0,7.0,7.0,1.0
49,50,164,1988,2,NaN,17,7.0,"10,11,16",1.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,7.0,7.0,2.0,2.0,7.0,5.0,5.0,1.0,7.0,1.0,7.0,7.0,7.0,5.0,7.0,7.0,7.0,5.0,7.0,7.0,1.0,1.0,7.0,7.0,7.0,1.0
50,51,164,1994,1,NaN,15,5.0,4,1.0,5.0,5.0,4.0,5.0,3.0,5.0,4.0,4.0,5.0,4.0,5.0,3.0,5.0,6.0,6.0,7.0,7.0,7.0,5.0,7.0,4.0,6.0,6.0,4.0,1.0,7.0,7.0,6.0,4.0,6.0,6.0,1.0,2.0,6.0,7.0,4.0,1.0
51,52,121,1997,1,NaN,16,NaN,10,2.0,4.0,4.0,3.0,5.0,5.0,4.0,5.0,5.0,4.0,3.0,5.0,4.0,2.0,6.0,4.0,7.0,5.0,6.0,1.0,4.0,1.0,5.0,6.0,7.0,4.0,4.0,4.0,5.0,3.0,5.0,6.0,4.0,3.0,6.0,6.0,4.0,2.0
52,53,126,1991,2,NaN,32,10.0,"10,14,16,19",3.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,5.0,7.0,2.0,7.0,1.0,7.0,1.0,7.0,1.0,7.0,1.0,7.0,7.0,7.0,1.0,7.0,7.0,7.0,1.0,7.0,7.0,1.0,1.0,7.0,7.0,7.0,1.0
53,54,126,1992,1,NaN,17,NaN,6,1.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,7.0,1.0,7.0,1.0,7.0,3.0,7.0,1.0,3.0,1.0,7.0,7.0,7.0,1.0,7.0,7.0,7.0,1.0,7.0,7.0,1.0,1.0,7.0,7.0,7.0,1.0
54,55,78,1992,2,NaN,17,1.0,10,2.0,5.0,5.0,3.0,4.0,3.0,5.0,4.0,5.0,4.0,3.0,3.0,6.0,4.0,6.0,6.0,6.0,6.0,5.0,5.0,6.0,6.0,4.0,5.0,5.0,5.0,4.0,4.0,5.0,4.0,3.0,3.0,4.0,4.0,3.0,4.0,3.0,3.0
55,56,185,1985,1,NaN,17,6.0,"8,14,15",2.0,5.0,5.0,5.0,5.0,4.0,5.0,4.0,4.0,5.0,3.0,5.0,6.0,2.0,7.0,1.0,7.0,6.0,7.0,2.0,7.0,3.0,7.0,7.0,7.0,1.0,6.0,7.0,7.0,1.0,7.0,1.0,1.0,1.0,7.0,7.0,7.0,1.0
56,57,126,1987,2,NaN,17,NaN,15,2.0,5.0,5.0,4.0,5.0,5.0,3.0,3.0,5.0,4.0,2.0,5.0,6.0,2.0,7.0,5.0,7.0,2.0,6.0,1.0,6.0,1.0,4.0,7.0,4.0,1.0,5.0,7.0,1.0,1.0,5.0,6.0,1.0,1.0,7.0,7.0,5.0,1.0
57,58,78,1998,1,NaN,17,3.0,10,2.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,59,126,1994,1,NaN,20,2.0,"7,14",1.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,2.0,5.0,4.0,7.0,7.0,7.0,2.0,7.0,4.0,4.0,7.0,6.0,1.0,7.0,7.0,7.0,2.0,5.0,7.0,1.0,1.0,7.0,6.0,7.0,7.0
59,60,164,1998,1,NaN,17,3.5,"3,10",1.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,5.0,5.0,5.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,7.0,7.0,1.0,4.0,1.0,7.0,1.0,1.0,7.0,7.0,1.0,1.0,7.0,7.0,7.0,1.0
60,61,165,1994,2,NaN,33,4.0,"16,18",2.0,5.0,5.0,5.0,5.0,4.0,5.0,5.0,4.0,4.0,3.0,5.0,7.0,4.0,6.0,4.0,6.0,2.0,5.0,1.0,6.0,1.0,7.0,7.0,1.0,1.0,6.0,7.0,1.0,1.0,5.0,7.0,1.0,1.0,7.0,7.0,1.0,1.0
61,62,78,2001,2,NaN,17,NaN,16,1.0,5.0,5.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,7.0,6.0,7.0,7.0,7.0,6.0,7.0,1.0,6.0,1.0,6.0,7.0,6.0,1.0,7.0,7.0,6.0,1.0,4.0,5.0,1.0,1.0,5.0,6.0,2.0,1.0
62,63,66,1993,1,NaN,17,5.0,"2,10,14,19",4.0,5.0,5.0,5.0,5.0,4.0,5.0,3.0,4.0,4.0,4.0,5.0,7.0,2.0,6.0,1.0,7.0,1.0,2.0,1.0,7.0,1.0,7.0,7.0,5.0,1.0,7.0,7.0,1.0,1.0,7.0,7.0,1.0,1.0,7.0,7.0,2.0,1.0
63,64,121,1998,1,NaN,16,0.0,NaN,2.0,4.0,4.0,4.0,4.0,3.0,4.0,4.0,4.0,4.0,3.0,4.0,6.0,6.0,6.0,3.0,6.0,5.0,6.0,2.0,6.0,2.0,7.0,NaN,6.0,NaN,4.0,6.0,6.0,6.0,7.0,6.0,NaN,4.0,7.0,7.0,7.0,7.0
64,65,126,1982,2,NaN,30,10.0,16,4.0,5.0,5.0,4.0,5.0,5.0,5.0,4.0,4.0,5.0,4.0,5.0,6.0,1.0,6.0,1.0,6.0,7.0,6.0,1.0,6.0,5.0,6.0,6.0,4.0,6.0,6.0,6.0,1.0,6.0,6.0,1.0,1.0,6.0,4.0,6.0,2.0,1.0
65,66,126,1980,1,NaN,15,NaN,"8,10,11",2.0,4.0,4.0,4.0,4.0,5.0,5.0,3.0,4.0,5.0,4.0,5.0,6.0,2.0,6.0,4.0,7.0,6.0,7.0,2.0,6.0,4.0,4.0,6.0,5.0,2.0,4.0,5.0,5.0,1.0,5.0,5.0,1.0,1.0,6.0,6.0,5.0,2.0
66,67,126,1986,1,NaN,17,6.0,10,1.0,4.0,5.0,5.0,4.0,5.0,4.0,4.0,5.0,4.0,1.0,5.0,5.0,5.0,6.0,7.0,5.0,7.0,7.0,2.0,7.0,2.0,6.0,7.0,4.0,3.0,5.0,3.0,4.0,5.0,2.0,4.0,6.0,3.0,7.0,7.0,7.0,1.0
67,68,164,1989,1,NaN,17,14.0,"10,13,18",2.0,5.0,5.0,4.0,5.0,5.0,5.0,4.0,5.0,5.0,3.0,5.0,6.0,6.0,7.0,3.0,7.0,3.0,6.0,3.0,6.0,2.0,6.0,6.0,4.0,1.0,4.0,6.0,4.0,4.0,6.0,6.0,3.0,2.0,6.0,6.0,5.0,2.0
68,69,66,1989,1,NaN,17,8.0,"1,10",1.0,4.0,5.0,4.0,5.0,5.0,5.0,4.0,4.0,5.0,3.0,5.0,5.0,1.0,1.0,NaN,7.0,7.0,7.0,1.0,6.0,5.0,6.0,6.0,4.0,1.0,5.0,6.0,6.0,1.0,5.0,6.0,5.0,1.0,6.0,6.0,6.0,1.0
69,70,164,1995,2,NaN,17,3.0,10,1.0,5.0,5.0,4.0,4.0,4.0,4.0,5.0,4.0,4.0,3.0,5.0,6.0,5.0,5.0,3.0,6.0,3.0,6.0,2.0,6.0,2.0,7.0,7.0,3.0,3.0,7.0,7.0,2.0,2.0,6.0,6.0,2.0,2.0,6.0,6.0,3.0,2.0
70,71,164,1990,1,NaN,17,8.0,"10,11",1.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,5.0,6.0,5.0,6.0,4.0,7.0,4.0,6.0,1.0,6.0,1.0,6.0,6.0,1.0,1.0,6.0,6.0,5.0,1.0,6.0,3.0,1.0,1.0,6.0,6.0,1.0,1.0
71,72,78,1998,2,NaN,15,1.0,"16,19",1.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,7.0,3.0,7.0,1.0,7.0,1.0,4.0,1.0,7.0,1.0,7.0,6.0,6.0,1.0,7.0,7.0,7.0,1.0,7.0,7.0,1.0,1.0,7.0,7.0,7.0,1.0
72,73,130,1996,1,NaN,17,NaN,NaN,1.0,5.0,5.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,7.0,NaN,7.0,7.0,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,NaN,NaN
73,74,79,1998,1,NaN,17,3.0,"7,19",1.0,4.0,4.0,3.0,3.0,5.0,4.0,2.0,4.0,4.0,3.0,4.0,4.0,4.0,4.0,3.0,6.0,4.0,6.0,4.0,5.0,4.0,5.0,6.0,7.0,4.0,5.0,5.0,6.0,3.0,6.0,4.0,5.0,4.0,5.0,5.0,5.0,4.0

In [15]:
import pandas as pd
import os

file_path = 'UWE_Brsitol_IGP_Project/python_folder/csv_data/data2.xlsx'
if not os.path.exists(file_path):
    raise FileNotFoundError(f"The file '{file_path}' does not exist.")
xls = pd.ExcelFile(file_path)

# Use the exact sheet name: 'Week 1 ' (with a space at the end)
df1 = pd.read_excel(xls, 'Week 1 ', skiprows=1)
df1.columns = (
    df1.columns.str.replace(' ', '_')
    .str.replace(',', '')
    .str.lower()
    .str.replace("-", '_')
    .str.replace("?", '')
    .str.replace("(", '')
    .str.replace(")", '')
    .str.replace('.', '')
    .str.replace('&', '')
    .str.replace(":", '')
)
df1 = df1.iloc[:, 4:]
df1['main_week'] = 'week_one'
if 'unnamed_40' in df1.columns:
    df1.drop('unnamed_40', axis=1, inplace=True)

# Display the cleaned DataFrame
df1.head()

,unnamed_4,unnamed_5,unnamed_6,unnamed_7,unnamed_8,list_of_countries,what_is_your_year_of_birth,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range__week_1,monday,tuesday,wednesday,thursday,friday,saturday,sunday,student_time_in_course,avg_time_per_user,total_items,total_logins,assignments,learning_materials,module_information,reading_list,week_0,week_1,assignments1,learning_materials1,module_information1,reading_list1,week_01,week_11,assignments2,learning_materials2,module_information2,reading_list2,week_02,week_12,main_week
0,0.56,0.56,0.56,0.56,56,United Kingdom of Great Britain and Northern I...,1999,Female,CAH11-01\tComputing,1,03/10/22 - 09/10/22,0.0,0.108333,0.0,0.0,0.022222,0.0,0.0,00:07:50,00:22:36,8,13,0.001667,0.002222,0.021112,0.001388,0.0,0.047500,3,4,5,2,0,2,2022-10-04 11:12:03.997,2022-10-04 11:11:57.874,2022-10-04 11:11:59.852,2022-10-07 17:27:57.359,NaT,2022-10-04 11:27:30.818,week_one
1,0.56,0.56,0.56,0.24,48,Nigeria,1992,Male,CAH11-01\tComputing,2,03/10/22 - 09/10/22,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,00:00:00,00:22:36,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0,0,0,0,0,0,NaT,NaT,NaT,NaT,NaT,NaT,week_one
2,0.64,0.61,0.64,0.59,62,Nigeria,1987,Male,CAH11-01\tComputing,3,03/10/22 - 09/10/22,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,00:00:00,00:22:36,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0,0,0,0,0,0,NaT,NaT,NaT,NaT,NaT,NaT,week_one
3,0.68,0.68,0.52,0.64,63,Nigeria,1993,Male,"CAH24-01\tMedia, journalism and communications",4,03/10/22 - 09/10/22,0.0,0.000000,0.0,0.0,0.088888,0.0,0.0,00:05:20,00:22:36,5,5,0.000000,0.016112,0.010833,0.002500,0.0,0.033888,0,3,2,1,0,1,NaT,2022-10-07 14:14:39.932,2022-10-07 14:14:26.647,2022-10-07 14:19:02.917,NaT,2022-10-07 14:17:01.123,week_one
4,0.59,0.59,0.69,0.69,64,Pakistan,1996,Male,CAH11-01\tComputing,5,03/10/22 - 09/10/22,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,00:00:00,00:22:36,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0,0,0,0,0,0,NaT,NaT,NaT,NaT,NaT,NaT,week_one

In [16]:
import pandas as pd
import os

file_path = 'UWE_Brsitol_IGP_Project/python_folder/csv_data/data2.xlsx'
if not os.path.exists(file_path):
    raise FileNotFoundError(f"The file '{file_path}' does not exist.")

df1 = pd.read_excel(file_path)
print("Number of columns:", len(df1.columns))
print("Column names:", df1.columns.tolist())

Number of columns: 46
Column names: ['Q17', 'Q12', 'Q14', 'Q10', 'Q10_4_TEXT', 'Q16', 'Q17.1', 'Q18', 'Q14.1', 'Q17_1', 'Q17_2', 'Q17_3', 'Q17_4', 'Q17_5', 'Q17_6', 'Q17_7', 'Q17_8', 'Q17_9', 'Q17_10', 'Q17_11', 'Q1_1', 'Q1_2', 'Q1_3', 'Q1_4', 'Q1_5', 'Q1_6', 'Q1_7', 'Q1_8', 'Q1_9', 'Q1_10', 'Q7_1', 'Q7_2', 'Q7_3', 'Q7_4', 'Q7_5', 'Q7_6', 'Q7_7', 'Q7_8', 'Q7_9', 'Q7_10', 'Q7_11', 'Q7_12', 'Q7_13', 'Q7_14', 'Q7_15', 'Q7_16']

In [17]:
import pandas as pd
import os

file_path = 'UWE_Brsitol_IGP_Project/python_folder/csv_data/data2.xlsx'
if not os.path.exists(file_path):
    raise FileNotFoundError(f"The file '{file_path}' does not exist.")

df1 = pd.read_excel(file_path)

# Example: renaming columns by index (add or adjust as needed)
df1.columns.values[0]  = 'total_marks'
df1.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df1.columns.values[6]  = 'date_range'
df1.columns.values[18] = 'std_act_assignments'
df1.columns.values[19] = 'std_act_learning_materials'
df1.columns.values[20] = 'std_act_module_information_handbook'
df1.columns.values[21] = 'std_act_reading_list'
df1.columns.values[22] = 'std_act_week1'
df1.columns.values[23] = 'std_act_week2'
df1.columns.values[24] = 'no_of_times_accessed_assignments'
df1.columns.values[25] = 'no_of_times_accessed_learning_materials'
df1.columns.values[26] = 'no_of_times_accessed_module_information_handbook'
df1.columns.values[27] = 'no_of_times_accessed_reading_list'
df1.columns.values[28] = 'no_of_times_week1'
df1.columns.values[29] = 'no_of_times_week2'
df1.columns.values[30] = 'initial_access_assignments'
df1.columns.values[31] = 'initial_access_learning_materials'
df1.columns.values[32] = 'initial_access_information_handbook'
df1.columns.values[33] = 'initial_access_reading_list'
df1.columns.values[34] = 'initial_access_week1'
df1.columns.values[35] = 'initial_access_week2'
# You can continue up to df1.columns.values[45] if needed

print("Renamed columns:", df1.columns.tolist())
df1.head()

Renamed columns: ['total_marks', 'Q12', 'what_is_your_year_of_birth_just_the_year', 'Q10', 'Q10_4_TEXT', 'Q16', 'date_range', 'Q18', 'Q14.1', 'Q17_1', 'Q17_2', 'Q17_3', 'Q17_4', 'Q17_5', 'Q17_6', 'Q17_7', 'Q17_8', 'Q17_9', 'std_act_assignments', 'std_act_learning_materials', 'std_act_module_information_handbook', 'std_act_reading_list', 'std_act_week1', 'std_act_week2', 'no_of_times_accessed_assignments', 'no_of_times_accessed_learning_materials', 'no_of_times_accessed_module_information_handbook', 'no_of_times_accessed_reading_list', 'no_of_times_week1', 'no_of_times_week2', 'initial_access_assignments', 'initial_access_learning_materials', 'initial_access_information_handbook', 'initial_access_reading_list', 'initial_access_week1', 'initial_access_week2', 'Q7_7', 'Q7_8', 'Q7_9', 'Q7_10', 'Q7_11', 'Q7_12', 'Q7_13', 'Q7_14', 'Q7_15', 'Q7_16']

,total_marks,Q12,what_is_your_year_of_birth_just_the_year,Q10,Q10_4_TEXT,Q16,date_range,Q18,Q14.1,Q17_1,Q17_2,Q17_3,Q17_4,Q17_5,Q17_6,Q17_7,Q17_8,Q17_9,std_act_assignments,std_act_learning_materials,std_act_module_information_handbook,std_act_reading_list,std_act_week1,std_act_week2,no_of_times_accessed_assignments,no_of_times_accessed_learning_materials,no_of_times_accessed_module_information_handbook,no_of_times_accessed_reading_list,no_of_times_week1,no_of_times_week2,initial_access_assignments,initial_access_learning_materials,initial_access_information_handbook,initial_access_reading_list,initial_access_week1,initial_access_week2,Q7_7,Q7_8,Q7_9,Q7_10,Q7_11,Q7_12,Q7_13,Q7_14,Q7_15,Q7_16
0,Please enter your student ID\n\nWe will use th...,List of Countries,What is your year of birth?,How do you describe yourself? - Selected Choice,How do you describe yourself? - Prefer to self...,What is your first degree subject area?,How many years work experience do you have?,What sectors have you worked in?,Previous experiences of formative assessment a...,"Based on experience or feeling, my expectation...","Based on experience or feeling, my expectation...","Based on experience or feeling, my expectation...","Based on experience or feeling, my expectation...","Based on experience or feeling, my expectation...","Based on experience or feeling, my expectation...","Based on experience or feeling, my expectation...","Based on experience or feeling, my expectation...","Based on experience or feeling, my expectation...","Based on experience or feeling, my expectation...","Based on experience or feeling, my expectation...","I see myself as... - Extraverted, enthusiastic","I see myself as... - Critical, quarrelsome","I see myself as... - Dependable, self-disciplined","I see myself as... - Anxious, easily upset",I see myself as... - Open to a new experiences...,"I see myself as... - Reserved, quiet","I see myself as... - Sympathetic, warm","I see myself as... - Disorganised, careless","I see myself as... - Calm, emotionally stable","I see myself as... - Conventional, uncreative",Why are you doing this module? \nScore by the ...,Why are you doing this module? \nScore by the ...,Why are you doing this module? \nScore by the ...,Why are you doing this module? \nScore by the ...,Why are you doing this module? \nScore by the ...,Why are you doing this module? \nScore by the ...,Why are you doing this module? \nScore by the ...,Why are you doing this module? \nScore by the ...,Why are you doing this module? \nScore by the ...,Why are you doing this module? \nScore by the ...,Why are you doing this module? \nScore by the ...,Why are you doing this module? \nScore by the ...,Why are you doing this module? \nScore by the ...,Why are you doing this module? \nScore by the ...,Why are you doing this module? \nScore by the ...,Why are you doing this module? \nScore by the ...
1,1,United Kingdom of Great Britain and Northern I...,1999,Female,NaN,CAH11-01\tComputing,NaN,OTHER SERVICE ACTIVITIES,NaN,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Agree a little,Agree a little,Agree a little,NaN,Agree a little,Agree moderately,Agree moderately,Agree moderately,Agree a little,Agree moderately,Not At All,A Little,Exactly,A Lot,Enough,Enough,Enough,A Lot,A Lot,Not At All,Not At All,A Little,Moderately,Not At All,Not At All,Not At All
2,2,Nigeria,1992,Male,NaN,CAH11-01\tComputing,4,FINANCIAL AND INSURANCE ACTIVITIES,I have no prior experience of formative assess...,Strongly agree,Strongly agree,Somewhat agree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,Strongly agree,Somewhat agree,Neither agree nor disagree,Strongly agree,Agree strongly,Diagree strongly,Disagree moderately,Diagree strongly,Agree strongly,Agree moderately,Agree moderately,Diagree strongly,Agree moderately,Disagree moderately,Exactly,Exactly,A Little,Moderately,Exactly,Exactly,A Little,Moderately,Moderately,A Lot,Moderately,A Very Little,Exactly,Exactly,A Little,Not At All
3,3,Nigeria,1987,Male,NaN,CAH11-01\tComputing,8,FINANCIAL AND INSURANCE ACTIVITIES,I have some experience,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Somewhat disagree,Strongly agree,Strongly agree,Somewhat disagree,Strongly agree,Agree strongly,Agree a little,Agree strongly,Disagree moderately,Agree strongly,Agree strongly,Agree moderately,Diagree strongly,Agree moderately,Diagree strongly,Exactly,A Lot,Enough,Not At All,Exactly,Exactly,Enough,Not At All,Exactly,A Lot,Enough,Not At All,Exactly,Exactly,Enough,Not At All
4,4,Nigeria,1993,Male,NaN,"CAH24-01\tMedia, journalism and communications",6,"AGRICULTURE, FORESTRY AND FISHING,INFORMATION ...",I have some experience,Strongly agree,Strongly agree,Somewhat agree,Strongly agree,Strongly agree,Strongly agree,Somewhat agree,Somewhat agree,Somewhat agree,NaN,Strongly agree,Agree moderately,Disagree moderately,NaN,Diagree strongly,Agree strongly,Agree moderately,Agree strongly,Diagree strongly,Agree strongly,Diagree strongly,Exactly,Exactly,Exactly,Not At All,A Lot,Exactly,Exactly,Not At All,A Lot,Moderately,Moderately,Not At All,Exactly,Exactly,Exactly,Not At All

In [18]:
import pandas as pd
import os

file_path = 'UWE_Brsitol_IGP_Project/python_folder/csv_data/data2.xlsx'
if not os.path.exists(file_path):
    raise FileNotFoundError(f"The file '{file_path}' does not exist.")

xls = pd.ExcelFile(file_path)

# Use the exact sheet name as it appears in your Excel file, e.g., 'Week 2 ' (with a space if needed)
df2 = pd.read_excel(xls, 'Week 2', skiprows=1)
df2.columns = (
    df2.columns.str.replace(' ', '_')
    .str.replace(',', '')
    .str.lower()
    .str.replace("-", '_')
    .str.replace("?", '')
    .str.replace("(", '')
    .str.replace(")", '')
    .str.replace('.', '')
    .str.replace('&', '')
    .str.replace(":", '')
)
df2 = df2.iloc[:, 4:]
df2['main_week'] = 'week_two'

# Display the cleaned DataFrame
df2.head()

,unnamed_4,unnamed_5,unnamed_6,unnamed_7,unnamed_8,list_of_countries,what_is_your_year_of_birth,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range__week_2,monday,tuesday,wednesday,thursday,friday,saturday,sunday,student_time_in_course,avg_time_per_user,total_items,total_logins,assignments,learning_materials,module_information,reading_list,week_0,week_1,week_2,week_3,assignments1,learning_materials1,module_information1,reading_list1,week_01,week_11,week_21,week_31,assignments2,learning_materials2,module_information2,reading_list2,week_0_introduction,week_12,week_22,week_32,main_week
0,0.56,0.56,0.56,0.56,56,United Kingdom of Great Britain and Northern I...,1999,Female,CAH11-01\tComputing,1,10/10/22 - 16/10/22,0.0,1.157500,0.000000,0.000000,0.010557,13.168055,0.000000,14:20:10,01:44:34,14,16,3.591667,0.002500,0.018888,0.0,0.000000,0.323333,0.217500,0.0,14,4,4,0,0,1,38,0,2022-10-14 09:06:39.702,2022-10-11 11:38:18.649,2022-10-11 11:38:16.944,NaT,NaT,2022-10-11 11:38:20.386,2022-10-16 01:46:19.000,NaT,week_two
1,0.56,0.56,0.56,0.24,48,Nigeria,1992,Male,CAH11-01\tComputing,2,10/10/22 - 16/10/23,0.0,1.806945,0.004722,0.008612,0.000000,0.000000,0.004167,01:49:28,01:44:34,6,10,0.000000,0.009445,0.268610,0.0,0.101667,0.875555,0.000000,0.0,0,7,4,0,2,3,1,0,NaT,2022-10-11 16:48:17.708,2022-10-11 16:32:14.061,NaT,2022-10-11 16:55:11.719,2022-10-11 16:58:20.695,2022-10-11 18:19:45.654,NaT,week_two
2,0.64,0.61,0.64,0.59,62,Nigeria,1987,Male,CAH11-01\tComputing,3,10/10/22 - 16/10/24,0.0,1.332222,0.000000,0.000000,0.000000,0.000000,0.000000,01:19:56,01:44:34,4,4,0.000000,0.002778,0.000000,0.0,0.056388,0.906112,0.000000,0.0,0,3,0,0,1,1,1,0,NaT,2022-10-11 16:59:20.616,NaT,NaT,2022-10-11 16:59:23.751,2022-10-11 17:02:59.094,2022-10-11 18:19:15.047,NaT,week_two
3,0.68,0.68,0.52,0.64,63,Nigeria,1993,Male,"CAH24-01\tMedia, journalism and communications",4,10/10/22 - 16/10/25,0.0,1.570278,0.000000,0.000000,0.010833,0.000000,0.000000,01:34:52,01:44:34,3,3,0.000000,0.005278,0.000000,0.0,0.000000,0.412500,0.800555,0.0,0,2,0,0,0,1,1,0,NaT,2022-10-11 12:47:12.156,NaT,NaT,NaT,2022-10-11 13:35:38.253,2022-10-11 12:47:27.146,NaT,week_two
4,0.59,0.59,0.69,0.69,64,Pakistan,1996,Male,CAH11-01\tComputing,5,10/10/22 - 16/10/26,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,00:00:00,01:44:34,0,0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0,0,0,0,0,0,0,0,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,week_two

In [19]:
import pandas as pd
import os

file_path = 'UWE_Brsitol_IGP_Project/python_folder/csv_data/week2.csv'
if not os.path.exists(file_path):
    raise FileNotFoundError(f"The file '{file_path}' does not exist.")

# Read the CSV file
df2 = pd.read_csv(file_path)

# Rename columns with duplicate or unclear names by index
df2.columns.values[0]  = 'total_marks'
df2.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df2.columns.values[6]  = 'date_range'
df2.columns.values[18] = 'std_act_assignments'
df2.columns.values[19] = 'std_act_learning_materials'
df2.columns.values[20] = 'std_act_module_information_handbook'
df2.columns.values[21] = 'std_act_reading_list'
df2.columns.values[22] = 'std_act_week1'
df2.columns.values[23] = 'std_act_week2'
df2.columns.values[24] = 'std_act_week3'
df2.columns.values[25] = 'no_of_times_accessed_assignments'
df2.columns.values[26] = 'no_of_times_accessed_learning_materials'
df2.columns.values[27] = 'no_of_times_accessed_module_information_handbook'
df2.columns.values[28] = 'no_of_times_accessed_reading_list'
df2.columns.values[29] = 'no_of_times_week1'
df2.columns.values[30] = 'no_of_times_week2'
df2.columns.values[31] = 'no_of_times_week3'
df2.columns.values[32] = 'initial_access_assignments'
df2.columns.values[33] = 'initial_access_learning_materials'
df2.columns.values[34] = 'initial_access_information_handbook'
df2.columns.values[35] = 'initial_access_reading_list'
df2.columns.values[36] = 'initial_access_week1'
df2.columns.values[37] = 'initial_access_week2'
df2.columns.values[38] = 'initial_access_week3'
print("Renamed columns:", df2.columns.tolist())
df2.head()

Renamed columns: ['total_marks', 'list_of_countries', 'what_is_your_year_of_birth_just_the_year', 'how_do_you_describe_yourself___selected_choice', 'what_is_your_first_degree_subject_area', 'student_id', 'date_range', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'student_time_in_course', 'avg_time_per_user', 'total_items', 'total_logins', 'std_act_assignments', 'std_act_learning_materials', 'std_act_module_information_handbook', 'std_act_reading_list', 'std_act_week1', 'std_act_week2', 'std_act_week3', 'no_of_times_accessed_assignments', 'no_of_times_accessed_learning_materials', 'no_of_times_accessed_module_information_handbook', 'no_of_times_accessed_reading_list', 'no_of_times_week1', 'no_of_times_week2', 'no_of_times_week3', 'initial_access_assignments', 'initial_access_learning_materials', 'initial_access_information_handbook', 'initial_access_reading_list', 'initial_access_week1', 'initial_access_week2', 'initial_access_week3']

,total_marks,list_of_countries,what_is_your_year_of_birth_just_the_year,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range,monday,tuesday,wednesday,thursday,friday,saturday,sunday,student_time_in_course,avg_time_per_user,total_items,total_logins,std_act_assignments,std_act_learning_materials,std_act_module_information_handbook,std_act_reading_list,std_act_week1,std_act_week2,std_act_week3,no_of_times_accessed_assignments,no_of_times_accessed_learning_materials,no_of_times_accessed_module_information_handbook,no_of_times_accessed_reading_list,no_of_times_week1,no_of_times_week2,no_of_times_week3,initial_access_assignments,initial_access_learning_materials,initial_access_information_handbook,initial_access_reading_list,initial_access_week1,initial_access_week2,initial_access_week3
0,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",1,10/10/22 - 16/10/22,0.157222,2.300555,0.0,0.0,0.000000,0.0,0.000000,02:27:28,02:21:13,3,5,0,0.681112,0.000000,0.0,0.006112,1.759167,0.0,0,0,3,0,1,2,0,NaN,2022-10-10 14:16:49.242,NaN,NaN,2022-10-10 14:25:20.527,2022-10-10 14:16:55.852,NaN
1,70.0,Nigeria,1996,Male,CAH07-02\tChemistry,2,10/10/22 - 16/10/22,0.085278,1.924167,0.0,0.0,0.000000,0.0,0.000000,02:00:34,02:21:13,3,4,0,0.001945,0.001112,0.0,0.000000,0.016388,0.0,0,2,1,0,1,0,0,NaN,2022-10-10 16:07:41.250,2022-10-10 16:09:02.015,NaN,NaN,2022-10-10 16:07:44.741,NaN
2,65.0,Nigeria,1990,Female,CAH15-02\tEconomics,3,10/10/22 - 16/10/22,0.795833,2.403888,0.0,0.0,0.000000,0.0,0.013612,03:12:48,02:21:13,3,6,0,0.006390,0.003333,0.0,0.000000,0.560833,0.0,0,4,2,0,0,4,0,NaN,2022-10-10 20:32:28.517,2022-10-10 20:32:20.105,NaN,NaN,2022-10-10 20:32:35.934,NaN
3,55.0,Nigeria,1991,Male,CAH15-02\tEconomics,4,10/10/22 - 16/10/22,0.000000,0.000000,0.0,0.0,0.061112,0.0,0.000000,00:03:40,02:21:13,2,2,0,0.001388,0.000000,0.0,0.000000,0.057778,0.0,0,1,0,0,0,1,0,NaN,2022-10-14 12:27:18.186,NaN,NaN,NaN,2022-10-14 12:27:22.967,NaN
4,65.0,Pakistan,1998,Male,CAH17-01\tBusiness and management,5,10/10/22 - 16/10/22,0.337500,3.089167,0.0,0.0,0.000000,0.0,0.000000,03:25:36,02:21:13,5,6,0,0.003888,0.002778,0.0,0.037500,0.004722,0.0,0,4,1,0,3,1,0,NaN,2022-10-11 14:02:17.998,2022-10-11 14:13:01.991,NaN,2022-10-11 14:02:25.595,2022-10-11 15:29:04.753,NaN

In [20]:


#  file paths
file_path1 = 'UWE_Brsitol_IGP_Project/python_folder/csv_data/week1.csv'
file_path2 = 'UWE_Brsitol_IGP_Project/python_folder/csv_data/week2.csv'

if not os.path.exists(file_path1):
    raise FileNotFoundError(f"The file '{file_path1}' does not exist.")
if not os.path.exists(file_path2):
    raise FileNotFoundError(f"The file '{file_path2}' does not exist.")

df1 = pd.read_csv(file_path1)
df2 = pd.read_csv(file_path2)


# Concatenate the two DataFrames
merged_df = pd.concat([df1, df2], ignore_index=True, sort=False)
merged_df

,unnamed_4,list_of_countries,what_is_your_year_of_birth_just_the_year_eg_1995_,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range__week_1,monday,tuesday,wednesday,thursday,friday,saturday,sunday,student_time_in_course,avg_time_per_user,total_items,total_logins,assignments,learning_materials,module_information_handbook,reading_list,week_1,week_2,assignments1,learning_materials1,module_information_handbook.1,reading_list1,week_11,week_21,assignments2,learning_materials2,module_information_handbook1,reading_list2,week_12,week_22,unnamed_40,date_range__week_2,week_3_,week_2_,week_3,week_3.1
0,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",1,03/10/22 - 09/10/22,0.000000,0.005278,0.014722,0.000000,0.000000,0.000000,0.023612,00:02:37,01:19:38,2,4,0,0.007222,0.000000,0.000000,0.016388,0.000000,0,3,0,0,2,0,NaN,2022-10-04 15:45:00.718,NaN,NaN,2022-10-04 15:45:03.544,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,70.0,Nigeria,1996,Male,CAH07-02\tChemistry,2,03/10/22 - 09/10/22,0.000000,3.117500,0.000000,0.000000,0.000000,0.000000,0.000000,03:07:03,01:19:38,3,3,0,0.004167,1.773333,0.000000,1.330555,0.000000,0,3,2,0,2,0,NaN,2022-10-04 15:48:30.421,2022-10-04 14:02:11.582,NaN,2022-10-04 15:48:38.726,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,65.0,Nigeria,1990,Female,CAH15-02\tEconomics,3,03/10/22 - 09/10/22,0.019722,1.710833,0.000000,0.000000,0.000000,0.000000,0.000000,01:43:50,01:19:38,6,9,0,0.007778,0.000555,0.033055,1.628055,0.000000,0,5,2,2,4,0,NaN,2022-10-04 14:05:35.288,2022-10-03 21:49:58.608,2022-10-04 14:01:58.086,2022-10-04 14:05:37.424,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,55.0,Nigeria,1991,Male,CAH15-02\tEconomics,4,03/10/22 - 09/10/22,0.001667,0.018055,0.000000,0.000000,0.000000,0.000000,0.000000,00:01:11,01:19:38,2,4,0,0.001943,0.000000,0.000000,0.000000,0.000000,0,2,0,0,2,0,NaN,2022-10-03 11:15:47.910,NaN,NaN,2022-10-03 11:15:50.346,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,65.0,Pakistan,1998,Male,CAH17-01\tBusiness and management,5,03/10/22 - 09/10/22,0.000000,2.232222,0.052778,0.000000,0.000000,0.000000,0.000000,02:17:06,01:19:38,3,5,0,0.002223,0.001667,0.000000,2.241667,0.000000,0,2,2,0,2,0,NaN,2022-10-04 15:49:31.924,2022-10-05 17:49:47.691,NaN,2022-10-04 15:49:38.697,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,62.0,Nigeria,1985,Male,CAH10-01\tEngineering,6,03/10/22 - 09/10/22,0.000000,5.439445,0.000000,0.000000,0.000000,0.000000,0.000000,05:26:22,01:19:38,4,4,0,0.001945,0.000833,0.000000,4.526667,0.000000,2,1,0,0,2,2,NaN,2022-10-04 12:27:00.446,2022-10-04 11:39:42.832,NaN,2022-10-04 12:27:03.171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,61.0,Nigeria,1985,Male,CAH11-01\tComputing,7,03/10/22 - 09/10/22,0.000000,1.549722,0.011667,0.000000,0.000000,0.000000,0.000000,01:33:41,01:19:38,4,6,0,0.003612,0.004167,0.000000,0.500278,0.000000,0,2,1,0,2,0,NaN,2022-10-04 15:05:07.261,2022-10-04 15:32:40.566,NaN,2022-10-04 15:05:10.582,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,77.0,United Kingdom of Great Britain and Northern I...,2001,Female,"CAH07-04\tGeneral, applied and forensic sciences",8,03/10/22 - 09/10/22,0.088333,2.041388,0.187500,0.000000,0.000000,0.000000,0.000000,02:19:02,01:19:38,4,10,0,0.003055,0.000000,0.006112,0.870000,0.000000,0,6,0,1,5,0,NaN,2022-10-04 09:45:51.107,NaN,2022-10-04 11:21:55.518,2022-10-04 09:45:52.993,NaN,2022-10-04 09:45:52.993,NaN,NaN,NaN,NaN,NaN
8,61.0,Nigeria,1976,Male,CAH03-01\tBiosciences,9,03/10/22 - 09/10/22,0.000000,0.003612,0.000000,0.000000,0.000000,0.000000,0.000000,00:00:13,01:19:38,2,2,0,0.001667,0.000000,0.000000,0.000000,0.000000,0,1,0,0,1,0,NaN,2022-10-04 15:57:44.779,NaN,NaN,2022-10-04 15:57:50.387,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,63.0,India,1998,Female,CAH11-01\tComputing,10,03/10/22 - 09/10/22,2.227223,0.001945,0.000000,0.000000,0.000000,0.000000,0.000000,02:13:45,01:19:38,4,6,0,0.000833,0.000000,2.189722,0.000000,0.000000,0,1,0,4,1,0,NaN,2022-10-04 15:53:32.716,NaN,2022-10-03 13:42:42.702,2022-10-04 15:53:35.542,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,67.0,Nigeria,1996,Female,CAH07-02\tChemistry,11,03/10/22 - 09/10/22,0.000000,2.108333,0.000000,0.000000,0.000000,0.000000,0.000000,02:06:30,01:19:38,3,3,0,0.005833,0.000000,0.000000,1.909167,0.000000,0,3,0,0,1,0,NaN,2022-10-04 15:11:39.609,NaN,NaN,2022-10-04 15:11:44.216,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,66.0,Nigeria,1986,Female,"CAH06-01\tAgriculture, food and related studies",12,03/10/22 - 09/10/22,0.189445,6.689167,0.000000,0.007778,0.049722,0.000000,0.000000,06:56:10,01:19:38,5,13,0,0.006667,0.009445,1.596667,3.158890,0.000000,0,6,1,6,6,0,NaN,2022-10-03 12:18:20.720,2022-10-04 14:33:38.001,2022-10-03 12:18:52.334,2022-10-03 12:18:24.798,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,76.0,United Kingdom of Great Britain and Northern I...,1995,Male,CAH11-01\tComputing,13,03/10/22 - 09/10/22,0.000000,4.679167,0.044167,0.000000,0.000000,0.008888,0.000000,04:43:56,01:19:38,3,5,0,0.002222,1.485278,0.000000,3.145000,0.000000,0,3,3,0,3,0,NaN,2022-10-04 11:04:32.766,2022-10-04 14:14:27.735,NaN,2022-10-04 11:04:37.310,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,57.0,Bangladesh,1997,Female,CAH10-01\tEngineering,14,03/10/22 - 09/10/22,0.000000,3.305000,0.000000,0.000000,0.000000,0.000000,0.000000,03:18:18,01:19:38,8,8,0,0.008888,1.756945,0.058612,1.136667,0.000000,0,4,3,2,3,0,NaN,2022-10-04 12:49:11.031,2022-10-04 12:40:49.049,2022-10-04 12:43:55.031,2022-10-04 12:49:18.623,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,64.0,Italy,2000,Female,CAH16-01\tLaw,15,03/10/22 - 09/10/22,0.276667,0.610833,0.000000,0.072500,0.000000,0.000000,0.001667,00:57:42,01:19:38,3,10,0,0.005555,0.001388,0.000000,0.183333,0.000000,0,6,1,0,5,0,NaN,2022-10-03 15:11:50.041,2022-10-03 15:12:22.128,NaN,2022-10-03 15:11:53.473,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,64.0,Sri Lanka,1993,Female,CAH17-01\tBusiness and management,16,03/10/22 - 09/10/22,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,00:00:00,01:19:38,0,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,78.0,Viet Nam,1999,Male,CAH11-01\tComputing,17,03/10/22 - 09/10/22,0.000000,3.774167,0.021667,0.000000,0.000833,0.000000,1.690833,05:29:15,01:19:38,9,19,0,0.302778,0.004445,1.863612,0.719445,0.000000,0,12,4,4,6,0,NaN,2022-10-04 10:45:34.183,2022-10-04 10:45:16.351,2022-10-04 10:45:27.593,2022-10-04 10:45:35.702,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,63.0,Viet Nam,1996,Female,CAH17-01\tBusiness and management,18,03/10/22 - 09/10/22,0.077222,2.310555,0.000000,0.000000,0.000000,0.000000,0.000000,02:23:16,01:19:38,5,18,0,0.003333,0.002778,0.003890,1.023057,0.000000,0,8,2,8,7,0,NaN,2022-10-03 14:10:57.311,2022-10-03 14:10:54.609,2022-10-03 14:10:53.314,2022-10-03 14:10:59.208,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,62.0,United Kingdom of Great Britain and Northern I...,2001,Male,CAH15-02\tEconomics,19,03/10/22 - 09/10/22,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.016112,00:00:58,01:19:38,1,1,0,0.000278,0.000000,0.000000,0.000000,0.000000,0,1,0,0,0,0,NaN,2022-10-09 23:17:24.116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,62.0,Sri Lanka,1989,Female,CAH17-01\tBusiness and management,20,03/10/22 - 09/10/22,0.000000,0.315000,0.000000,0.000000,0.000000,0.000000,0.000000,00:18:54,01:19:54,4,4,0,0.000555,0.000833,0.000000,0.296388,0.000000,0,1,1,0,1,0,NaN,2022-10-04 23:03:12.885,2022-10-04 23:03:09.998,NaN,2022-10-04 23:03:15.047,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",1,NaN,0.157222,2.300555,0.000000,0.000000,0.000000,0.000000,0.000000,02:27:28,02:21:13,3,5,0,0.681112,0.000000,0.000000,0.006112,1.759167,0,0,3,0,1,2022-10-10 14:16:55.852,NaN,2022-10-10 14:16:49.242,NaN,NaN,2022-10-10 14:25:20.527,NaN,NaN,10/10/22 - 16/10/22,0.000000,2.0,0.0,NaN
21,70.0,Nigeria,1996,Male,CAH07-02\tChemistry,2,NaN,0.085278,1.924167,0.000000,0.000000,0.000000,0.000000,0.000000,02:00:34,02:21:13,3,4,0,0.001945,0.001112,0.000000,0.000000,0.016388,0,2,1,0,1,2022-10-10 16:07:44.741,NaN,2022-10-10 16:07:41.250,2022-10-10 16:09:02.015,NaN,NaN,NaN,NaN,10/10/22 - 16/10/22,0.000000,0.0,0.0,NaN
22,65.0,Nigeria,1990,Female,CAH15-02\tEconomics,3,NaN,0.795833,2.403888,0.000000,0.000000,0.000000,0.000000,0.013612,03:12:48,02:21:13,3,6,0,0.006390,0.003333,0.000000,0.000000,0.560833,0,4,2,0,0,2022-10-10 20:32:35.934,NaN,2022-10-10 20:32:28.517,2022-10-10 20:32:20.105,NaN,NaN,NaN,NaN,10/10/22 - 16/10/22,0.000000,4.0,0.0,NaN
23,55.0,Nigeria,1991,Male,CAH15-02\tEconomics,4,NaN,0.000000,0.000000,0.000000,0.000000,0.061112,0.000000,0.000000,00:03:40,02:21:13,2,2,0,0.001388,0.000000,0.000000,0.000000,0.057778,0,1,0,0,0,2022-10-14 12:27:22.967,NaN,2022-10-14 12:27:18.186,NaN,NaN,NaN,NaN,NaN,10/10/22 - 16/10/22,0.000000,1.0,0.0,NaN
24,65.0,Pakistan,1998,Male,CAH17-01\tBusiness and management,5,NaN,0.337500,3.089167,0.000000,0.000000,0.000000,0.000000,0.000000,03:25:36,02:21:13,5,6,0,0.003888,0.002778,0.000000,0.037500,0.004722,0,4,1,0,3,2022-10-11 15:29:04.753,NaN,2022-10-11 14:02:17.998,2022-10-11 14:13:01.991,NaN,2022-10-11 14:02:25.595,NaN,NaN,10/10/22 - 16/10/22,0.000000,1.0,0.0,NaN
25,62.0,Nigeria,1985,Male,CAH10-01\tEngineering,6,NaN,0.000000,3.400277,0.000000,0.000000,0.000000,0.018610,0.000000,03:25:07,02:21:13,6,13,0,0.061665,0.000555,0.000000,0.261388,2.856667,0,13,1,0,2,2022-10-11 11:25:45.811,NaN,2022-10-11 11:22:45.832,2022-10-11 15:44:20.328,NaN,2022-10-11 15:31:37.239,NaN,NaN,10/10/22 - 16/10/22,0.000833,8.0,2.0,2022-10-15 11:25:51.164
26,61.0,Nigeria,1985,Male,CAH11-01\tComputing,7,NaN,0.000000,3.686667,0.000000,0.000000,2.393055,0.603612,0.000000,06:41:00,02:21:13,10,16,0,0.048333,0.010833,0.081112,0.977777,1.796390,0,15,1,2,3,2022-10-11 14:37:03.267,NaN,2022-10-11 14:02:38.156,2022-10-15 00:40:03.300,2022-10-14 23:11:34.794,2022-10-11 14:03:04.643,NaN,NaN,10/10/22 - 16/10/22,0.033890,8.0,2.0,2022-10-15 01:00:35.391
27,77.0,United Kingdom of Great Britain and Northern I...,2001,Female,"CAH07-04\tGeneral, applied and forensic sciences",8,NaN,0.184443,2.943888,0.000000,0.001388,0.000000,0.000000,0.000000,03:07:46,02:21:13,3,9,0,0.002502,0.008888,0.000000,0.000000,0.074443,0,7,1,0,0,2022-10-10 14:08:39.690,NaN,2022-10-10 14:08:37.975,2022-10-11 14:24:44.977,NaN,NaN,NaN,NaN,10/10/22 - 16/10/22,0.000000,7.0,0.0,NaN
28,61.0,Nigeria,1976,Male,CAH03-01\tBiosciences,9,NaN,0.033612,0.000000,0.218333,0.000000,0.000000,0.000000,2.653612,02:54:20,02:21:13,5,6,0,0.005278,0.004167,0.001112,0.000000,0.005278,0,2,1,1,1,2022-10-12 08:59:55.836,NaN,2022-10-10 05:26:30.737,2022-10-16 15:57:37.969,2022-10-16 15:57:34.365,2022-10-10 05:26:45.779,NaN,NaN,10/10/22 - 16/10/22,0.000000,1.0,0.0,NaN
29,63.0,India,1998,Female,CAH11-01\tComputing,10,NaN,0.378612,1.994723,0.000000,0.002778,0.000000,0.000000,0.000000,02:22:34,02:21:13,4,4,0,0.490000,0.000000,0.010555,0.126388,0.000000,0,2,1,2,1,NaN,NaN,2022-10-11 14:05:07.468,2022-10-10 16:04:40.905,2022-10-10 16:04:38.345,2022-10-11 14:05:10.031,NaN,NaN,10/10/22 - 16/10/22,0.000000,0.0,0.0,NaN
30,67.0,Nigeria,1996,Female,CAH07-02\tChemistry,11,NaN,0.000000,2.746945,0.012500,0.000000,0.004722,0.016667,0.000000,02:46:51,02:21:13,3,7,0,0.003612,0.000000,0.000000,1.128888,0.141945,0,4,0,0,1,2022-10-11 14:01:30.471,NaN,2022-10-11 14:01:27.770,NaN,NaN,2022-10-11 14:09:43.154,NaN,NaN,10/10/22 - 16/10/22,0.000000,3.0,0.0,NaN
31,66.0,Nigeria,1986,Female,"CAH06-01\tAgriculture, food and related studies",12,NaN,0.380000,3.200833,0.000000,0.000000,0.000000,6.344167,5.215278,15:08:25,02:21:13,7,17,0,0.018890,0.015000,0.181112,0.000000,2.392777,0,14,1,1,0,2022-10-10 19:20:31.298,NaN,2022-10-10 19:20:25.648,2022-10-10 19:23:39.544,2022-10-10 19:31:53.459,NaN,NaN,NaN,10/10/22 - 16/10/22,2.261390,7.0,4.0,2022-10-15 18:11:28.679
32,76.0,United Kingdom of Great Britain and Northern I...,1995,Male,CAH11-01\tComputing,13,NaN,0.005833,1.176667,0.000000,0.000000,0.398055,0.050833,0.000000,01:37:53,02:21:13,5,6,0,0.002222,0.000555,0.000000,0.000000,0.012222,0,3,2,0,0,2022-10-11 13:47:09.476,NaN,2022-10-11 13:47:06.802,2022-10-14 20:25:19.077,NaN,NaN,NaN,NaN,10/10/22 - 16/10/22,0.005278,1.0,2.0,2022-10-14 19:56:26.777
33,57.0,Bangladesh,1997,Female,CAH10-01\tEngineering,14,NaN,0.000000,4.493057,0.027222,0.000000,0.000000,0.000000,0.000000,04:31:13,02:21:13,3,3,0,0.003888,0.000000,0.000000,0.360278,2.627778,0,5,0,0,1,2022-10-11 13:59:23.257,NaN,2022-10-11 13:59:19.249,NaN,NaN,2022-10-11 14:49:16.366,NaN,NaN,10/10/22 - 16/10/22,0.000000,4.0,0.0,NaN
34,64.0,Italy,2000,Female,CAH16-01\tLaw,15,NaN,4.064723,0.951112,0.000000,0.000000,0.000000,0.005833,2.123612,07:08:43,02:21:13,7,14,0,0.061945,0.001667,0.000000,1.070555,1.449722,0,9,1,0,1,2022-10-10 11:19:02.415,NaN,2022-10-10 11:18:59.655,2022-10-16 16:20:07.522,NaN,2022-10-10 15:10:22.792,NaN,NaN,10/10/22 - 16/10/22,0.002500,5.0,2.0,2022-10-15 16:03:02.428
35,64.0,Sri Lanka,1993,Female,CAH17-01\tBusiness and management,16,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,00:00:00,02:21:13,0,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10/10/22 - 16/10/22,0.000000,0.0,0.0,NaN
36,78.0,Viet Nam,1999,Male,CAH11-01\tComputing,17,NaN,0.000000,1.222500,0.000000,0.000000,0.022222,0.000000,0.013612,01:15:30,02:21:13,4,7,0,0.003890,0.001388,0.000000,0.000000,0.485555,0,5,2,0,0,2022-10-11 09:38:40.016,NaN,2022-10-11 09:38:38.182,2022-10-11 09:36:16.785,NaN,NaN,NaN,NaN,10/10/22 - 16/10/22,0.000000,7.0,0.0,NaN
37,63.0,Viet Nam,1996,Female,CAH17-01\tBusiness and management,18,NaN,1.826945,4.698055,0.000000,0.000000,0.000000,0.000000,0.000000,06:31:30,02:21:13,2,4,0,0.003057,0.000000,0.000000,0.000000,2.799445,0,7,0,0,0,2022-10-10 13:34:59.179,NaN,2022-10-10 13:34:57.791,NaN,NaN,NaN,NaN,NaN,10/10/22 - 16/10/22,0.000000,6.0,0.0,NaN
38,62.0,United Kingdom of Great Britain and Northern I...,2001,Male,CAH15-02\tEconomics,19,NaN,0.000000,0.270833,0.000000,0.000000,0.000000,0.000000,0.000000,00:16:15,02:21:13,2,2,0,0.000555,0.000000,0.000000,0.003055,0.000000,0,1,0,0,1,NaN,NaN,2022-10-11 14:47:53.096,NaN,NaN,2022-10-11 14:47:55.454,NaN,NaN,10/10/22 - 16/10/22,0.000000,0.0,0.0,NaN
39,62.0,Sri Lanka,1989,Female,CAH17-01\tBusiness and management,20,NaN,1.182778,1.624445,0.000000,0.000000,0.000000,0.000000,0.000000,02:48:26,02:21:13,4,6,0,0.004167,0.000833,0.000000,0.826945,0.528888,0,6,1,0,1,2022-10-10 12:49:40.490,NaN,2022-10-10 11:57:17.773,2022-10-10 11:57:15.185,NaN,2022-10-10 11:57:22.034,NaN,NaN,10/10/22 - 16/10/22,0.000000,5.0,0.0,NaN

In [21]:
# renaming columns with spaces and special characters
week3 = pd.read_excel(xls,'Week 3',skiprows=1)
week3.columns=week3.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
week3 =week3.iloc[:, 4:]
week3['main_week'] = 'week_3'
# show the first few rows of the DataFrame
week3.head()

,unnamed_4,unnamed_5,unnamed_6,unnamed_7,unnamed_8,list_of_countries,what_is_your_year_of_birth,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range__week_3,monday,tuesday,wednesday,thursday,friday,saturday,sunday,student_time_in_course,avg_time_per_user,total_items,total_logins,assignments,learning_materials,module_information,reading_list,week_0,week_1,week_2,week_3,week_4,assignments1,learning_materials1,module_information1,reading_list1,week_01,week_11,week_21,week_31,week_41,assignments2,learning_materials2,module_information2,reading_list2,week_02,week_12,week_22,week_32,week_42,main_week
0,0.56,0.56,0.56,0.56,56,United Kingdom of Great Britain and Northern I...,1999,Female,CAH11-01\tComputing,1,17/10/22 - 23/10/22,0.0,0.09,0.05,7.39,3.33,0.00,0.17,11:02:32,02:08:22,8,31,1.61,0.02,0.01,0.00,0.00,0.0,0.0,1.93,2.31,22,24,13,10,0,0,0,6,4,"Oct 18, 2022, 11:10 AM","Oct 18, 2022, 11:08 AM","Oct 18, 2022, 11:08 AM","Oct 18, 2022, 11:10 AM",NaN,NaN,NaN,"Oct 18, 2022, 11:08 AM","Oct 20, 2022, 1:28 PM",week_3
1,0.56,0.56,0.56,0.24,48,Nigeria,1992,Male,CAH11-01\tComputing,2,17/10/22 - 23/10/22,0.0,2.02,0.16,2.55,0.00,0.07,0.00,04:47:31,02:08:22,9,26,0.19,0.08,0.01,0.01,0.00,0.0,0.0,4.34,0.00,2,18,5,1,0,0,1,12,0,"Oct 21, 2022, 12:00 AM","Oct 17, 2022, 11:43 AM","Oct 18, 2022, 4:39 PM","Oct 18, 2022, 4:55 PM",NaN,NaN,"Oct 17, 2022, 11:43 AM","Oct 18, 2022, 4:40 PM",NaN,week_3
2,0.64,0.61,0.64,0.59,62,Nigeria,1987,Male,CAH11-01\tComputing,3,17/10/22 - 23/10/22,0.0,0.00,0.00,0.00,0.00,0.00,0.00,00:00:08,02:08:22,2,2,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.00,0,1,0,0,0,0,0,1,0,NaN,"Oct 18, 2022, 5:15 PM",NaN,NaN,NaN,NaN,NaN,"Oct 18, 2022, 5:15 PM",NaN,week_3
3,0.68,0.68,0.52,0.64,63,Nigeria,1993,Male,"CAH24-01\tMedia, journalism and communications",4,17/10/22 - 23/10/22,0.0,0.72,0.00,0.02,1.22,0.00,0.00,01:58:02,02:08:22,9,13,0.32,0.02,0.00,0.00,0.01,0.0,0.0,0.60,0.00,2,8,0,1,1,0,0,5,0,"Oct 18, 2022, 11:48 AM","Oct 18, 2022, 11:11 AM",NaN,"Oct 21, 2022, 2:14 PM","Oct 18, 2022, 11:12 AM",NaN,NaN,"Oct 18, 2022, 11:11 AM",NaN,week_3
4,0.59,0.59,0.69,0.69,64,Pakistan,1996,Male,CAH11-01\tComputing,5,17/10/22 - 23/10/22,0.0,0.00,0.00,0.00,0.00,0.00,0.00,00:00:00,02:08:22,0,0,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.00,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,week_3

In [22]:
week3 = pd.read_excel(xls,'Week 3',skiprows=1)
week3.columns=week3.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
week3 =week3.iloc[:, 4:]
week3['main_week'] = 'week_3'

In [23]:
# renaming columns with duplicate names
week3.columns.values[0] = 'total_marks'
week3.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
week3.columns.values[6]  =  'date_range'
week3.columns.values[18] = 'std_act_assignments'
week3.columns.values[19] = 'std_act_learning_materials'
week3.columns.values[20] = 'std_act_module_information_handbook'
week3.columns.values[21] = 'std_act_reading_list'
week3.columns.values[22] = 'std_act_week1'
week3.columns.values[23] = 'std_act_week2'
week3.columns.values[24] = 'std_act_week3'
week3.columns.values[25] = 'std_act_df5'
week3.columns.values[26] = 'no_of_times_accessed_assignments'
week3.columns.values[27] = 'no_of_times_accessed_learning_materials'
week3.columns.values[28] = 'no_of_times_accessed_module_information_handbook'
week3.columns.values[29] = 'no_of_times_accessed_reading_list'
week3.columns.values[30] = 'no_of_times_week1'
week3.columns.values[31] = 'no_of_times_week2'
week3.columns.values[32] = 'no_of_times_week3'
week3.columns.values[33] = 'no_of_times_week4'
week3.columns.values[34] = 'initial_access_assignments'
week3.columns.values[35] = 'initial_access_learning_materials'
week3.columns.values[36] = 'initial_access_information_handbook'
week3.columns.values[37] = 'initial_access_reading_list'
week3.columns.values[38] = 'initial_access_week1'
week3.columns.values[39] = 'initial_access_week2'
week3.columns.values[40] = 'initial_access_week3'
week3.columns.values[41] = 'initial_access_week4'
week3 = week3.copy()

# Show the first few rows to verify changes
week3.head()
print(week3.columns.tolist())

['total_marks', 'unnamed_5', 'what_is_your_year_of_birth_just_the_year', 'unnamed_7', 'unnamed_8', 'list_of_countries', 'date_range', 'how_do_you_describe_yourself___selected_choice', 'what_is_your_first_degree_subject_area', 'student_id', 'date_range__week_3', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'std_act_assignments', 'std_act_learning_materials', 'std_act_module_information_handbook', 'std_act_reading_list', 'std_act_week1', 'std_act_week2', 'std_act_week3', 'std_act_df5', 'no_of_times_accessed_assignments', 'no_of_times_accessed_learning_materials', 'no_of_times_accessed_module_information_handbook', 'no_of_times_accessed_reading_list', 'no_of_times_week1', 'no_of_times_week2', 'no_of_times_week3', 'no_of_times_week4', 'initial_access_assignments', 'initial_access_learning_materials', 'initial_access_information_handbook', 'initial_access_reading_list', 'initial_access_week1', 'initial_access_week2', 'initial_access_week3', 'initial_access_week4', 'module_information2', 'reading_list2', 'week_02', 'week_12', 'week_22', 'week_32', 'week_42', 'main_week']

In [24]:


file_path = 'UWE_Brsitol_IGP_Project/python_folder/csv_data/data2.xlsx'
if not os.path.exists(file_path):
    raise FileNotFoundError(f"The file '{file_path}' does not exist.")
xls = pd.ExcelFile(file_path)

# Load and clean Week 1
df1 = pd.read_excel(xls, 'Week 1 ', skiprows=1)
df1.columns = (
    df1.columns.str.replace(' ', '_')
    .str.replace(',', '')
    .str.lower()
    .str.replace("-", '_')
    .str.replace("?", '')
    .str.replace("(", '')
    .str.replace(")", '')
    .str.replace('.', '')
    .str.replace('&', '')
    .str.replace(":", '')
)
df1 = df1.iloc[:, 4:]
df1['main_week'] = 'week_one'

# Load and clean Week 2
df2 = pd.read_excel(xls, 'Week 2', skiprows=1)
df2.columns = (
    df2.columns.str.replace(' ', '_')
    .str.replace(',', '')
    .str.lower()
    .str.replace("-", '_')
    .str.replace("?", '')
    .str.replace("(", '')
    .str.replace(")", '')
    .str.replace('.', '')
    .str.replace('&', '')
    .str.replace(":", '')
)
df2 = df2.iloc[:, 4:]
df2['main_week'] = 'week_two'

In [25]:
merged_df = pd.concat([df1, df2], ignore_index=True, sort=False)
merged_df = pd.concat([merged_df, week3], ignore_index=True, sort=False)
merged_df = merged_df.fillna('NA')
merged_df.shape

(408, 78)

In [26]:
# renaming columns with spaces and special characters
week4 = pd.read_excel(xls,'Week 4',skiprows=1)
week4.columns=week4.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
week4 = week4 =week4.iloc[:, 4:]
week4['main_week'] = 'week5'

In [27]:
# renaming columns with duplicate names
week4.columns.values[0]  = 'total_marks'
week4.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
week4.columns.values[6]  = 'date_range'
week4.columns.values[18] = 'std_act_assignments'
week4.columns.values[19] = 'std_act_learning_materials'
week4.columns.values[20] = 'std_act_module_information_handbook'
week4.columns.values[21] = 'std_act_reading_list'
week4.columns.values[22] = 'std_act_week1'
week4.columns.values[23] = 'std_act_week2'
week4.columns.values[24] = 'std_act_week3'
week4.columns.values[25] = 'std_act_week4'
week4.columns.values[26] = 'std_act_week5'
week4.columns.values[27] = 'std_act_week6'
week4.columns.values[28] = 'std_act_week7'
week4.columns.values[29] = 'no_of_times_accessed_assignments'
week4.columns.values[30] = 'no_of_times_accessed_learning_materials'
week4.columns.values[31] = 'no_of_times_accessed_module_information_handbook'
week4.columns.values[32] = 'no_of_times_accessed_reading_list'
week4.columns.values[33] = 'no_of_times_week1'
week4.columns.values[34] = 'no_of_times_week2'
week4.columns.values[35] = 'no_of_times_week3'
week4.columns.values[36] = 'no_of_times_week4'
week4.columns.values[37] = 'no_of_times_week5'
week4.columns.values[38] = 'no_of_times_week6'
week4.columns.values[39] = 'no_of_times_week7'
week4.columns.values[40] = 'initial_access_assignments'
week4.columns.values[41] = 'initial_access_learning_materials'
week4.columns.values[42] = 'initial_access_information_handbook'
week4.columns.values[43] = 'initial_access_reading_list'
week4.columns.values[44] = 'initial_access_week1'
week4.columns.values[45] = 'initial_access_week2'
week4.columns.values[46] = 'initial_access_week3'
week4.columns.values[47] = 'initial_access_week4'
week4.columns.values[48] = 'initial_access_week5'
week4.columns.values[49] = 'initial_access_week6'
week4.columns.values[50] = 'initial_access_week7'

# Show the first few rows to verify changes
week4.head()
print(week4.columns.tolist())

['total_marks', 'unnamed_5', 'what_is_your_year_of_birth_just_the_year', 'unnamed_7', 'unnamed_8', 'list_of_countries', 'date_range', 'how_do_you_describe_yourself___selected_choice', 'what_is_your_first_degree_subject_area', 'student_id', 'date_range__week_4', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'std_act_assignments', 'std_act_learning_materials', 'std_act_module_information_handbook', 'std_act_reading_list', 'std_act_week1', 'std_act_week2', 'std_act_week3', 'std_act_week4', 'std_act_week5', 'std_act_week6', 'std_act_week7', 'no_of_times_accessed_assignments', 'no_of_times_accessed_learning_materials', 'no_of_times_accessed_module_information_handbook', 'no_of_times_accessed_reading_list', 'no_of_times_week1', 'no_of_times_week2', 'no_of_times_week3', 'no_of_times_week4', 'no_of_times_week5', 'no_of_times_week6', 'no_of_times_week7', 'initial_access_assignments', 'initial_access_learning_materials', 'initial_access_information_handbook', 'initial_access_reading_list', 'initial_access_week1', 'initial_access_week2', 'initial_access_week3', 'initial_access_week4', 'initial_access_week5', 'initial_access_week6', 'initial_access_week7', 'week_52', 'main_week']

In [28]:
merged_df = pd.concat([merged_df, week4], ignore_index=True,sort=False)
merged_df = merged_df.fillna('NA')
merged_df.shape

(544, 90)

In [29]:
# renaming columns with spaces and special characters
df5 = pd.read_excel(xls,'Week 5',skiprows=1)
df5.columns=df5.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df5 =df5.iloc[:, 4:]
df5['main_week'] = 'week_five'
[i for i in enumerate(df5.columns)]

[(0, 'unnamed_4'),
 (1, 'unnamed_5'),
 (2, 'unnamed_6'),
 (3, 'unnamed_7'),
 (4, 'unnamed_8'),
 (5, 'list_of_countries'),
 (6, 'what_is_your_year_of_birth'),
 (7, 'how_do_you_describe_yourself___selected_choice'),
 (8, 'what_is_your_first_degree_subject_area'),
 (9, 'student_id'),
 (10, 'date_range__week_5'),
 (11, 'monday'),
 (12, 'tuesday'),
 (13, 'wednesday'),
 (14, 'thursday'),
 (15, 'friday'),
 (16, 'saturday'),
 (17, 'sunday'),
 (18, 'student_time_in_course'),
 (19, 'avg_time_per_user'),
 (20, 'total_items'),
 (21, 'total_logins'),
 (22, 'assignments'),
 (23, 'learning_materials'),
 (24, 'module_information'),
 (25, 'reading_list'),
 (26, 'week_0'),
 (27, 'week_1'),
 (28, 'week_2'),
 (29, 'week_3'),
 (30, 'week_4'),
 (31, 'week_5'),
 (32, 'week_6'),
 (33, 'feedback_task_1_journal'),
 (34, 'assignments1'),
 (35, 'learning_materials1'),
 (36, 'module_information1'),
 (37, 'reading_list1'),
 (38, 'week_01'),
 (39, 'week_11'),
 (40, 'week_21'),
 (41, 'week_31'),
 (42, 'week_41'),
 (43, 'week_51'),
 (44, 'week_61'),
 (45, 'feedback_task_1_journal1'),
 (46, 'assignments2'),
 (47, 'learning_materials2'),
 (48, 'module_information2'),
 (49, 'reading_list2'),
 (50, 'week_02'),
 (51, 'week_12'),
 (52, 'week_22'),
 (53, 'week_32'),
 (54, 'week_42'),
 (55, 'week_52'),
 (56, 'week_62'),
 (57, 'feedback_task_1_journal2'),
 (58, 'main_week')]

In [30]:
# renaming columns with duplicate names
df5.columns.values[0]  = 'total_marks'
df5.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df5.columns.values[6]  = 'date_range'
df5.columns.values[18] = 'std_act_assignments'
df5.columns.values[19] = 'std_act_learning_materials'
df5.columns.values[20] = 'std_act_module_information_handbook'
df5.columns.values[21] = 'std_act_reading_list'
df5.columns.values[22] = 'std_act_week1'
df5.columns.values[23] = 'std_act_week2'
df5.columns.values[24] = 'std_act_week3'
df5.columns.values[25] = 'std_act_week4'
df5.columns.values[26] = 'std_act_week5'
df5.columns.values[27] = 'std_act_week6'
df5.columns.values[28] = 'no_of_times_accessed_assignments'
df5.columns.values[29] = 'no_of_times_accessed_learning_materials'
df5.columns.values[30] = 'no_of_times_accessed_module_information_handbook'
df5.columns.values[31] = 'no_of_times_accessed_reading_list'
df5.columns.values[32] = 'no_of_times_week1'
df5.columns.values[33] = 'no_of_times_week2'
df5.columns.values[34] = 'no_of_times_week3'
df5.columns.values[35] = 'no_of_times_week4'
df5.columns.values[36] = 'no_of_times_week5'
df5.columns.values[37] = 'no_of_times_week6'
df5.columns.values[38] = 'initial_access_assignments'
df5.columns.values[39] = 'initial_access_learning_materials'
df5.columns.values[40] = 'initial_access_information_handbook'
df5.columns.values[41] = 'initial_access_reading_list'
df5.columns.values[42] = 'initial_access_week1'
df5.columns.values[43] = 'initial_access_week2'
df5.columns.values[44] = 'initial_access_week3'
df5.columns.values[45] = 'initial_access_week4'
df5.columns.values[46] = 'initial_access_week5'
df5.columns.values[47] = 'initial_access_week6'

# Show the first few rows to verify changes
df5.head()
print(df5.columns.tolist())

['total_marks', 'unnamed_5', 'what_is_your_year_of_birth_just_the_year', 'unnamed_7', 'unnamed_8', 'list_of_countries', 'date_range', 'how_do_you_describe_yourself___selected_choice', 'what_is_your_first_degree_subject_area', 'student_id', 'date_range__week_5', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'std_act_assignments', 'std_act_learning_materials', 'std_act_module_information_handbook', 'std_act_reading_list', 'std_act_week1', 'std_act_week2', 'std_act_week3', 'std_act_week4', 'std_act_week5', 'std_act_week6', 'no_of_times_accessed_assignments', 'no_of_times_accessed_learning_materials', 'no_of_times_accessed_module_information_handbook', 'no_of_times_accessed_reading_list', 'no_of_times_week1', 'no_of_times_week2', 'no_of_times_week3', 'no_of_times_week4', 'no_of_times_week5', 'no_of_times_week6', 'initial_access_assignments', 'initial_access_learning_materials', 'initial_access_information_handbook', 'initial_access_reading_list', 'initial_access_week1', 'initial_access_week2', 'initial_access_week3', 'initial_access_week4', 'initial_access_week5', 'initial_access_week6', 'module_information2', 'reading_list2', 'week_02', 'week_12', 'week_22', 'week_32', 'week_42', 'week_52', 'week_62', 'feedback_task_1_journal2', 'main_week']

In [31]:
merged_df = pd.concat([merged_df,df5],ignore_index=True,sort=False)
merged_df.fillna('NA',inplace=True)
merged_df.shape

C:\Users\Owner\AppData\Local\Temp\ipykernel_16080\2639349055.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'NA' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  merged_df.fillna('NA',inplace=True)

(680, 93)

In [32]:
# renaming columns with spaces and special characters
df6 = pd.read_excel(xls,'Week 6',skiprows=1)
df6.columns=df6.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df6 = df6.iloc[:, 4:]
df6['main_week'] = 'week_six'

In [33]:
# renaming columns with duplicate names
df6.columns.values[0] = 'total_marks'
df6.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df6.columns.values[6]  = 'date_range'
df6.columns.values[18] = 'std_act_assignments'
df6.columns.values[19] = 'std_act_learning_materials'
df6.columns.values[20] = 'std_act_module_information_handbook'
df6.columns.values[21] = 'std_act_reading_list'
df6.columns.values[22] = 'std_act_week1'
df6.columns.values[23] = 'std_act_week2'
df6.columns.values[24] = 'std_act_week3'
df6.columns.values[25] = 'std_act_week4'
df6.columns.values[26] = 'std_act_week5'
df6.columns.values[27] = 'std_act_week6'
df6.columns.values[28] = 'std_act_week7'
df6.columns.values[29] = 'no_of_times_accessed_assignments'
df6.columns.values[30] = 'no_of_times_accessed_learning_materials'
df6.columns.values[31] = 'no_of_times_accessed_module_information_handbook'
df6.columns.values[32] = 'no_of_times_accessed_reading_list'
df6.columns.values[33] = 'no_of_times_week1'
df6.columns.values[34] = 'no_of_times_week2'
df6.columns.values[35] = 'no_of_times_week3'
df6.columns.values[36] = 'no_of_times_week4'
df6.columns.values[37] = 'no_of_times_week5'
df6.columns.values[38] = 'no_of_times_week6'
df6.columns.values[39] = 'no_of_times_week7'
df6.columns.values[40] = 'initial_access_assignments'
df6.columns.values[41] = 'initial_access_learning_materials'
df6.columns.values[42] = 'initial_access_information_handbook'
df6.columns.values[43] = 'initial_access_reading_list'
df6.columns.values[44] = 'initial_access_week1'
df6.columns.values[45] = 'initial_access_week2'
df6.columns.values[46] = 'initial_access_week3'
df6.columns.values[47] = 'initial_access_week4'
df6.columns.values[48] = 'initial_access_week5'
df6.columns.values[49] = 'initial_access_week6'
df6.columns.values[50] = 'initial_access_week7'

In [34]:
merged_df = pd.concat([merged_df,df6],ignore_index=True,sort=False)
merged_df.fillna('NA', inplace=True)
merged_df.shape

C:\Users\Owner\AppData\Local\Temp\ipykernel_16080\2672650768.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'NA' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  merged_df.fillna('NA', inplace=True)

(816, 96)

In [35]:
# renaming columns with spaces and special characters
df7 = pd.read_excel(xls,'Week 7',skiprows=1)
df7.columns=df7.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df7 = df7.iloc[:, 4:]
df7['main_week'] = 'week_seven'
[i for i in enumerate(df7.columns)]

[(0, 'unnamed_4'),
 (1, 'unnamed_5'),
 (2, 'unnamed_6'),
 (3, 'unnamed_7'),
 (4, 'unnamed_8'),
 (5, 'list_of_countries'),
 (6, 'what_is_your_year_of_birth'),
 (7, 'how_do_you_describe_yourself___selected_choice'),
 (8, 'what_is_your_first_degree_subject_area'),
 (9, 'student_id'),
 (10, 'date_range__week_7'),
 (11, 'monday'),
 (12, 'tuesday'),
 (13, 'wednesday'),
 (14, 'thursday'),
 (15, 'friday'),
 (16, 'saturday'),
 (17, 'sunday'),
 (18, 'student_time_in_course'),
 (19, 'avg_time_per_user'),
 (20, 'total_items'),
 (21, 'total_logins'),
 (22, 'assignments'),
 (23, 'learning_materials'),
 (24, 'module_information'),
 (25, 'reading_list'),
 (26, 'week_0'),
 (27, 'week_1'),
 (28, 'week_2'),
 (29, 'week_3'),
 (30, 'week_4'),
 (31, 'week_5'),
 (32, 'week_6'),
 (33, 'week_7'),
 (34, 'week_8'),
 (35, 'feedback_task_1_journal'),
 (36, 'feedback_task_2_journal'),
 (37, 'feedback_task_3_journal'),
 (38, 'assignments1'),
 (39, 'learning_materials1'),
 (40, 'module_information1'),
 (41, 'reading_list1'),
 (42, 'week_01'),
 (43, 'week_11'),
 (44, 'week_21'),
 (45, 'week_31'),
 (46, 'week_41'),
 (47, 'week_51'),
 (48, 'week_61'),
 (49, 'week_71'),
 (50, 'week_81'),
 (51, 'feedback_task_1_journal1'),
 (52, 'feedback_task_2_journal1'),
 (53, 'feedback_task_3_journal1'),
 (54, 'assignments2'),
 (55, 'learning_materials2'),
 (56, 'module_information2'),
 (57, 'reading_list2'),
 (58, 'week_02'),
 (59, 'week_12'),
 (60, 'week_22'),
 (61, 'week_32'),
 (62, 'week_42'),
 (63, 'week_52'),
 (64, 'week_62'),
 (65, 'week_72'),
 (66, 'week_82'),
 (67, 'feedback_task_1_journal2'),
 (68, 'feedback_task_2_journal2'),
 (69, 'feedback_task_3_journal2'),
 (70, 'main_week')]

In [36]:
# renaming columns with duplicate names
df7.columns.values[0]  = 'total_marks'
df7.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df7.columns.values[6]  = 'date_range'
df7.columns.values[18] = 'std_act_assignments'
df7.columns.values[19] = 'std_act_learning_materials'
df7.columns.values[20] = 'std_act_module_information_handbook'
df7.columns.values[21] = 'std_act_reading_list'
df7.columns.values[22] = 'std_act_week1'
df7.columns.values[23] = 'std_act_week2'
df7.columns.values[24] = 'std_act_week3'
df7.columns.values[25] = 'std_act_week4'
df7.columns.values[26] = 'std_act_week5'
df7.columns.values[27] = 'std_act_week6'
df7.columns.values[28] = 'std_act_week7'
df7.columns.values[29] = 'std_act_week8'
df7.columns.values[30] = 'no_of_times_accessed_assignments'
df7.columns.values[31] = 'no_of_times_accessed_learning_materials'
df7.columns.values[32] = 'no_of_times_accessed_module_information_handbook'
df7.columns.values[33] = 'no_of_times_accessed_reading_list'
df7.columns.values[34] = 'no_of_times_week1'
df7.columns.values[35] = 'no_of_times_week2'
df7.columns.values[36] = 'no_of_times_week3'
df7.columns.values[37] = 'no_of_times_week4'
df7.columns.values[38] = 'no_of_times_week5'
df7.columns.values[39] = 'no_of_times_week6'
df7.columns.values[40] = 'no_of_times_week7'
df7.columns.values[41] = 'no_of_times_week8'
df7.columns.values[42] = 'initial_access_assignments'
df7.columns.values[43] = 'initial_access_learning_materials'
df7.columns.values[44] = 'initial_access_information_handbook'
df7.columns.values[45] = 'initial_access_reading_list'
df7.columns.values[46] = 'initial_access_week1'
df7.columns.values[47] = 'initial_access_week2'
df7.columns.values[48] = 'initial_access_week3'
df7.columns.values[49] = 'initial_access_week4'
df7.columns.values[50] = 'initial_access_week5'
df7.columns.values[51] = 'initial_access_week6'
df7.columns.values[52] = 'initial_access_week7'
df7.columns.values[53] = 'initial_access_week8'

# Show the first few rows to verify changes
df7.head()
print(df7.columns.tolist())

['total_marks', 'unnamed_5', 'what_is_your_year_of_birth_just_the_year', 'unnamed_7', 'unnamed_8', 'list_of_countries', 'date_range', 'how_do_you_describe_yourself___selected_choice', 'what_is_your_first_degree_subject_area', 'student_id', 'date_range__week_7', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'std_act_assignments', 'std_act_learning_materials', 'std_act_module_information_handbook', 'std_act_reading_list', 'std_act_week1', 'std_act_week2', 'std_act_week3', 'std_act_week4', 'std_act_week5', 'std_act_week6', 'std_act_week7', 'std_act_week8', 'no_of_times_accessed_assignments', 'no_of_times_accessed_learning_materials', 'no_of_times_accessed_module_information_handbook', 'no_of_times_accessed_reading_list', 'no_of_times_week1', 'no_of_times_week2', 'no_of_times_week3', 'no_of_times_week4', 'no_of_times_week5', 'no_of_times_week6', 'no_of_times_week7', 'no_of_times_week8', 'initial_access_assignments', 'initial_access_learning_materials', 'initial_access_information_handbook', 'initial_access_reading_list', 'initial_access_week1', 'initial_access_week2', 'initial_access_week3', 'initial_access_week4', 'initial_access_week5', 'initial_access_week6', 'initial_access_week7', 'initial_access_week8', 'assignments2', 'learning_materials2', 'module_information2', 'reading_list2', 'week_02', 'week_12', 'week_22', 'week_32', 'week_42', 'week_52', 'week_62', 'week_72', 'week_82', 'feedback_task_1_journal2', 'feedback_task_2_journal2', 'feedback_task_3_journal2', 'main_week']

In [37]:
merged_df = pd.concat([merged_df, df7], ignore_index=True, sort=False)
merged_df.fillna('NA', inplace=True)
merged_df.shape

C:\Users\Owner\AppData\Local\Temp\ipykernel_16080\4078301476.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'NA' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  merged_df.fillna('NA', inplace=True)
C:\Users\Owner\AppData\Local\Temp\ipykernel_16080\4078301476.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'NA' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  merged_df.fillna('NA', inplace=True)

(952, 102)

In [38]:
# Check the actual sheet names
print(xls.sheet_names)

# Use the exact sheet name as printed above
df8 = pd.read_excel(xls, 'Week8', skiprows=1)  # <-- note the space if present
df8.columns = (
    df8.columns.str.replace(' ', '_')
    .str.replace(',', '')
    .str.lower()
    .str.replace("-", '_')
    .str.replace("?", '')
    .str.replace("(", '')
    .str.replace(")", '')
    .str.replace('.', '')
    .str.replace('&', '')
    .str.replace(":", '')
)
df8 = df8.iloc[:, 4:]
df8['main_week'] = 'week_eight'

for idx, col in enumerate(df8.columns):
    print(idx, col)

df8.head()

['QUESTIONNAIRE', 'QuestNumericValues', 'RetrospectiveNumeric', 'Week 1 ', 'Week 2', 'Week 3', 'Week 4', 'Week 5', 'Week 6', 'Week 7', 'Week8', 'Week 9', 'Week 10', '11 only 2']
0 unnamed_4
1 unnamed_5
2 unnamed_6
3 unnamed_7
4 unnamed_8
5 list_of_countries
6 what_is_your_year_of_birth
7 how_do_you_describe_yourself___selected_choice
8 what_is_your_first_degree_subject_area
9 student_id
10 date_range__week_8
11 monday
12 tuesday
13 wednesday
14 thursday
15 friday
16 saturday
17 sunday
18 student_time_in_course
19 avg_time_per_user
20 total_items
21 total_logins
22 assignments
23 learning_materials
24 module_information
25 reading_list
26 week_0
27 week_1
28 week_2
29 week_3
30 week_4
31 week_5
32 week_6
33 week_7
34 week_8
35 week_9
36 feedback_task_1_journal
37 feedback_task_2_journal
38 feedback_task_3_journal
39 assignments1
40 learning_materials1
41 module_information1
42 reading_list1
43 week_01
44 week_11
45 week_21
46 week_31
47 week_41
48 week_51
49 week_61
50 week_71
51 week_81
52 week_91
53 feedback_task_1_journal1
54 feedback_task_2_journal1
55 feedback_task_3_journal1
56 assignments2
57 learning_materials2
58 module_information2
59 reading_list2
60 week_02
61 week_12
62 week_22
63 week_32
64 week_42
65 week_52
66 week_62
67 week_72
68 week_82
69 week_92
70 feedback_task_1_journal2
71 feedback_task_2_journal2
72 feedback_task_3_journal2
73 main_week

,unnamed_4,unnamed_5,unnamed_6,unnamed_7,unnamed_8,list_of_countries,what_is_your_year_of_birth,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range__week_8,monday,tuesday,wednesday,thursday,friday,saturday,sunday,student_time_in_course,avg_time_per_user,total_items,total_logins,assignments,learning_materials,module_information,reading_list,week_0,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,feedback_task_1_journal,feedback_task_2_journal,feedback_task_3_journal,assignments1,learning_materials1,module_information1,reading_list1,week_01,week_11,week_21,week_31,week_41,week_51,week_61,week_71,week_81,week_91,feedback_task_1_journal1,feedback_task_2_journal1,feedback_task_3_journal1,assignments2,learning_materials2,module_information2,reading_list2,week_02,week_12,week_22,week_32,week_42,week_52,week_62,week_72,week_82,week_92,feedback_task_1_journal2,feedback_task_2_journal2,feedback_task_3_journal2,main_week
0,0.56,0.56,0.56,0.56,56,United Kingdom of Great Britain and Northern I...,1999,Female,CAH11-01\tComputing,1,21/11/22 - 27/11/22,0.0,0.542222,0.0,0.0,0.000000,0.0,0.000000,00:32:32,01:53:22,4,4,0.000833,0.001667,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,NaN,NaN,NaN,2,1,0,0,0,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,2022-11-22 11:05:12.209,2022-11-22 11:37:35.117,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,2022-11-22 11:37:40.966,NaT,NaT,NaT,NaT,week_eight
1,0.56,0.56,0.56,0.24,48,Nigeria,1992,Male,CAH11-01\tComputing,2,21/11/22 - 27/11/22,0.0,0.170833,0.0,0.0,0.000000,0.0,0.001945,00:10:22,01:53:22,4,5,0.000000,0.092778,0.029167,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,NaN,NaN,NaN,1,1,3,0,0,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,2022-11-27 18:07:05.690,2022-11-22 16:27:08.468,2022-11-22 14:11:33.065,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,2022-11-22 16:32:41.998,NaT,NaT,NaT,NaT,week_eight
2,0.64,0.61,0.64,0.59,62,Nigeria,1987,Male,CAH11-01\tComputing,3,21/11/22 - 27/11/22,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,00:00:00,01:53:22,0,0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,week_eight
3,0.68,0.68,0.52,0.64,63,Nigeria,1993,Male,"CAH24-01\tMedia, journalism and communications",4,21/11/22 - 27/11/22,0.0,0.004167,0.0,0.0,0.000000,0.0,0.000000,00:00:15,01:53:22,2,2,0.000000,0.001667,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,NaN,NaN,NaN,0,1,0,0,0,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,NaT,2022-11-22 11:41:33.640,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,2022-11-22 11:41:39.679,NaT,NaT,NaT,NaT,week_eight
4,0.59,0.59,0.69,0.69,64,Pakistan,1996,Male,CAH11-01\tComputing,5,21/11/22 - 27/11/22,0.0,3.099167,0.0,0.0,0.470833,0.0,0.000000,03:34:12,01:53:22,7,8,1.650833,0.020000,0.000000,0.0,0.0,0.0,0.0,1.049722,0.0,0.083055,0.120555,0.0,0.629167,0.0,NaN,NaN,NaN,3,8,0,0,0,0,0,2,0,1,1,0,3,0,NaN,NaN,NaN,2022-11-22 14:59:56.630,2022-11-22 15:07:42.520,NaT,NaT,NaT,NaT,NaT,2022-11-22 15:07:53.071,NaT,2022-11-22 18:00:14.057,2022-11-22 17:08:48.876,NaT,2022-11-22 17:16:06.962,NaT,NaT,NaT,NaT,week_eight

In [39]:
# renaming columns with spaces and special characters
print(xls.sheet_names)  # Check the exact sheet name
df8 = pd.read_excel(xls, 'Week8', skiprows=1)  
df8.columns = (
    df8.columns.str.replace(' ', '_')
    .str.replace(',', '')
    .str.lower()
    .str.replace("-", '_')
    .str.replace("?", '')
    .str.replace("(", '')
    .str.replace(")", '')
    .str.replace('.', '')
    .str.replace('&', '')
    .str.replace(":", '')
)
df8 = df8.iloc[:, 4:]
df8['main_week'] = 'week_eight'

# renaming columns with duplicate names
df8.columns.values[0]  = 'total_marks'
df8.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df8.columns.values[6]  = 'date_range'
df8.columns.values[18] = 'std_act_assignments'
df8.columns.values[19] = 'std_act_learning_materials'
df8.columns.values[20] = 'std_act_module_information_handbook'
df8.columns.values[21] = 'std_act_reading_list'
df8.columns.values[22] = 'std_act_week1'
df8.columns.values[23] = 'std_act_week2'
df8.columns.values[24] = 'std_act_week3'
df8.columns.values[25] = 'std_act_week4'
df8.columns.values[26] = 'std_act_week5'
df8.columns.values[27] = 'std_act_week6'
df8.columns.values[28] = 'std_act_week7'
df8.columns.values[29] = 'std_act_week8'
df8.columns.values[30] = 'std_act_week9'
df8.columns.values[31] = 'no_of_times_accessed_assignments'
df8.columns.values[32] = 'no_of_times_accessed_learning_materials'
df8.columns.values[33] = 'no_of_times_accessed_module_information_handbook'
df8.columns.values[34] = 'no_of_times_accessed_reading_list'
df8.columns.values[35] = 'no_of_times_week1'
df8.columns.values[36] = 'no_of_times_week2'
df8.columns.values[37] = 'no_of_times_week3'
df8.columns.values[38] = 'no_of_times_week4'
df8.columns.values[39] = 'no_of_times_week5'
df8.columns.values[40] = 'no_of_times_week6'
df8.columns.values[41] = 'no_of_times_week7'
df8.columns.values[42] = 'no_of_times_week8'
df8.columns.values[43] = 'no_of_times_week9'
df8.columns.values[44] = 'initial_access_assignments'
df8.columns.values[45] = 'initial_access_learning_materials'
df8.columns.values[46] = 'initial_access_information_handbook'
df8.columns.values[47] = 'initial_access_reading_list'
df8.columns.values[48] = 'initial_access_week1'
df8.columns.values[49] = 'initial_access_week2'
df8.columns.values[50] = 'initial_access_week3'
df8.columns.values[51] = 'initial_access_week4'
df8.columns.values[52] = 'initial_access_week5'
df8.columns.values[53] = 'initial_access_week6'
df8.columns.values[54] = 'initial_access_week7'
df8.columns.values[55] = 'initial_access_week8'
df8.columns.values[56] = 'initial_access_week9'

# Show the first few rows to verify changes
df8.head()

['QUESTIONNAIRE', 'QuestNumericValues', 'RetrospectiveNumeric', 'Week 1 ', 'Week 2', 'Week 3', 'Week 4', 'Week 5', 'Week 6', 'Week 7', 'Week8', 'Week 9', 'Week 10', '11 only 2']

,total_marks,unnamed_5,what_is_your_year_of_birth_just_the_year,unnamed_7,unnamed_8,list_of_countries,date_range,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range__week_8,monday,tuesday,wednesday,thursday,friday,saturday,sunday,std_act_assignments,std_act_learning_materials,std_act_module_information_handbook,std_act_reading_list,std_act_week1,std_act_week2,std_act_week3,std_act_week4,std_act_week5,std_act_week6,std_act_week7,std_act_week8,std_act_week9,no_of_times_accessed_assignments,no_of_times_accessed_learning_materials,no_of_times_accessed_module_information_handbook,no_of_times_accessed_reading_list,no_of_times_week1,no_of_times_week2,no_of_times_week3,no_of_times_week4,no_of_times_week5,no_of_times_week6,no_of_times_week7,no_of_times_week8,no_of_times_week9,initial_access_assignments,initial_access_learning_materials,initial_access_information_handbook,initial_access_reading_list,initial_access_week1,initial_access_week2,initial_access_week3,initial_access_week4,initial_access_week5,initial_access_week6,initial_access_week7,initial_access_week8,initial_access_week9,learning_materials2,module_information2,reading_list2,week_02,week_12,week_22,week_32,week_42,week_52,week_62,week_72,week_82,week_92,feedback_task_1_journal2,feedback_task_2_journal2,feedback_task_3_journal2,main_week
0,0.56,0.56,0.56,0.56,56,United Kingdom of Great Britain and Northern I...,1999,Female,CAH11-01\tComputing,1,21/11/22 - 27/11/22,0.0,0.542222,0.0,0.0,0.000000,0.0,0.000000,00:32:32,01:53:22,4,4,0.000833,0.001667,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,NaN,NaN,NaN,2,1,0,0,0,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,2022-11-22 11:05:12.209,2022-11-22 11:37:35.117,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,2022-11-22 11:37:40.966,NaT,NaT,NaT,NaT,week_eight
1,0.56,0.56,0.56,0.24,48,Nigeria,1992,Male,CAH11-01\tComputing,2,21/11/22 - 27/11/22,0.0,0.170833,0.0,0.0,0.000000,0.0,0.001945,00:10:22,01:53:22,4,5,0.000000,0.092778,0.029167,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,NaN,NaN,NaN,1,1,3,0,0,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,2022-11-27 18:07:05.690,2022-11-22 16:27:08.468,2022-11-22 14:11:33.065,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,2022-11-22 16:32:41.998,NaT,NaT,NaT,NaT,week_eight
2,0.64,0.61,0.64,0.59,62,Nigeria,1987,Male,CAH11-01\tComputing,3,21/11/22 - 27/11/22,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,00:00:00,01:53:22,0,0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,week_eight
3,0.68,0.68,0.52,0.64,63,Nigeria,1993,Male,"CAH24-01\tMedia, journalism and communications",4,21/11/22 - 27/11/22,0.0,0.004167,0.0,0.0,0.000000,0.0,0.000000,00:00:15,01:53:22,2,2,0.000000,0.001667,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,NaN,NaN,NaN,0,1,0,0,0,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,NaT,2022-11-22 11:41:33.640,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,2022-11-22 11:41:39.679,NaT,NaT,NaT,NaT,week_eight
4,0.59,0.59,0.69,0.69,64,Pakistan,1996,Male,CAH11-01\tComputing,5,21/11/22 - 27/11/22,0.0,3.099167,0.0,0.0,0.470833,0.0,0.000000,03:34:12,01:53:22,7,8,1.650833,0.020000,0.000000,0.0,0.0,0.0,0.0,1.049722,0.0,0.083055,0.120555,0.0,0.629167,0.0,NaN,NaN,NaN,3,8,0,0,0,0,0,2,0,1,1,0,3,0,NaN,NaN,NaN,2022-11-22 14:59:56.630,2022-11-22 15:07:42.520,NaT,NaT,NaT,NaT,NaT,2022-11-22 15:07:53.071,NaT,2022-11-22 18:00:14.057,2022-11-22 17:08:48.876,NaT,2022-11-22 17:16:06.962,NaT,NaT,NaT,NaT,week_eight

In [40]:
merged_df = pd.concat([merged_df,df8],ignore_index=True,sort=False)
merged_df.fillna('NA', inplace=True)
merged_df




merged_df.shape

C:\Users\Owner\AppData\Local\Temp\ipykernel_16080\1550580804.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'NA' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  merged_df.fillna('NA', inplace=True)
C:\Users\Owner\AppData\Local\Temp\ipykernel_16080\1550580804.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'NA' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  merged_df.fillna('NA', inplace=True)

(1088, 107)

In [41]:
# renaming columns with spaces and special characters
df9 = pd.read_excel(xls,'Week 9',skiprows=1)
df9.columns=df9.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df9 = df9.iloc[:, 4:]
df9['main_week'] = 'week_nine'

[i for i in enumerate(df9.columns)]

[(0, 'unnamed_4'),
 (1, 'unnamed_5'),
 (2, 'unnamed_6'),
 (3, 'unnamed_7'),
 (4, 'unnamed_8'),
 (5, 'list_of_countries'),
 (6, 'what_is_your_year_of_birth'),
 (7, 'how_do_you_describe_yourself___selected_choice'),
 (8, 'what_is_your_first_degree_subject_area'),
 (9, 'student_id'),
 (10, 'date_range__week_9'),
 (11, 'monday'),
 (12, 'tuesday'),
 (13, 'wednesday'),
 (14, 'thursday'),
 (15, 'friday'),
 (16, 'saturday'),
 (17, 'sunday'),
 (18, 'student_time_in_course'),
 (19, 'avg_time_per_user'),
 (20, 'total_items'),
 (21, 'total_logins'),
 (22, 'assignments'),
 (23, 'learning_materials'),
 (24, 'module_information'),
 (25, 'reading_list'),
 (26, 'week_0'),
 (27, 'week_1'),
 (28, 'week_2'),
 (29, 'week_3'),
 (30, 'week_4'),
 (31, 'week_5'),
 (32, 'week_6'),
 (33, 'week_7'),
 (34, 'week_8'),
 (35, 'week_9'),
 (36, 'week_10'),
 (37, 'feedback_task_1_journal'),
 (38, 'feedback_task_2_journal'),
 (39, 'feedback_task_3_journal'),
 (40, 'feedback_task_4_journal'),
 (41, 'assignments1'),
 (42, 'learning_materials1'),
 (43, 'module_information1'),
 (44, 'reading_list1'),
 (45, 'week_01'),
 (46, 'week_11'),
 (47, 'week_21'),
 (48, 'week_31'),
 (49, 'week_41'),
 (50, 'week_51'),
 (51, 'week_61'),
 (52, 'week_71'),
 (53, 'week_81'),
 (54, 'week_91'),
 (55, 'week_101'),
 (56, 'feedback_task_1_journal1'),
 (57, 'feedback_task_2_journal1'),
 (58, 'feedback_task_3_journal1'),
 (59, 'feedback_task_4_journal1'),
 (60, 'assignments2'),
 (61, 'learning_materials2'),
 (62, 'module_information2'),
 (63, 'reading_list2'),
 (64, 'week_02'),
 (65, 'week_12'),
 (66, 'week_22'),
 (67, 'week_32'),
 (68, 'week_42'),
 (69, 'week_52'),
 (70, 'week_62'),
 (71, 'week_72'),
 (72, 'week_82'),
 (73, 'week_92'),
 (74, 'week_102'),
 (75, 'feedback_task_1_journal2'),
 (76, 'feedback_task_2_journal2'),
 (77, 'feedback_task_3_journal2'),
 (78, 'feedback_task_4_journal2'),
 (79, 'main_week')]

In [42]:
# renaming columns with spaces and special characters
df9 = pd.read_excel(xls, 'Week 9', skiprows=1)
df9.columns = (
    df9.columns.str.replace(' ', '_')
    .str.replace(',', '')
    .str.lower()
    .str.replace("-", '_')
    .str.replace("?", '')
    .str.replace("(", '')
    .str.replace(")", '')
    .str.replace('.', '')
    .str.replace('&', '')
    .str.replace(":", '')
)
df9 = df9.iloc[:, 4:]
df9['main_week'] = 'week_nine'

# renaming columns with duplicate names
df9.columns.values[0]  = 'total_marks'
df9.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df9.columns.values[6]  = 'date_range'
df9.columns.values[18] = 'std_act_assignments'
df9.columns.values[19] = 'std_act_learning_materials'
df9.columns.values[20] = 'std_act_module_information_handbook'
df9.columns.values[21] = 'std_act_reading_list'
df9.columns.values[22] = 'std_act_week1'
df9.columns.values[23] = 'std_act_week2'
df9.columns.values[24] = 'std_act_week3'
df9.columns.values[25] = 'std_act_week4'
df9.columns.values[26] = 'std_act_week5'
df9.columns.values[27] = 'std_act_week6'
df9.columns.values[28] = 'std_act_week7'
df9.columns.values[29] = 'std_act_week8'
df9.columns.values[30] = 'std_act_week9'
df9.columns.values[31] = 'std_act_week10'
df9.columns.values[32] = 'no_of_times_accessed_assignments'
df9.columns.values[33] = 'no_of_times_accessed_learning_materials'
df9.columns.values[34] = 'no_of_times_accessed_module_information_handbook'
df9.columns.values[35] = 'no_of_times_accessed_reading_list'
df9.columns.values[36] = 'no_of_times_week1'
df9.columns.values[37] = 'no_of_times_week2'
df9.columns.values[38] = 'no_of_times_week3'
df9.columns.values[39] = 'no_of_times_week4'
df9.columns.values[40] = 'no_of_times_week5'
df9.columns.values[41] = 'no_of_times_week6'
df9.columns.values[42] = 'no_of_times_week7'
df9.columns.values[43] = 'no_of_times_week8'
df9.columns.values[44] = 'no_of_times_week9'
df9.columns.values[45] = 'no_of_times_week10'
df9.columns.values[46] = 'initial_access_assignments'
df9.columns.values[47] = 'initial_access_learning_materials'
df9.columns.values[48] = 'initial_access_information_handbook'
df9.columns.values[49] = 'initial_access_reading_list'
df9.columns.values[50] = 'initial_access_week1'
df9.columns.values[51] = 'initial_access_week2'
df9.columns.values[52] = 'initial_access_week3'
df9.columns.values[53] = 'initial_access_week4'
df9.columns.values[54] = 'initial_access_week5'
df9.columns.values[55] = 'initial_access_week6'
df9.columns.values[56] = 'initial_access_week7'
df9.columns.values[57] = 'initial_access_week8'
df9.columns.values[58] = 'initial_access_week9'
df9.columns.values[59] = 'initial_access_week10'

# Show the first few rows to verify changes
df9.head()

,total_marks,unnamed_5,what_is_your_year_of_birth_just_the_year,unnamed_7,unnamed_8,list_of_countries,date_range,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range__week_9,monday,tuesday,wednesday,thursday,friday,saturday,sunday,std_act_assignments,std_act_learning_materials,std_act_module_information_handbook,std_act_reading_list,std_act_week1,std_act_week2,std_act_week3,std_act_week4,std_act_week5,std_act_week6,std_act_week7,std_act_week8,std_act_week9,std_act_week10,no_of_times_accessed_assignments,no_of_times_accessed_learning_materials,no_of_times_accessed_module_information_handbook,no_of_times_accessed_reading_list,no_of_times_week1,no_of_times_week2,no_of_times_week3,no_of_times_week4,no_of_times_week5,no_of_times_week6,no_of_times_week7,no_of_times_week8,no_of_times_week9,no_of_times_week10,initial_access_assignments,initial_access_learning_materials,initial_access_information_handbook,initial_access_reading_list,initial_access_week1,initial_access_week2,initial_access_week3,initial_access_week4,initial_access_week5,initial_access_week6,initial_access_week7,initial_access_week8,initial_access_week9,initial_access_week10,assignments2,learning_materials2,module_information2,reading_list2,week_02,week_12,week_22,week_32,week_42,week_52,week_62,week_72,week_82,week_92,week_102,feedback_task_1_journal2,feedback_task_2_journal2,feedback_task_3_journal2,feedback_task_4_journal2,main_week
0,0.56,0.56,0.56,0.56,56,United Kingdom of Great Britain and Northern I...,1999,Female,CAH11-01\tComputing,1,28/11/22 - 04/12/22,0.000000,1.079167,0.000000,0.750000,0.000000,0.078612,0.0,01:54:28,01:54:24,11,18,0.002777,0.009722,0.000555,0.000555,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.905278,0.006667,0.004445,NaN,NaN,NaN,NaN,5,7,1,2,0,0,0,0,0,0,0,0,2,2,1,NaN,NaN,NaN,NaN,2022-12-01 09:56:00.440,2022-11-29 11:41:26.054,2022-12-01 10:04:07.687,2022-12-01 10:03:35.176,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,2022-11-29 11:41:31.782,2022-11-29 12:45:46.125,2022-12-01 10:36:36.406,NaT,NaT,NaT,NaT,week_nine
1,0.56,0.56,0.56,0.24,48,Nigeria,1992,Male,CAH11-01\tComputing,2,28/11/22 - 04/12/22,0.385833,0.000000,1.531388,1.384722,2.269445,2.916945,0.0,08:29:18,01:54:24,10,18,0.063055,3.316388,0.003612,0.000555,0.539722,0.114445,0.0,1.846945,0.771667,1.249167,0.0,0.0,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,1,13,2,1,2,2,0,3,3,4,0,0,0,0,0,NaN,NaN,NaN,NaN,2022-11-28 18:26:38.798,2022-11-28 18:30:26.251,2022-12-02 22:43:15.128,2022-12-01 18:12:58.279,2022-11-28 18:30:33.456,2022-11-30 14:51:18.796,NaT,2022-11-30 14:58:19.564,2022-12-01 17:27:28.945,2022-12-01 18:44:46.269,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,week_nine
2,0.64,0.61,0.64,0.59,62,Nigeria,1987,Male,CAH11-01\tComputing,3,28/11/22 - 04/12/22,0.000000,1.310000,0.000000,0.000000,0.000000,0.000000,0.0,01:18:36,01:54:24,2,2,0.000000,0.001945,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaT,2022-11-29 17:22:06.476,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,week_nine
3,0.68,0.68,0.52,0.64,63,Nigeria,1993,Male,"CAH24-01\tMedia, journalism and communications",4,28/11/22 - 04/12/22,0.000000,4.635833,0.000000,0.000000,0.000000,0.000000,0.0,04:38:09,01:54:24,8,8,0.000833,0.007500,0.000000,0.000000,0.000000,0.005555,0.0,0.000000,0.000000,1.656667,0.0,0.0,0.602778,0.000000,0.000000,NaN,NaN,NaN,NaN,3,9,0,0,0,1,0,1,0,1,0,0,3,0,0,NaN,NaN,NaN,NaN,2022-11-29 12:41:15.593,2022-11-29 10:42:36.020,NaT,NaT,NaT,2022-11-29 15:20:14.776,NaT,2022-11-29 15:20:37.822,NaT,2022-11-29 10:42:41.841,NaT,NaT,2022-11-29 12:41:20.989,NaT,NaT,NaT,NaT,NaT,NaT,week_nine
4,0.59,0.59,0.69,0.69,64,Pakistan,1996,Male,CAH11-01\tComputing,5,28/11/22 - 04/12/22,0.000000,0.019445,0.000000,0.000000,0.000000,0.000000,0.0,00:01:10,01:54:24,8,10,0.001388,0.003610,0.000000,0.003055,0.005000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.001667,0.000000,NaN,NaN,NaN,NaN,1,4,0,2,1,2,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,NaN,2022-11-29 13:28:36.347,2022-11-29 13:28:46.425,NaT,2022-11-29 13:28:41.445,2022-11-29 13:28:50.925,2022-11-29 13:29:29.702,NaT,NaT,NaT,NaT,NaT,NaT,NaT,2022-11-29 16:44:26.579,NaT,NaT,NaT,NaT,NaT,week_nine