In [507]:
#importing libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as matplot
import re
import logging
import os
import warnings
warnings.filterwarnings("ignore")

In [508]:
#reading excel with multiple sheets and selecting a specific sheet
xls = pd.ExcelFile('csv_data/data1.xlsx')
demo_week_2 = pd.read_excel(xls,'Demographics',skiprows=1)
demo_week_2 = demo_week_2.iloc[:,1:]
demo_week_2.columns = demo_week_2.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')

In [509]:
demo_week_2.columns.values[8] = 'enjoy_working_in_the_team'
demo_week_2.columns.values[9] = 'team_communication_will_be_highly_effective'
demo_week_2.columns.values[10] = 'team_communication_will_be_very_frequent'
demo_week_2.columns.values[11] = 'bond_perosnally_with_my_team_members'
demo_week_2.columns.values[12] = 'we_will_collaborate_together_on_the_same_tasks'
demo_week_2.columns.values[13] = 'work_separately_and_link_up_our_work_later'
demo_week_2.columns.values[14] = 'develop_my_professional_skills'
demo_week_2.columns.values[15] = 'develop_my_team_working_skills'
demo_week_2.columns.values[16] = 'adjust_the_project_regularly'
demo_week_2.columns.values[17] = 'we_will_stick_to_our_original_project'
demo_week_2.columns.values[18] = 'we_will_produce_an_end_result'
demo_week_2.columns.values[29] = 'module_is_interesting'
demo_week_2.columns.values[30] = 'because_i_am_doing_it_for_my_own_good'
demo_week_2.columns.values[31] = 'because_i_am_supposed_to_do_it'
demo_week_2.columns.values[32] = 'i_don’t_see_any_good_reasons_in_the_module'
demo_week_2.columns.values[33] = 'because_i_think_that_this_module_is_pleasant'
demo_week_2.columns.values[34] = 'because_i_think_that_this_module_is_good_for_me'
demo_week_2.columns.values[35] = 'because_it_is_something_that_i_have_to_do'
demo_week_2.columns.values[36] = 'not_worth_it'
demo_week_2.columns.values[37] = 'because_this_module_looks_funny'
demo_week_2.columns.values[38] = 'by_personal_decision'
demo_week_2.columns.values[39] = 'because_i_dont_have_any_choice' 
demo_week_2.columns.values[40] = 'module_brings_nothing'
demo_week_2.columns.values[41] = 'because_i_feel_good_about_this_module'
demo_week_2.columns.values[42] = 'it_is_important'
demo_week_2.columns.values[43] = 'because_i_feel_that_i_have_to_do_it'
demo_week_2.columns.values[44] = 'it_is_a_good_thing_to_pursue_it'

In [510]:
demo_week_2.drop_duplicates().reset_index(drop=True).to_csv('demo_week_2.csv', index=False)

demo_week_2.columns

Index(['list_of_countries',
       'what_is_your_year_of_birth_just_the_year_eg_1995_',
       'how_do_you_describe_yourself___selected_choice',
       'how_do_you_describe_yourself___prefer_to_self_describe___text',
       'what_is_your_first_degree_subject_area',
       'how_many_years_work_experience_do_you_have',
       'what_sectors_have_you_worked_in',
       'previous_experiences_of_team_working_in_study_and_work',
       'enjoy_working_in_the_team',
       'team_communication_will_be_highly_effective',
       'team_communication_will_be_very_frequent',
       'bond_perosnally_with_my_team_members',
       'we_will_collaborate_together_on_the_same_tasks',
       'work_separately_and_link_up_our_work_later',
       'develop_my_professional_skills', 'develop_my_team_working_skills',
       'adjust_the_project_regularly', 'we_will_stick_to_our_original_project',
       'we_will_produce_an_end_result',
       'i_see_myself_as___extraverted_enthusiastic',
       'i_see_myself_as___critical_quarrelsome',
       'i_see_myself_as___dependable_self_disciplined',
       'i_see_myself_as___anxious_easily_upset',
       'i_see_myself_as___open_to_a_new_experiences_complex',
       'i_see_myself_as___reserved_quiet',
       'i_see_myself_as___sympathetic_warm',
       'i_see_myself_as___disorganised_careless',
       'i_see_myself_as___calm_emotionally_stable',
       'i_see_myself_as___conventional_uncreative', 'module_is_interesting',
       'because_i_am_doing_it_for_my_own_good',
       'because_i_am_supposed_to_do_it',
       'i_don’t_see_any_good_reasons_in_the_module',
       'because_i_think_that_this_module_is_pleasant',
       'because_i_think_that_this_module_is_good_for_me',
       'because_it_is_something_that_i_have_to_do', 'not_worth_it',
       'because_this_module_looks_funny', 'by_personal_decision',
       'because_i_dont_have_any_choice', 'module_brings_nothing',
       'because_i_feel_good_about_this_module', 'it_is_important',
       'because_i_feel_that_i_have_to_do_it',
       'it_is_a_good_thing_to_pursue_it'],
      dtype='object')

In [511]:
#reading excel with multiple sheets and selecting a specific sheet
demo_numeric = pd.read_excel(xls,'Numeric Demographic',skiprows=1)
demo_numeric.columns = demo_numeric.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')

In [512]:
demo_numeric.columns.values[8] = 'previous_experiences_of_team_working_in_study_and_work'
demo_numeric.columns.values[9] = 'i_will_enjoy_working_in_the_team'
demo_numeric.columns.values[10] = 'team_communication_will_be_highly_effective'
demo_numeric.columns.values[11] = 'team_communication_will_be_very_frequent'
demo_numeric.columns.values[12] = 'my_team_will_bond_personally_as_well_as_professionally'
demo_numeric.columns.values[13] = 'we_will_collaborate_together_on_the_same_tasks'
demo_numeric.columns.values[14] = 'work_on_separate_tasks_and_link_them_together_later_on'
demo_numeric.columns.values[15] = 'develop_my_professional_skills_as_a_result_of_the_team_project'
demo_numeric.columns.values[16] = 'develop_my_team_working_skills_and_collaboration'
demo_numeric.columns.values[16] = 'develop_my_team_working_skills_and_collaboration'
demo_numeric.columns.values[17] = 'we_will_adjust_the_project_regularly_as_we_go_along'
demo_numeric.columns.values[18] = 'we_will_stick_to_our_original_project_plan'
demo_numeric.columns.values[19] = 'we_will_produce_an_end_result_which_we_are_proud_of'
demo_numeric.columns.values[30] = 'because_i_think_that_this_module_is_interesting'
demo_numeric.columns.values[31] = 'because_i_am_doing_it_for_my_own_good'
demo_numeric.columns.values[32] = 'because_i_am_supposed_to_do_it'
demo_numeric.columns.values[33] = 'personally_i_don’t_see_any_good_reasons_in_the_module'
demo_numeric.columns.values[34] = 'because_i_think_that_this_module_is_pleasant'
demo_numeric.columns.values[35] = 'because_i_think_that_this_module_is_good_for_me'
demo_numeric.columns.values[36] = 'because_it_is_something_that_i_have_to_do'
demo_numeric.columns.values[37] = 'not_sure_if_it_is_worth_it'
demo_numeric.columns.values[38] = 'because_this_module_looks_fun'
demo_numeric.columns.values[39] = 'by_personal_decision' 
demo_numeric.columns.values[40] = 'because_i_don’t_have_any_choice'
demo_numeric.columns.values[41] = 'i_don’t_see_what_this_module_brings_me'
demo_numeric.columns.values[42] = 'feel_good_about_this_module'
demo_numeric.columns.values[43] = 'because_i_feel_that_i_have_to_do_it'
demo_numeric.columns.values[44] = 'it_is_a_good_thing_to_pursue_it'
demo_numeric.columns.values[45] = 'not_sure_it_is_a_good_thing_to_pursue_it'

In [513]:
demo_numeric.drop_duplicates().reset_index(drop=True).to_csv('demo_numeric.csv', index=False)

In [514]:
#reading excel with multiple sheets and selecting a specific sheet
Retro_numeric = pd.read_excel(xls,'Retro numeric',skiprows=1)
Retro_numeric.columns = Retro_numeric.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')

In [515]:
Retro_numeric.columns.values[0] = 'please_enter_your_student_id'
Retro_numeric.columns.values[1] = 'i_really_enjoyed_working_in_the_team'
Retro_numeric.columns.values[2] = "team_communication_was_highly_effective"
Retro_numeric.columns.values[3] = "team_communication_was_very_frequent"
Retro_numeric.columns.values[4] = "bonded_personally_as_well_as_professionally"
Retro_numeric.columns.values[5] = "we_tended_to_collaborate_together_on_the_same_tasks"
Retro_numeric.columns.values[6] = "work_on_separate_tasks_and_link_them_together_later_on"
Retro_numeric.columns.values[7] = "dev_my_profess_skills_as_a_result_of_the_team_project"
Retro_numeric.columns.values[8] = "my_approach_to_collab_as_a_result_of_the_team_project"
Retro_numeric.columns.values[9] = "adjust_the_project_regularly_as_we_went_along"
Retro_numeric.columns.values[10] = "we_stuck_to_our_original_project_plan"
Retro_numeric.columns.values[11] = "overall_i_am_pleased_with_our_end_result"
Retro_numeric.columns.values[12] = "things_that_you_felt_went_well"
Retro_numeric.columns.values[13] = "the_team_could_have_done_better"
Retro_numeric.columns.values[14] = "how_many_hours_per_week_outside_classes"
Retro_numeric.drop_duplicates().reset_index(drop=True).to_csv('Retro_numeric.csv', index=False)

In [516]:
#reading excel with multiple sheets and selecting a specific sheetx
Retrospective = pd.read_excel(xls,'Retrospective',skiprows=1,na_values='NA')
Retrospective.columns = Retrospective.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')

In [517]:
Retrospective.columns.values[0] = 'please_enter_your_student_id'
Retrospective.columns.values[1] = 'i_really_enjoyed_working_in_the_team'
Retrospective.columns.values[2] = "team_communication_was_highly_effective"
Retrospective.columns.values[3] = "team_communication_was_very_frequent"
Retrospective.columns.values[4] = "bonded_personally_as_well_as_professionally"
Retrospective.columns.values[5] = "we_tended_to_collaborate_together_on_the_same_tasks"
Retrospective.columns.values[6] = "work_on_separate_tasks_and_link_them_together_later_on"
Retrospective.columns.values[7] = "dev_my_profess_skills_as_a_result_of_the_team_project"
Retrospective.columns.values[8] = "my_approach_to_collab_as_a_result_of_the_team_project"
Retrospective.columns.values[9] = "adjust_the_project_regularly_as_we_went_along"
Retrospective.columns.values[10] = "we_stuck_to_our_original_project_plan"
Retrospective.columns.values[11] = "overall_i_am_pleased_with_our_end_result"
Retrospective.columns.values[12] = "things_that_you_felt_went_well"
Retrospective.columns.values[13] = "the_team_could_have_done_better"
Retrospective.columns.values[14] = "how_many_hours_per_week_outside_classes"
Retrospective.drop_duplicates().reset_index(drop=True).to_csv('Retrospective.csv', index=False)

In [518]:
Retrospective.columns

Index(['please_enter_your_student_id', 'i_really_enjoyed_working_in_the_team',
       'team_communication_was_highly_effective',
       'team_communication_was_very_frequent',
       'bonded_personally_as_well_as_professionally',
       'we_tended_to_collaborate_together_on_the_same_tasks',
       'work_on_separate_tasks_and_link_them_together_later_on',
       'dev_my_profess_skills_as_a_result_of_the_team_project',
       'my_approach_to_collab_as_a_result_of_the_team_project',
       'adjust_the_project_regularly_as_we_went_along',
       'we_stuck_to_our_original_project_plan',
       'overall_i_am_pleased_with_our_end_result',
       'things_that_you_felt_went_well', 'the_team_could_have_done_better',
       'how_many_hours_per_week_outside_classes'],
      dtype='object')

In [519]:
# renaming columns with spaces and special characters
df1 = pd.read_excel(xls,'Week 1',skiprows=1)
df1.columns = df1.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df1 = df1.iloc[:, 4:]
df1['main_week'] = 'Week 1'
df1.drop('unnamed_40', axis=1,inplace=True)

In [520]:
# renaming columns with duplicate names
df1.columns.values[0]  = 'total_marks'
df1.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df1.columns.values[6]  = 'date_range'
df1.columns.values[18] = 'std_act_assignments'
df1.columns.values[19] = 'std_act_learning_materials'
df1.columns.values[20] = 'std_act_module_information_handbook'
df1.columns.values[21] = 'std_act_reading_list'
df1.columns.values[22] = 'std_act_week1'
df1.columns.values[23] = 'std_act_week2'
df1.columns.values[24] = 'no_of_times_accessed_assignments'
df1.columns.values[25] = 'no_of_times_accessed_learning_materials'
df1.columns.values[26] = 'no_of_times_accessed_module_information_handbook'
df1.columns.values[27] = 'no_of_times_accessed_reading_list'
df1.columns.values[28] = 'no_of_times_week1'
df1.columns.values[29] = 'no_of_times_week2'
df1.columns.values[30] = 'initial_access_assignments'
df1.columns.values[31] = 'initial_access_learning_materials'
df1.columns.values[32] = 'initial_access_information_handbook'
df1.columns.values[33] = 'initial_access_reading_list'
df1.columns.values[34] = 'initial_access_week1'
df1.columns.values[35] = 'initial_access_week2'

In [521]:
# renaming columns with spaces and special characters
df2 = pd.read_excel(xls,'Week 2',skiprows=1)
df2.columns=df2.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df2 = df2.iloc[:, 4:]
df2['main_week'] = 'Week 2'

In [522]:
# renaming columns with duplicate names
df2.columns.values[0] = 'total_marks'
df2.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df2.columns.values[6]  = 'date_range'
df2.columns.values[18] = 'std_act_assignments'
df2.columns.values[19] = 'std_act_learning_materials'
df2.columns.values[20] = 'std_act_module_information_handbook'
df2.columns.values[21] = 'std_act_reading_list'
df2.columns.values[22] = 'std_act_week1'
df2.columns.values[23] = 'std_act_week2'
df2.columns.values[24] = 'std_act_week3'
df2.columns.values[25] = 'no_of_times_accessed_assignments'
df2.columns.values[26] = 'no_of_times_accessed_learning_materials'
df2.columns.values[27] = 'no_of_times_accessed_module_information_handbook'
df2.columns.values[28] = 'no_of_times_accessed_reading_list'
df2.columns.values[29] = 'no_of_times_week1'
df2.columns.values[30] = 'no_of_times_week2'
df2.columns.values[31] = 'no_of_times_week3'
df2.columns.values[32] = 'initial_access_assignments'
df2.columns.values[33] = 'initial_access_learning_materials'
df2.columns.values[34] = 'initial_access_information_handbook'
df2.columns.values[35] = 'initial_access_reading_list'
df2.columns.values[36] = 'initial_access_week1'
df2.columns.values[37] = 'initial_access_week2'
df2.columns.values[38] = 'initial_access_week3'

In [523]:
merged_df = pd.concat([df1,df2], ignore_index=True,sort=False)
merged_df

,total_marks,list_of_countries,what_is_your_year_of_birth_just_the_year,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range,monday,tuesday,wednesday,...,initial_access_assignments,initial_access_learning_materials,initial_access_information_handbook,initial_access_reading_list,initial_access_week1,initial_access_week2,main_week,std_act_week3,no_of_times_week3,initial_access_week3
0,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",1,03/10/22 - 09/10/22,0.000000,0.005278,0.014722,...,NaN,2022-10-04 15:45:00.718,NaT,NaT,2022-10-04 15:45:03.544,NaT,Week 1,NaN,NaN,NaT
1,70.0,Nigeria,1996,Male,CAH07-02\tChemistry,2,03/10/22 - 09/10/22,0.000000,3.117500,0.000000,...,NaN,2022-10-04 15:48:30.421,2022-10-04 14:02:11.582,NaT,2022-10-04 15:48:38.726,NaT,Week 1,NaN,NaN,NaT
2,65.0,Nigeria,1990,Female,CAH15-02\tEconomics,3,03/10/22 - 09/10/22,0.019722,1.710833,0.000000,...,NaN,2022-10-04 14:05:35.288,2022-10-03 21:49:58.608,2022-10-04 14:01:58.086,2022-10-04 14:05:37.424,NaT,Week 1,NaN,NaN,NaT
3,55.0,Nigeria,1991,Male,CAH15-02\tEconomics,4,03/10/22 - 09/10/22,0.001667,0.018055,0.000000,...,NaN,2022-10-03 11:15:47.910,NaT,NaT,2022-10-03 11:15:50.346,NaT,Week 1,NaN,NaN,NaT
4,65.0,Pakistan,1998,Male,CAH17-01\tBusiness and management,5,03/10/22 - 09/10/22,0.000000,2.232222,0.052778,...,NaN,2022-10-04 15:49:31.924,2022-10-05 17:49:47.691,NaT,2022-10-04 15:49:38.697,NaT,Week 1,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419,60.4,India,1992,Male,CAH19-01\tEnglish studies,208,09/10/23 - 15/10/23,0.000000,1.403888,0.000000,...,NaN,2023-10-10 14:00:37.642,NaT,NaT,2023-10-10 14:01:00.490,2023-10-10 14:00:39.370,Week 2,0.000000,0.0,NaT
420,64.0,Bangladesh,1996,Female,CAH17-01\tBusiness and management,209,09/10/23 - 15/10/23,2.835000,1.852500,0.000000,...,NaN,2023-10-09 22:38:40.351,NaT,2023-10-09 22:38:36.911,2023-10-09 19:59:06.028,2023-10-09 22:39:01.643,Week 2,0.000000,1.0,2023-10-16 01:47:34.795
421,73.0,Sri Lanka,1996,Female,CAH11-01\tComputing,210,09/10/23 - 15/10/23,0.000000,1.731112,0.000000,...,NaN,2023-10-10 14:05:59.836,NaT,NaT,2023-10-10 14:06:03.021,2023-10-10 15:37:15.039,Week 2,0.063333,2.0,2023-10-10 15:45:54.537
422,61.8,Myanmar,1998,Female,CAH11-01\tComputing,211,09/10/23 - 15/10/23,0.020000,1.141945,0.000000,...,NaN,2023-10-10 12:10:10.035,NaT,NaT,2023-10-10 12:21:11.116,2023-10-10 12:10:14.445,Week 2,0.000000,1.0,2023-10-15 16:06:25.528
423,63.0,United States of America,2001,Male,CAH11-01\tComputing,212,09/10/23 - 15/10/23,0.023055,0.080833,0.000000,...,NaN,2023-10-09 18:10:56.032,NaT,NaT,2023-10-09 18:11:00.881,2023-10-10 15:37:36.341,Week 2,0.000000,1.0,2023-10-10 15:41:36.312

In [524]:
# renaming columns with spaces and special characters
week3 = pd.read_excel(xls,'Week 3',skiprows=1)
week3.columns=week3.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
week3 =week3.iloc[:, 4:]
week3['main_week'] = 'Week 3'

In [525]:
# renaming columns with duplicate names
week3.columns.values[0] = 'total_marks'
week3.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
week3.columns.values[6]  =  'date_range'
week3.columns.values[18] = 'std_act_assignments'
week3.columns.values[19] = 'std_act_learning_materials'
week3.columns.values[20] = 'std_act_module_information_handbook'
week3.columns.values[21] = 'std_act_reading_list'
week3.columns.values[22] = 'std_act_week1'
week3.columns.values[23] = 'std_act_week2'
week3.columns.values[24] = 'std_act_week3'
week3.columns.values[25] = 'std_act_week4'
week3.columns.values[26] = 'no_of_times_accessed_assignments'
week3.columns.values[27] = 'no_of_times_accessed_learning_materials'
week3.columns.values[28] = 'no_of_times_accessed_module_information_handbook'
week3.columns.values[29] = 'no_of_times_accessed_reading_list'
week3.columns.values[30] = 'no_of_times_week1'
week3.columns.values[31] = 'no_of_times_week2'
week3.columns.values[32] = 'no_of_times_week3'
week3.columns.values[33] = 'no_of_times_week4'
week3.columns.values[34] = 'initial_access_assignments'
week3.columns.values[35] = 'initial_access_learning_materials'
week3.columns.values[36] = 'initial_access_information_handbook'
week3.columns.values[37] = 'initial_access_reading_list'
week3.columns.values[38] = 'initial_access_week1'
week3.columns.values[39] = 'initial_access_week2'
week3.columns.values[40] = 'initial_access_week3'
week3.columns.values[41] = 'initial_access_week4'
week3 = week3.copy()

In [526]:
merged_df = pd.concat([merged_df,week3],ignore_index=True,sort=False)
merged_df = merged_df.fillna('NA')
merged_df.shape

(636, 43)

In [527]:
# renaming columns with spaces and special characters
week4 = pd.read_excel(xls,'Week 4',skiprows=1)
week4.columns=week4.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
week4 = week4 =week4.iloc[:, 4:]
week4['main_week'] = 'Week 4'

In [528]:
# renaming columns with duplicate names
week4.columns.values[0] = 'total_marks'
week4.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
week4.columns.values[6]  = 'date_range'
week4.columns.values[18] = 'std_act_assignments'
week4.columns.values[19] = 'std_act_learning_materials'
week4.columns.values[20] = 'std_act_module_information_handbook'
week4.columns.values[21] = 'std_act_reading_list'
week4.columns.values[22] = 'std_act_week1'
week4.columns.values[23] = 'std_act_week2'
week4.columns.values[24] = 'std_act_week3'
week4.columns.values[25] = 'std_act_week4'
week4.columns.values[26] = 'std_act_week5'
week4.columns.values[27] = 'std_act_week6'
week4.columns.values[28] = 'std_act_week7'
week4.columns.values[29] = 'no_of_times_accessed_assignments'
week4.columns.values[30] = 'no_of_times_accessed_learning_materials'
week4.columns.values[31] = 'no_of_times_accessed_module_information_handbook'
week4.columns.values[32] = 'no_of_times_accessed_reading_list'
week4.columns.values[33] = 'no_of_times_week1'
week4.columns.values[34] = 'no_of_times_week2'
week4.columns.values[35] = 'no_of_times_week3'
week4.columns.values[36] = 'no_of_times_week4'
week4.columns.values[37] = 'no_of_times_week5'
week4.columns.values[38] = 'no_of_times_week6'
week4.columns.values[39] = 'no_of_times_week7'
week4.columns.values[40] = 'initial_access_assignments'
week4.columns.values[41] = 'initial_access_learning_materials'
week4.columns.values[42] = 'initial_access_information_handbook'
week4.columns.values[43] = 'initial_access_reading_list'
week4.columns.values[44] = 'initial_access_week1'
week4.columns.values[45] = 'initial_access_week2'
week4.columns.values[46] = 'initial_access_week3'
week4.columns.values[47] = 'initial_access_week4'
week4.columns.values[48] = 'initial_access_week5'
week4.columns.values[49] = 'initial_access_week6'
week4.columns.values[50] = 'initial_access_week7'

In [529]:
merged_df = pd.concat([merged_df, week4], ignore_index=True,sort=False)
merged_df = merged_df.fillna('NA')
merged_df.shape

(848, 52)

In [530]:
# renaming columns with spaces and special characters
df5 = pd.read_excel(xls,'Week 5',skiprows=1)
df5.columns=df5.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df5 =df5.iloc[:, 4:]
[i for i in enumerate(df5.columns)]
df5['main_week'] = 'Week 5'

In [531]:
# renaming columns with duplicate names
df5.columns.values[0] = 'total_marks'
df5.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df5.columns.values[6]  = 'date_range'
df5.columns.values[18] = 'std_act_assignments'
df5.columns.values[19] = 'std_act_learning_materials'
df5.columns.values[20] = 'std_act_module_information_handbook'
df5.columns.values[21] = 'std_act_reading_list'
df5.columns.values[22] = 'std_act_week1'
df5.columns.values[23] = 'std_act_week2'
df5.columns.values[24] = 'std_act_week3'
df5.columns.values[25] = 'std_act_week4'
df5.columns.values[26] = 'std_act_week5'
df5.columns.values[27] = 'std_act_week6'
df5.columns.values[28] = 'no_of_times_accessed_assignments'
df5.columns.values[29] = 'no_of_times_accessed_learning_materials'
df5.columns.values[30] = 'no_of_times_accessed_module_information_handbook'
df5.columns.values[31] = 'no_of_times_accessed_reading_list'
df5.columns.values[32] = 'no_of_times_week1'
df5.columns.values[33] = 'no_of_times_week2'
df5.columns.values[34] = 'no_of_times_week3'
df5.columns.values[35] = 'no_of_times_week4'
df5.columns.values[36] = 'no_of_times_week5'
df5.columns.values[37] = 'no_of_times_week6'
df5.columns.values[38] = 'initial_access_assignments'
df5.columns.values[39] = 'initial_access_learning_materials'
df5.columns.values[40] = 'initial_access_information_handbook'
df5.columns.values[41] = 'initial_access_reading_list'
df5.columns.values[42] = 'initial_access_week1'
df5.columns.values[43] = 'initial_access_week2'
df5.columns.values[44] = 'initial_access_week3'
df5.columns.values[45] = 'initial_access_week4'
df5.columns.values[46] = 'initial_access_week5'
df5.columns.values[47] = 'initial_access_week6'

In [532]:
merged_df = pd.concat([merged_df,df5],ignore_index=True,sort=False)
merged_df.fillna('NA',inplace=True)
merged_df.shape

(1060, 52)

In [533]:
# renaming columns with spaces and special characters
df6 = pd.read_excel(xls,'Week 6',skiprows=1)
df6.columns=df6.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df6 = df6.iloc[:, 4:]
df6['main_week'] = 'week 6'

In [534]:
# renaming columns with duplicate names
df6.columns.values[0] = 'total_marks'
df6.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df6.columns.values[6]  = 'date_range'
df6.columns.values[18] = 'std_act_assignments'
df6.columns.values[19] = 'std_act_learning_materials'
df6.columns.values[20] = 'std_act_module_information_handbook'
df6.columns.values[21] = 'std_act_reading_list'
df6.columns.values[22] = 'std_act_week1'
df6.columns.values[23] = 'std_act_week2'
df6.columns.values[24] = 'std_act_week3'
df6.columns.values[25] = 'std_act_week4'
df6.columns.values[26] = 'std_act_week5'
df6.columns.values[27] = 'std_act_week6'
df6.columns.values[28] = 'std_act_week7'
df6.columns.values[29] = 'no_of_times_accessed_assignments'
df6.columns.values[30] = 'no_of_times_accessed_learning_materials'
df6.columns.values[31] = 'no_of_times_accessed_module_information_handbook'
df6.columns.values[32] = 'no_of_times_accessed_reading_list'
df6.columns.values[33] = 'no_of_times_week1'
df6.columns.values[34] = 'no_of_times_week2'
df6.columns.values[35] = 'no_of_times_week3'
df6.columns.values[36] = 'no_of_times_week4'
df6.columns.values[37] = 'no_of_times_week5'
df6.columns.values[38] = 'no_of_times_week6'
df6.columns.values[39] = 'no_of_times_week7'
df6.columns.values[40] = 'initial_access_assignments'
df6.columns.values[41] = 'initial_access_learning_materials'
df6.columns.values[42] = 'initial_access_information_handbook'
df6.columns.values[43] = 'initial_access_reading_list'
df6.columns.values[44] = 'initial_access_week1'
df6.columns.values[45] = 'initial_access_week2'
df6.columns.values[46] = 'initial_access_week3'
df6.columns.values[47] = 'initial_access_week4'
df6.columns.values[48] = 'initial_access_week5'
df6.columns.values[49] = 'initial_access_week6'
df6.columns.values[50] = 'initial_access_week7'

In [535]:
merged_df = pd.concat([merged_df,df6],ignore_index=True,sort=False)
merged_df.fillna('NA', inplace=True)
merged_df.shape

(1272, 52)

In [536]:
# renaming columns with spaces and special characters
df7 = pd.read_excel(xls,'Week 7',skiprows=1)
df7.columns=df7.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df7 = df7.iloc[:, 4:]
df7['main_week'] = 'Week 7'
[i for i in enumerate(df7.columns)]

[(0, 'unnamed_4'),
 (1, 'list_of_countries'),
 (2, 'what_is_your_year_of_birth_just_the_year_eg_1995_'),
 (3, 'how_do_you_describe_yourself___selected_choice'),
 (4, 'what_is_your_first_degree_subject_area'),
 (5, 'student_id'),
 (6, 'date_range__week_7'),
 (7, 'monday'),
 (8, 'tuesday'),
 (9, 'wednesday'),
 (10, 'thursday'),
 (11, 'friday'),
 (12, 'saturday'),
 (13, 'sunday'),
 (14, 'student_time_in_course'),
 (15, 'avg_time_per_user'),
 (16, 'total_items'),
 (17, 'total_logins'),
 (18, 'assignments'),
 (19, 'learning_materials'),
 (20, 'module_information_handbook'),
 (21, 'reading_list'),
 (22, 'week_1'),
 (23, 'week_2_'),
 (24, 'week_3'),
 (25, 'week_4'),
 (26, 'week_5'),
 (27, 'week_6'),
 (28, 'week_7'),
 (29, 'week_8'),
 (30, 'assignments1'),
 (31, 'learning_materials1'),
 (32, 'module_information_handbook'),
 (33, 'reading_list1'),
 (34, 'week_11'),
 (35, 'week_2_1'),
 (36, 'week_3'),
 (37, 'week_41'),
 (38, 'week_51'),
 (39, 'week_61'),
 (40, 'week_71'),
 (41, 'week_81'),
 (42, 'assignments2'),
 (43, 'learning_materials2'),
 (44, 'module_information_handbook1'),
 (45, 'reading_list2'),
 (46, 'week_12'),
 (47, 'week_2'),
 (48, 'week_31'),
 (49, 'week_42'),
 (50, 'week_52'),
 (51, 'week_6'),
 (52, 'week_72'),
 (53, 'week_82'),
 (54, 'main_week')]

In [537]:
# renaming columns with duplicate names
df7.columns.values[0] = 'total_marks'
df7.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df7.columns.values[6]  = 'date_range'
df7.columns.values[18] = 'std_act_assignments'
df7.columns.values[19] = 'std_act_learning_materials'
df7.columns.values[20] = 'std_act_module_information_handbook'
df7.columns.values[21] = 'std_act_reading_list'
df7.columns.values[22] = 'std_act_week1'
df7.columns.values[23] = 'std_act_week2'
df7.columns.values[24] = 'std_act_week3'
df7.columns.values[25] = 'std_act_week4'
df7.columns.values[26] = 'std_act_week5'
df7.columns.values[27] = 'std_act_week6'
df7.columns.values[28] = 'std_act_week7'
df7.columns.values[29] = 'std_act_week8'
df7.columns.values[30] = 'no_of_times_accessed_assignments'
df7.columns.values[31] = 'no_of_times_accessed_learning_materials'
df7.columns.values[32] = 'no_of_times_accessed_module_information_handbook'
df7.columns.values[33] = 'no_of_times_accessed_reading_list'
df7.columns.values[34] = 'no_of_times_week1'
df7.columns.values[35] = 'no_of_times_week2'
df7.columns.values[36] = 'no_of_times_week3'
df7.columns.values[37] = 'no_of_times_week4'
df7.columns.values[38] = 'no_of_times_week5'
df7.columns.values[39] = 'no_of_times_week6'
df7.columns.values[40] = 'no_of_times_week7'
df7.columns.values[41] = 'no_of_times_week8'
df7.columns.values[42] = 'initial_access_assignments'
df7.columns.values[43] = 'initial_access_learning_materials'
df7.columns.values[44] = 'initial_access_information_handbook'
df7.columns.values[45] = 'initial_access_reading_list'
df7.columns.values[46] = 'initial_access_week1'
df7.columns.values[47] = 'initial_access_week2'
df7.columns.values[48] = 'initial_access_week3'
df7.columns.values[49] = 'initial_access_week4'
df7.columns.values[50] = 'initial_access_week5'
df7.columns.values[51] = 'initial_access_week6'
df7.columns.values[52] = 'initial_access_week7'
df7.columns.values[53] = 'initial_access_week8'

In [538]:
merged_df = pd.concat([merged_df,df7],ignore_index=True,sort=False)
merged_df.fillna('NA', inplace=True)

In [539]:
# renaming columns with spaces and special characters
df8 = pd.read_excel(xls,'Week 8',skiprows=1)
df8.columns=df8.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df8 = df8.iloc[:, 4:]
df8['main_week'] = 'Week 8'
[i for i in enumerate(df8.columns)]

[(0, 'unnamed_4'),
 (1, 'list_of_countries'),
 (2, 'what_is_your_year_of_birth_just_the_year_eg_1995_'),
 (3, 'how_do_you_describe_yourself___selected_choice'),
 (4, 'what_is_your_first_degree_subject_area'),
 (5, 'student_id'),
 (6, 'date_range__week_8'),
 (7, 'monday'),
 (8, 'tuesday'),
 (9, 'wednesday'),
 (10, 'thursday'),
 (11, 'friday'),
 (12, 'saturday'),
 (13, 'sunday'),
 (14, 'student_time_in_course'),
 (15, 'avg_time_per_user'),
 (16, 'total_items'),
 (17, 'total_logins'),
 (18, 'assignments'),
 (19, 'learning_materials'),
 (20, 'module_information_handbook'),
 (21, 'reading_list'),
 (22, 'week_1'),
 (23, 'week_2_'),
 (24, 'week_3'),
 (25, 'week_4'),
 (26, 'week_5'),
 (27, 'week_6'),
 (28, 'week_7'),
 (29, 'week_8'),
 (30, 'week_9'),
 (31, 'assignments1'),
 (32, 'learning_materials1'),
 (33, 'module_information_handbook'),
 (34, 'reading_list1'),
 (35, 'week_11'),
 (36, 'week_2'),
 (37, 'week_3_'),
 (38, 'week_41'),
 (39, 'week_51'),
 (40, 'week_61'),
 (41, 'week_71'),
 (42, 'week_81'),
 (43, 'week_91'),
 (44, 'assignments2'),
 (45, 'learning_materials2'),
 (46, 'module_information_handbook1'),
 (47, 'reading_list2'),
 (48, 'week_12'),
 (49, 'week_2_1'),
 (50, 'week_31'),
 (51, 'week_42'),
 (52, 'week_52'),
 (53, 'week_62'),
 (54, 'week_72'),
 (55, 'week_82'),
 (56, 'week_92'),
 (57, 'main_week')]

In [540]:
# renaming columns with duplicate names
df8.columns.values[0] = 'total_marks'
df8.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df8.columns.values[6]  = 'date_range'
df8.columns.values[18] = 'std_act_assignments'
df8.columns.values[19] = 'std_act_learning_materials'
df8.columns.values[20] = 'std_act_module_information_handbook'
df8.columns.values[21] = 'std_act_reading_list'
df8.columns.values[22] = 'std_act_week1'
df8.columns.values[23] = 'std_act_week2'
df8.columns.values[24] = 'std_act_week3'
df8.columns.values[25] = 'std_act_week4'
df8.columns.values[26] = 'std_act_week5'
df8.columns.values[27] = 'std_act_week6'
df8.columns.values[28] = 'std_act_week7'
df8.columns.values[29] = 'std_act_week8'
df8.columns.values[30] = 'std_act_week9'
df8.columns.values[31] = 'no_of_times_accessed_assignments'
df8.columns.values[32] = 'no_of_times_accessed_learning_materials'
df8.columns.values[33] = 'no_of_times_accessed_module_information_handbook'
df8.columns.values[34] = 'no_of_times_accessed_reading_list'
df8.columns.values[35] = 'no_of_times_week1'
df8.columns.values[36] = 'no_of_times_week2'
df8.columns.values[37] = 'no_of_times_week3'
df8.columns.values[38] = 'no_of_times_week4'
df8.columns.values[39] = 'no_of_times_week5'
df8.columns.values[40] = 'no_of_times_week6'
df8.columns.values[41] = 'no_of_times_week7'
df8.columns.values[42] = 'no_of_times_week8'
df8.columns.values[43] = 'no_of_times_week9'
df8.columns.values[44] = 'initial_access_assignments'
df8.columns.values[45] = 'initial_access_learning_materials'
df8.columns.values[46] = 'initial_access_information_handbook'
df8.columns.values[47] = 'initial_access_reading_list'
df8.columns.values[48] = 'initial_access_week1'
df8.columns.values[49] = 'initial_access_week2'
df8.columns.values[50] = 'initial_access_week3'
df8.columns.values[51] = 'initial_access_week4'
df8.columns.values[52] = 'initial_access_week5'
df8.columns.values[53] = 'initial_access_week6'
df8.columns.values[54] = 'initial_access_week7'
df8.columns.values[55] = 'initial_access_week8'
df8.columns.values[56] = 'initial_access_week9'

In [541]:
merged_df = pd.concat([merged_df,df8],ignore_index=True,sort=False)
merged_df.fillna('NA', inplace=True)
merged_df

,total_marks,list_of_countries,what_is_your_year_of_birth_just_the_year,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range,monday,tuesday,wednesday,...,no_of_times_week7,initial_access_week5,initial_access_week6,initial_access_week7,std_act_week8,no_of_times_week8,initial_access_week8,std_act_week9,no_of_times_week9,initial_access_week9
0,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",1,03/10/22 - 09/10/22,0.000000,0.005278,0.014722,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
1,70.0,Nigeria,1996,Male,CAH07-02\tChemistry,2,03/10/22 - 09/10/22,0.000000,3.117500,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
2,65.0,Nigeria,1990,Female,CAH15-02\tEconomics,3,03/10/22 - 09/10/22,0.019722,1.710833,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
3,55.0,Nigeria,1991,Male,CAH15-02\tEconomics,4,03/10/22 - 09/10/22,0.001667,0.018055,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
4,65.0,Pakistan,1998,Male,CAH17-01\tBusiness and management,5,03/10/22 - 09/10/22,0.000000,2.232222,0.052778,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1691,60.4,India,1992,Male,CAH19-01\tEnglish studies,208,20/11/23 - 26/11/23,0.000000,0.141667,0.000000,...,1,NA,NA,2023-11-21 14:27:32.190000,0.0,1,2023-11-21 14:28:14.708000,0.0,0.0,NA
1692,64.0,Bangladesh,1996,Female,CAH17-01\tBusiness and management,209,20/11/23 - 26/11/23,0.193888,0.178612,0.000000,...,0,NA,NA,NA,0.0,1,2023-11-21 14:27:40.827000,0.0,0.0,NA
1693,73.0,Sri Lanka,1996,Female,CAH11-01\tComputing,210,20/11/23 - 26/11/23,0.000000,2.178333,0.823612,...,0,NA,NA,NA,1.815555,2,2023-11-21 13:52:08.504000,0.0,0.0,NA
1694,61.8,Myanmar,1998,Female,CAH11-01\tComputing,211,20/11/23 - 26/11/23,2.264443,0.100555,0.000000,...,3,NA,NA,2023-11-20 03:08:19.424000,0.003888,2,2023-11-21 00:37:39.742000,0.0,0.0,NA
1695,63.0,United States of America,2001,Male,CAH11-01\tComputing,212,20/11/23 - 26/11/23,0.000000,0.014167,0.000000,...,0,NA,NA,NA,0.0,1,2023-11-21 14:19:26.822000,0.0,0.0,NA

In [542]:
# renaming columns with spaces and special characters
df9 = pd.read_excel(xls,'Week 9',skiprows=1)
df9.columns=df9.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df9 = df9.iloc[:, 4:]
df9['main_week'] = 'Week 9'

In [543]:
# renaming columns with duplicate names
df9.columns.values[0] = 'total_marks'
df9.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df9.columns.values[6]  = 'date_range'
df9.columns.values[18] = 'std_act_assignments'
df9.columns.values[19] = 'std_act_learning_materials'
df9.columns.values[20] = 'std_act_module_information_handbook'
df9.columns.values[21] = 'std_act_reading_list'
df9.columns.values[22] = 'std_act_week1'
df9.columns.values[23] = 'std_act_week2'
df9.columns.values[24] = 'std_act_week3'
df9.columns.values[25] = 'std_act_week4'
df9.columns.values[26] = 'std_act_week5'
df9.columns.values[27] = 'std_act_week6'
df9.columns.values[28] = 'std_act_week7'
df9.columns.values[29] = 'std_act_week8'
df9.columns.values[30] = 'std_act_week9'
df9.columns.values[31] = 'std_act_week10'
df9.columns.values[32] = 'no_of_times_accessed_assignments'
df9.columns.values[33] = 'no_of_times_accessed_learning_materials'
df9.columns.values[34] = 'no_of_times_accessed_module_information_handbook'
df9.columns.values[35] = 'no_of_times_accessed_reading_list'
df9.columns.values[36] = 'no_of_times_week1'
df9.columns.values[37] = 'no_of_times_week2'
df9.columns.values[38] = 'no_of_times_week3'
df9.columns.values[39] = 'no_of_times_week4'
df9.columns.values[40] = 'no_of_times_week5'
df9.columns.values[41] = 'no_of_times_week6'
df9.columns.values[42] = 'no_of_times_week7'
df9.columns.values[43] = 'no_of_times_week8'
df9.columns.values[44] = 'no_of_times_week9'
df9.columns.values[45] = 'no_of_times_week10'
df9.columns.values[46] = 'initial_access_assignments'
df9.columns.values[47] = 'initial_access_learning_materials'
df9.columns.values[48] = 'initial_access_information_handbook'
df9.columns.values[49] = 'initial_access_reading_list'
df9.columns.values[50] = 'initial_access_week1'
df9.columns.values[51] = 'initial_access_week2'
df9.columns.values[52] = 'initial_access_week3'
df9.columns.values[53] = 'initial_access_week4'
df9.columns.values[54] = 'initial_access_week5'
df9.columns.values[55] = 'initial_access_week6'
df9.columns.values[56] = 'initial_access_week7'
df9.columns.values[57] = 'initial_access_week8'
df9.columns.values[58] = 'initial_access_week9'
df9.columns.values[59] = 'initial_access_week10'

In [544]:
merged_df = pd.concat([merged_df,df9],ignore_index=True,sort=False)
merged_df.fillna('NA', inplace=True)
merged_df

,total_marks,list_of_countries,what_is_your_year_of_birth_just_the_year,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range,monday,tuesday,wednesday,...,initial_access_week7,std_act_week8,no_of_times_week8,initial_access_week8,std_act_week9,no_of_times_week9,initial_access_week9,std_act_week10,no_of_times_week10,initial_access_week10
0,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",1,03/10/22 - 09/10/22,0.000000,0.005278,0.014722,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
1,70.0,Nigeria,1996,Male,CAH07-02\tChemistry,2,03/10/22 - 09/10/22,0.000000,3.117500,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
2,65.0,Nigeria,1990,Female,CAH15-02\tEconomics,3,03/10/22 - 09/10/22,0.019722,1.710833,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
3,55.0,Nigeria,1991,Male,CAH15-02\tEconomics,4,03/10/22 - 09/10/22,0.001667,0.018055,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
4,65.0,Pakistan,1998,Male,CAH17-01\tBusiness and management,5,03/10/22 - 09/10/22,0.000000,2.232222,0.052778,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1903,60.4,India,1992,Male,CAH19-01\tEnglish studies,208,27/11/23 - 03/12/23,0.000000,0.000000,0.185833,...,NA,0.0,0,NA,0.0,0,NA,0.0,0.0,NA
1904,64.0,Bangladesh,1996,Female,CAH17-01\tBusiness and management,209,27/11/23 - 03/12/23,0.000000,0.179722,0.000000,...,NA,0.0,0,NA,0.091112,1,2023-11-28 14:24:39.901000,0.0,0.0,NA
1905,73.0,Sri Lanka,1996,Female,CAH11-01\tComputing,210,27/11/23 - 03/12/23,0.000000,0.592778,0.005833,...,NA,0.0,0,NA,0.004443,4,2023-11-28 11:46:23.507000,0.0,0.0,NA
1906,61.8,Myanmar,1998,Female,CAH11-01\tComputing,211,27/11/23 - 03/12/23,2.553333,0.003612,0.000000,...,NA,0.0,0,NA,0.012778,4,2023-11-27 11:22:05.677000,0.0,0.0,NA
1907,63.0,United States of America,2001,Male,CAH11-01\tComputing,212,27/11/23 - 03/12/23,0.000000,0.001667,0.000000,...,NA,0.0,0,NA,0.0,0,NA,0.0,0.0,NA

In [545]:
# renaming columns with spaces and special characters
df10 = pd.read_excel(xls,'Week 10',skiprows=1)
df10.columns=df10.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df10 = df10.iloc[:, 4:]
df10['main_week'] = 'Week 10'
[i for i in enumerate(df10.columns)]

[(0, 'unnamed_4'),
 (1, 'list_of_countries'),
 (2, 'what_is_your_year_of_birth_just_the_year_eg_1995_'),
 (3, 'how_do_you_describe_yourself___selected_choice'),
 (4, 'what_is_your_first_degree_subject_area'),
 (5, 'student_id'),
 (6, 'date_range__week_10'),
 (7, 'monday'),
 (8, 'tuesday'),
 (9, 'wednesday'),
 (10, 'thursday'),
 (11, 'friday'),
 (12, 'saturday'),
 (13, 'sunday'),
 (14, 'student_time_in_course'),
 (15, 'avg_time_per_user'),
 (16, 'total_items'),
 (17, 'total_logins'),
 (18, 'assignments'),
 (19, 'learning_materials'),
 (20, 'module_information_handbook'),
 (21, 'reading_list'),
 (22, 'week_1'),
 (23, 'week_2'),
 (24, 'week_3_'),
 (25, 'week_4'),
 (26, 'week_5'),
 (27, 'week_6'),
 (28, 'week_7'),
 (29, 'week_8'),
 (30, 'week_9'),
 (31, 'week_10'),
 (32, 'assignments1'),
 (33, 'learning_materials1'),
 (34, 'module_information_handbook'),
 (35, 'reading_list1'),
 (36, 'week_11'),
 (37, 'week_21'),
 (38, 'week_3_'),
 (39, 'week_41'),
 (40, 'week_51'),
 (41, 'week_61'),
 (42, 'week_71'),
 (43, 'week_81'),
 (44, 'week_91'),
 (45, 'week_101'),
 (46, 'assignments2'),
 (47, 'learning_materials2'),
 (48, 'module_information_handbook1'),
 (49, 'reading_list2'),
 (50, 'week_12'),
 (51, 'week_2_'),
 (52, 'week_3_1'),
 (53, 'week_42'),
 (54, 'week_52'),
 (55, 'week_62'),
 (56, 'week_72'),
 (57, 'week_82'),
 (58, 'week_92'),
 (59, 'week_102'),
 (60, 'main_week')]

In [546]:
# renaming columns with duplicate names
df10.columns.values[0] = 'total_marks'
df10.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df10.columns.values[6]  = 'date_range'
df10.columns.values[18] = 'std_act_assignments'
df10.columns.values[19] = 'std_act_learning_materials'
df10.columns.values[20] = 'std_act_module_information_handbook'
df10.columns.values[21] = 'std_act_reading_list'
df10.columns.values[22] = 'std_act_week1'
df10.columns.values[23] = 'std_act_week2'
df10.columns.values[24] = 'std_act_week3'
df10.columns.values[25] = 'std_act_week4'
df10.columns.values[26] = 'std_act_week5'
df10.columns.values[27] = 'std_act_week6'
df10.columns.values[28] = 'std_act_week7'
df10.columns.values[29] = 'std_act_week8'
df10.columns.values[30] = 'std_act_week9'
df10.columns.values[31] = 'std_act_week10'
df10.columns.values[32] = 'no_of_times_accessed_assignments'
df10.columns.values[33] = 'no_of_times_accessed_learning_materials'
df10.columns.values[34] = 'no_of_times_accessed_module_information_handbook'
df10.columns.values[35] = 'no_of_times_accessed_reading_list'
df10.columns.values[36] = 'no_of_times_week1'
df10.columns.values[37] = 'no_of_times_week2'
df10.columns.values[38] = 'no_of_times_week3'
df10.columns.values[39] = 'no_of_times_week4'
df10.columns.values[40] = 'no_of_times_week5'
df10.columns.values[41] = 'no_of_times_week6'
df10.columns.values[42] = 'no_of_times_week7'
df10.columns.values[43] = 'no_of_times_week8'
df10.columns.values[44] = 'no_of_times_week9'
df10.columns.values[45] = 'no_of_times_week10'
df10.columns.values[46] = 'initial_access_assignments'
df10.columns.values[47] = 'initial_access_learning_materials'
df10.columns.values[48] = 'initial_access_information_handbook'
df10.columns.values[49] = 'initial_access_reading_list'
df10.columns.values[50] = 'initial_access_week1'
df10.columns.values[51] = 'initial_access_week2'
df10.columns.values[52] = 'initial_access_week3'
df10.columns.values[53] = 'initial_access_week4'
df10.columns.values[54] = 'initial_access_week5'
df10.columns.values[55] = 'initial_access_week6'
df10.columns.values[56] = 'initial_access_week7'
df10.columns.values[57] = 'initial_access_week8'
df10.columns.values[58] = 'initial_access_week9'
df10.columns.values[59] = 'initial_access_week10'

In [547]:
merged_df = pd.concat([merged_df,df10],ignore_index=True,sort=False)
merged_df.fillna('NA', inplace=True)
merged_df

,total_marks,list_of_countries,what_is_your_year_of_birth_just_the_year,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range,monday,tuesday,wednesday,...,initial_access_week7,std_act_week8,no_of_times_week8,initial_access_week8,std_act_week9,no_of_times_week9,initial_access_week9,std_act_week10,no_of_times_week10,initial_access_week10
0,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",1,03/10/22 - 09/10/22,0.000000,0.005278,0.014722,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
1,70.0,Nigeria,1996,Male,CAH07-02\tChemistry,2,03/10/22 - 09/10/22,0.000000,3.117500,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
2,65.0,Nigeria,1990,Female,CAH15-02\tEconomics,3,03/10/22 - 09/10/22,0.019722,1.710833,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
3,55.0,Nigeria,1991,Male,CAH15-02\tEconomics,4,03/10/22 - 09/10/22,0.001667,0.018055,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
4,65.0,Pakistan,1998,Male,CAH17-01\tBusiness and management,5,03/10/22 - 09/10/22,0.000000,2.232222,0.052778,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2115,60.4,India,1992,Male,CAH19-01\tEnglish studies,208,04/12/23 - 10/12/23,0.108333,0.098888,0.000000,...,NA,0.0,0,NA,0.0,0,NA,0.0,0,NA
2116,64.0,Bangladesh,1996,Female,CAH17-01\tBusiness and management,209,04/12/23 - 10/12/23,0.008333,0.006388,0.000000,...,NA,0.0,0,NA,0.0,0,NA,0.0,0,NA
2117,73.0,Sri Lanka,1996,Female,CAH11-01\tComputing,210,04/12/23 - 10/12/23,3.331112,1.504722,0.008888,...,NA,0.0,0,NA,0.0,0,NA,0.0,1,2023-12-05 12:35:03.715000
2118,61.8,Myanmar,1998,Female,CAH11-01\tComputing,211,04/12/23 - 10/12/23,0.000000,0.583055,0.463055,...,NA,0.0,0,NA,0.0,0,NA,0.0,2,2023-12-05 12:32:54.983000
2119,63.0,United States of America,2001,Male,CAH11-01\tComputing,212,04/12/23 - 10/12/23,0.000000,0.000000,0.000000,...,NA,0.0,0,NA,0.0,0,NA,0.0,0,NA

In [548]:
# renaming columns with spaces and special characters
df11 = pd.read_excel(xls,'Week 11',skiprows=1)
df11.columns=df11.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df11 = df11.iloc[:, 4:]
df11['main_week'] = 'week 11'
[i for i in enumerate(df11.columns)]

[(0, 'unnamed_4'),
 (1, 'list_of_countries'),
 (2, 'what_is_your_year_of_birth_just_the_year_eg_1995_'),
 (3, 'how_do_you_describe_yourself___selected_choice'),
 (4, 'what_is_your_first_degree_subject_area'),
 (5, 'student_id'),
 (6, 'date_range__week_11'),
 (7, 'monday'),
 (8, 'tuesday'),
 (9, 'wednesday'),
 (10, 'thursday'),
 (11, 'friday'),
 (12, 'saturday'),
 (13, 'sunday'),
 (14, 'student_time_in_course'),
 (15, 'avg_time_per_user'),
 (16, 'total_items'),
 (17, 'total_logins'),
 (18, 'assignments'),
 (19, 'learning_materials'),
 (20, 'module_information_handbook'),
 (21, 'reading_list'),
 (22, 'week_1'),
 (23, 'week_2_'),
 (24, 'week_3_'),
 (25, 'week_4'),
 (26, 'week_5'),
 (27, 'week_6'),
 (28, 'week_7'),
 (29, 'week_8'),
 (30, 'week_9'),
 (31, 'week_10'),
 (32, 'week_11feedback'),
 (33, 'assignments1'),
 (34, 'learning_materials1'),
 (35, 'module_information_handbook'),
 (36, 'reading_list1'),
 (37, 'week_11'),
 (38, 'week_2_1'),
 (39, 'week_3_'),
 (40, 'week_41'),
 (41, 'week_51'),
 (42, 'week_61'),
 (43, 'week_71'),
 (44, 'week_81'),
 (45, 'week_91'),
 (46, 'week_101'),
 (47, 'week_11feedback1'),
 (48, 'assignments2'),
 (49, 'learning_materials2'),
 (50, 'module_information_handbook1'),
 (51, 'reading_list2'),
 (52, 'week_12'),
 (53, 'week_2_2'),
 (54, 'week_3'),
 (55, 'week_42'),
 (56, 'week_52'),
 (57, 'week_62'),
 (58, 'week_72'),
 (59, 'week_82'),
 (60, 'week_92'),
 (61, 'week_102'),
 (62, 'week_11feedback2'),
 (63, 'main_week')]

In [549]:
# renaming columns with duplicate names
df11.columns.values[0] = 'total_marks'
df11.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df11.columns.values[6]  = 'date_range'
df11.columns.values[18] = 'std_act_assignments'
df11.columns.values[19] = 'std_act_learning_materials'
df11.columns.values[20] = 'std_act_module_information_handbook'
df11.columns.values[21] = 'std_act_reading_list'
df11.columns.values[22] = 'std_act_week1'
df11.columns.values[23] = 'std_act_week2'
df11.columns.values[24] = 'std_act_week3'
df11.columns.values[25] = 'std_act_week4'
df11.columns.values[26] = 'std_act_week5'
df11.columns.values[27] = 'std_act_week6'
df11.columns.values[28] = 'std_act_week7'
df11.columns.values[29] = 'std_act_week8'
df11.columns.values[30] = 'std_act_week9'
df11.columns.values[31] = 'std_act_week10'
df11.columns.values[32] = 'std_act_week_11_feedback'
df11.columns.values[33] = 'no_of_times_accessed_assignments'
df11.columns.values[34] = 'no_of_times_accessed_learning_materials'
df11.columns.values[35] = 'no_of_times_accessed_module_information_handbook'
df11.columns.values[36] = 'no_of_times_accessed_reading_list'
df11.columns.values[37] = 'no_of_times_week1'
df11.columns.values[38] = 'no_of_times_week2'
df11.columns.values[39] = 'no_of_times_week3'
df11.columns.values[40] = 'no_of_times_week4'
df11.columns.values[41] = 'no_of_times_week5'
df11.columns.values[42] = 'no_of_times_week6'
df11.columns.values[43] = 'no_of_times_week7'
df11.columns.values[44] = 'no_of_times_week8'
df11.columns.values[45] = 'no_of_times_week9'
df11.columns.values[46] = 'no_of_times_week10'
df11.columns.values[47] = 'no_of_times_week11_feedback'
df11.columns.values[48] = 'initial_access_assignments'
df11.columns.values[49] = 'initial_access_learning_materials'
df11.columns.values[50] = 'initial_access_information_handbook'
df11.columns.values[51] = 'initial_access_reading_list'
df11.columns.values[52] = 'initial_access_week1'
df11.columns.values[53] = 'initial_access_week2'
df11.columns.values[54] = 'initial_access_week3'
df11.columns.values[55] = 'initial_access_week4'
df11.columns.values[56] = 'initial_access_week5'
df11.columns.values[57] = 'initial_access_week6'
df11.columns.values[58] = 'initial_access_week7'
df11.columns.values[59] = 'initial_access_week8'
df11.columns.values[60] = 'initial_access_week9'
df11.columns.values[61] = 'initial_access_week10'
df11.columns.values[62] = 'initial_access_week11_feedback'

In [550]:
merged_df = pd.concat([merged_df,df11],ignore_index=True,sort=False)
merged_df.fillna('NA', inplace=True)
merged_df

,total_marks,list_of_countries,what_is_your_year_of_birth_just_the_year,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range,monday,tuesday,wednesday,...,initial_access_week8,std_act_week9,no_of_times_week9,initial_access_week9,std_act_week10,no_of_times_week10,initial_access_week10,std_act_week_11_feedback,no_of_times_week11_feedback,initial_access_week11_feedback
0,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",1,03/10/22 - 09/10/22,0.000000,0.005278,0.014722,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
1,70.0,Nigeria,1996,Male,CAH07-02\tChemistry,2,03/10/22 - 09/10/22,0.000000,3.117500,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
2,65.0,Nigeria,1990,Female,CAH15-02\tEconomics,3,03/10/22 - 09/10/22,0.019722,1.710833,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
3,55.0,Nigeria,1991,Male,CAH15-02\tEconomics,4,03/10/22 - 09/10/22,0.001667,0.018055,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
4,65.0,Pakistan,1998,Male,CAH17-01\tBusiness and management,5,03/10/22 - 09/10/22,0.000000,2.232222,0.052778,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2327,60.4,India,1992,Male,CAH19-01\tEnglish studies,208,11/12/23 - 17/12/23,0.000000,0.000000,0.301667,...,NA,0.0,0,NA,0.0,0,NA,0.0,0.0,NA
2328,64.0,Bangladesh,1996,Female,CAH17-01\tBusiness and management,209,11/12/23 - 17/12/23,0.000000,0.017778,0.022778,...,NA,0.0,0,NA,0.0,0,NA,0.013612,1.0,2023-12-12 14:30:47.321000
2329,73.0,Sri Lanka,1996,Female,CAH11-01\tComputing,210,11/12/23 - 17/12/23,3.059722,2.752778,0.000000,...,NA,0.0,0,NA,0.0,0,NA,0.014445,1.0,2023-12-12 14:16:13.475000
2330,61.8,Myanmar,1998,Female,CAH11-01\tComputing,211,11/12/23 - 17/12/23,0.016667,0.113888,0.000000,...,NA,0.0,0,NA,0.0,0,NA,0.008888,4.0,2023-12-11 20:07:31.608000
2331,63.0,United States of America,2001,Male,CAH11-01\tComputing,212,11/12/23 - 17/12/23,0.000000,1.459445,0.000000,...,NA,0.0,0,NA,0.0,0,NA,0.251388,1.0,2023-12-12 14:17:38.059000

In [551]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2332 entries, 0 to 2331
Data columns (total 64 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   total_marks                                       2332 non-null   float64
 1   list_of_countries                                 2332 non-null   object
 2   what_is_your_year_of_birth_just_the_year          2332 non-null   int64
 3   how_do_you_describe_yourself___selected_choice    2332 non-null   object
 4   what_is_your_first_degree_subject_area            2332 non-null   object
 5   student_id                                        2332 non-null   int64
 6   date_range                                        2332 non-null   object
 7   monday                                            2332 non-null   float64
 8   tuesday                                           2332 non-null   float64
 9   wednesday                                         2332 non-null   float64
 10  thursday                                          2332 non-null   float64
 11  friday                                            2332 non-null   float64
 12  saturday                                          2332 non-null   float64
 13  sunday                                            2332 non-null   float64
 14  student_time_in_course                            2332 non-null   object
 15  avg_time_per_user                                 2332 non-null   object
 16  total_items                                       2332 non-null   int64
 17  total_logins                                      2332 non-null   int64
 18  std_act_assignments                               2332 non-null   float64
 19  std_act_learning_materials                        2332 non-null   float64
 20  std_act_module_information_handbook               2332 non-null   float64
 21  std_act_reading_list                              2332 non-null   float64
 22  std_act_week1                                     2332 non-null   float64
 23  std_act_week2                                     2332 non-null   float64
 24  no_of_times_accessed_assignments                  2332 non-null   int64
 25  no_of_times_accessed_learning_materials           2332 non-null   int64
 26  no_of_times_accessed_module_information_handbook  2332 non-null   int64
 27  no_of_times_accessed_reading_list                 2332 non-null   int64
 28  no_of_times_week1                                 2332 non-null   int64
 29  no_of_times_week2                                 2332 non-null   int64
 30  initial_access_assignments                        2332 non-null   object
 31  initial_access_learning_materials                 2332 non-null   object
 32  initial_access_information_handbook               2332 non-null   object
 33  initial_access_reading_list                       2332 non-null   object
 34  initial_access_week1                              2332 non-null   object
 35  initial_access_week2                              2332 non-null   object
 36  main_week                                         2332 non-null   object
 37  std_act_week3                                     2332 non-null   object
 38  no_of_times_week3                                 2332 non-null   object
 39  initial_access_week3                              2332 non-null   object
 40  std_act_week4                                     2332 non-null   object
 41  no_of_times_week4                                 2332 non-null   object
 42  initial_access_week4                              2332 non-null   object
 43  std_act_week5                                     2332 non-null   object
 44  std_act_week6                                     2332 non-null   object
 45  std_act_week7                                     2332 non-null   object
 46  no_of_times_week5                                 2332 non-null   object
 47  no_of_times_week6                                 2332 non-null   object
 48  no_of_times_week7                                 2332 non-null   object
 49  initial_access_week5                              2332 non-null   object
 50  initial_access_week6                              2332 non-null   object
 51  initial_access_week7                              2332 non-null   object
 52  std_act_week8                                     2332 non-null   object
 53  no_of_times_week8                                 2332 non-null   object
 54  initial_access_week8                              2332 non-null   object
 55  std_act_week9                                     2332 non-null   object
 56  no_of_times_week9                                 2332 non-null   object
 57  initial_access_week9                              2332 non-null   object
 58  std_act_week10                                    2332 non-null   object
 59  no_of_times_week10                                2332 non-null   object
 60  initial_access_week10                             2332 non-null   object
 61  std_act_week_11_feedback                          2332 non-null   object
 62  no_of_times_week11_feedback                       2332 non-null   object
 63  initial_access_week11_feedback                    2332 non-null   object
dtypes: float64(14), int64(10), object(40)
memory usage: 1.1+ MB

In [552]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2332 entries, 0 to 2331
Data columns (total 64 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   total_marks                                       2332 non-null   float64
 1   list_of_countries                                 2332 non-null   object
 2   what_is_your_year_of_birth_just_the_year          2332 non-null   int64
 3   how_do_you_describe_yourself___selected_choice    2332 non-null   object
 4   what_is_your_first_degree_subject_area            2332 non-null   object
 5   student_id                                        2332 non-null   int64
 6   date_range                                        2332 non-null   object
 7   monday                                            2332 non-null   float64
 8   tuesday                                           2332 non-null   float64
 9   wednesday                                         2332 non-null   float64
 10  thursday                                          2332 non-null   float64
 11  friday                                            2332 non-null   float64
 12  saturday                                          2332 non-null   float64
 13  sunday                                            2332 non-null   float64
 14  student_time_in_course                            2332 non-null   object
 15  avg_time_per_user                                 2332 non-null   object
 16  total_items                                       2332 non-null   int64
 17  total_logins                                      2332 non-null   int64
 18  std_act_assignments                               2332 non-null   float64
 19  std_act_learning_materials                        2332 non-null   float64
 20  std_act_module_information_handbook               2332 non-null   float64
 21  std_act_reading_list                              2332 non-null   float64
 22  std_act_week1                                     2332 non-null   float64
 23  std_act_week2                                     2332 non-null   float64
 24  no_of_times_accessed_assignments                  2332 non-null   int64
 25  no_of_times_accessed_learning_materials           2332 non-null   int64
 26  no_of_times_accessed_module_information_handbook  2332 non-null   int64
 27  no_of_times_accessed_reading_list                 2332 non-null   int64
 28  no_of_times_week1                                 2332 non-null   int64
 29  no_of_times_week2                                 2332 non-null   int64
 30  initial_access_assignments                        2332 non-null   object
 31  initial_access_learning_materials                 2332 non-null   object
 32  initial_access_information_handbook               2332 non-null   object
 33  initial_access_reading_list                       2332 non-null   object
 34  initial_access_week1                              2332 non-null   object
 35  initial_access_week2                              2332 non-null   object
 36  main_week                                         2332 non-null   object
 37  std_act_week3                                     2332 non-null   object
 38  no_of_times_week3                                 2332 non-null   object
 39  initial_access_week3                              2332 non-null   object
 40  std_act_week4                                     2332 non-null   object
 41  no_of_times_week4                                 2332 non-null   object
 42  initial_access_week4                              2332 non-null   object
 43  std_act_week5                                     2332 non-null   object
 44  std_act_week6                                     2332 non-null   object
 45  std_act_week7                                     2332 non-null   object
 46  no_of_times_week5                                 2332 non-null   object
 47  no_of_times_week6                                 2332 non-null   object
 48  no_of_times_week7                                 2332 non-null   object
 49  initial_access_week5                              2332 non-null   object
 50  initial_access_week6                              2332 non-null   object
 51  initial_access_week7                              2332 non-null   object
 52  std_act_week8                                     2332 non-null   object
 53  no_of_times_week8                                 2332 non-null   object
 54  initial_access_week8                              2332 non-null   object
 55  std_act_week9                                     2332 non-null   object
 56  no_of_times_week9                                 2332 non-null   object
 57  initial_access_week9                              2332 non-null   object
 58  std_act_week10                                    2332 non-null   object
 59  no_of_times_week10                                2332 non-null   object
 60  initial_access_week10                             2332 non-null   object
 61  std_act_week_11_feedback                          2332 non-null   object
 62  no_of_times_week11_feedback                       2332 non-null   object
 63  initial_access_week11_feedback                    2332 non-null   object
dtypes: float64(14), int64(10), object(40)
memory usage: 1.1+ MB

In [553]:
merged_df.fillna('NA', inplace=True)

In [554]:
def time_to_hours(time_str):
    try:
        h, m, s = map(int, time_str.split(':'))
        return round(h*3600 + m * 60 + s,1)
    except:
        return 0

In [555]:
merged_df['student_time_in_course_total_hrs'] = merged_df['student_time_in_course'].apply(time_to_hours)
merged_df['avg_total_time'] = merged_df['avg_time_per_user'].apply(time_to_hours)

In [556]:
merged_df['student_time_in_course_total_hrs']

0         157
1       11223
2        6230
3          71
4        8226
        ...
2327     1130
2328      146
2329    20925
2330      476
2331     5254
Name: student_time_in_course_total_hrs, Length: 2332, dtype: int64

In [557]:
# cols = ['total_marks','monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday',
#        'sunday', 'student_time_in_course', 'avg_time_per_user', 'total_items',
#        'total_logins', 'std_act_assignments', 'std_act_learning_materials',
#        'std_act_module_information_handbook', 'std_act_reading_list',
#        'std_act_week1', 'std_act_week2', 'no_of_times_accessed_assignments',
#        'no_of_times_accessed_learning_materials',
#        'no_of_times_accessed_module_information_handbook',
#        'no_of_times_accessed_reading_list', 'no_of_times_week1',
#        'no_of_times_week2',
#        'std_act_week3', 'no_of_times_week3',
#        'no_of_times_week4',
#        'std_act_week4', 'std_act_week5', 'std_act_week6', 'std_act_week7',
#        'no_of_times_week5', 'no_of_times_week6', 'no_of_times_week7',
#        'std_act_week8', 'no_of_times_week8','std_act_week9', 'no_of_times_week9',
#        'std_act_week10', 'no_of_times_week10',
#        'std_act_week_11_feedback', 'no_of_times_week11_feedback',
#        'student_time_in_course_total_hrs']
# df = merged_df

In [558]:
merged_df.to_csv('merged_df2.csv', index=False)

In [559]:
merged_df.drop(columns=[ 'list_of_countries','what_is_your_year_of_birth_just_the_year',
            'how_do_you_describe_yourself___selected_choice','what_is_your_first_degree_subject_area'
            ]).drop_duplicates().reset_index(drop=True).to_csv('merged_weeks.csv', index=False)

In [560]:
merged_df[['student_id', 'total_marks', 'list_of_countries','what_is_your_year_of_birth_just_the_year',
            'how_do_you_describe_yourself___selected_choice','what_is_your_first_degree_subject_area'
            ]].drop_duplicates().reset_index(drop=True).to_csv('students_info.csv', index=False)

In [561]:
merged_df[['total_marks', 'list_of_countries',
       'what_is_your_year_of_birth_just_the_year',
       'how_do_you_describe_yourself___selected_choice',
       'what_is_your_first_degree_subject_area', 'student_id', 'date_range',
       'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday',
       'sunday', 'student_time_in_course', 'avg_time_per_user', 'total_items',
       'total_logins', 'std_act_assignments', 'std_act_learning_materials',
       'std_act_module_information_handbook', 'std_act_reading_list',
       'std_act_week1', 'std_act_week2', 'no_of_times_accessed_assignments',
       'no_of_times_accessed_learning_materials',
       'no_of_times_accessed_module_information_handbook',
       'no_of_times_accessed_reading_list', 'no_of_times_week1',
       'no_of_times_week2', 'initial_access_assignments',
       'initial_access_learning_materials',
       'initial_access_information_handbook', 'initial_access_reading_list',
       'initial_access_week1', 'initial_access_week2', 'main_week',
       'std_act_week3', 'no_of_times_week3', 'initial_access_week3',
       'std_act_week4', 'no_of_times_week4', 'initial_access_week4',
       'std_act_week5', 'std_act_week6', 'std_act_week7', 'no_of_times_week5',
       'no_of_times_week6', 'no_of_times_week7', 'initial_access_week5',
       'initial_access_week6', 'initial_access_week7', 'std_act_week8',
       'no_of_times_week8', 'initial_access_week8', 'std_act_week9',
       'no_of_times_week9', 'initial_access_week9', 'std_act_week10',
       'no_of_times_week10', 'initial_access_week10',
       'std_act_week_11_feedback', 'no_of_times_week11_feedback',
       'initial_access_week11_feedback']].drop_duplicates().reset_index(drop=True).to_csv('new.csv', index=False)

In [562]:
df['total_weeks'] = df['monday']+df['tuesday']+df['wednesday']+df['thursday']+df['friday']+df['saturday']+df['sunday']
df['total_weeks'] = df['total_weeks'].fillna(0)
df['total_weeks'] = df['total_weeks'].astype(float) 
df['std_activity_total'] = df['std_act_assignments']+df['std_act_learning_materials']+df['std_act_module_information_handbook']+df['std_act_reading_list']+df['std_act_week1']+df['std_act_week2']+df['std_act_week3']+df['std_act_week4']+df['std_act_week5']+df['std_act_week6']+df['std_act_week7']+df['std_act_week8']+df['std_act_week9']+df['std_act_week10']
df['std_activity_total'] = df['std_activity_total'].fillna(0)
df['std_activity_total'] = df['std_activity_total'].astype(float)
df['no_of_times_accessed_total'] = df['no_of_times_accessed_assignments']+df['no_of_times_accessed_learning_materials']+df['no_of_times_accessed_module_information_handbook']+df['no_of_times_accessed_reading_list']+df['no_of_times_week1']+df['no_of_times_week2']+df['no_of_times_week3']+df['no_of_times_week4']+df['no_of_times_week5']+df['no_of_times_week6']+df['no_of_times_week7']+df['no_of_times_week8']+df['no_of_times_week9']+df['no_of_times_week10']
df['no_of_times_accessed_total'] = df['no_of_times_accessed_total'].fillna(0)
df['no_of_times_accessed_total'] = df['no_of_times_accessed_total'].astype(float)
df['student_time_in_course_total_hrs'] = df['student_time_in_course_total_hrs'].fillna(0)
df['student_time_in_course_total_hrs'] = df['student_time_in_course_total_hrs'].astype(float)

NameError: name 'df' is not defined