In [2]:
#importing libraries
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as matplot
import re
import logging
import os
import warnings
warnings.filterwarnings("ignore")

In [3]:
#reading excel with multiple sheets and selecting a specific sheet
xls = pd.ExcelFile('csv_data/data1.xlsx')
demo_week_2 = pd.read_excel(xls,'Demographics',skiprows=1)
demo_week_2 = demo_week_2.iloc[:,1:]

In [4]:
#reading excel with multiple sheets and selecting a specific sheet
demo_week_2_numeric = pd.read_excel(xls,'Numeric Demographic',skiprows=1)

In [5]:
#reading excel with multiple sheets and selecting a specific sheet
Retro_numeric = pd.read_excel(xls,'Retro numeric',skiprows=1)
Retro_numeric

,"Please enter your student ID\n\nWe will use this to connect your data together, but will not share it or use it to identify you personally beyond the end of the study",Please reflect on your team's performance in the module - I really enjoyed working in the team,Please reflect on your team's performance in the module - Team communication was highly effective,Please reflect on your team's performance in the module - Team communication was very frequent,Please reflect on your team's performance in the module - We bonded personally as well as professionally,Please reflect on your team's performance in the module - We tended to collaborate together on the same tasks,Please reflect on your team's performance in the module - We tended to work on separate tasks and link them together later on,Please reflect on your team's performance in the module - I feel I have developed my professional skills as a result of the team project,Please reflect on your team's performance in the module - I feel I have developed my team working skills and my approach to collaboration as a result of the team project,Please reflect on your team's performance in the module - We adjusted the project regularly as we went along,Please reflect on your team's performance in the module - We stuck to our original project plan,"Please reflect on your team's performance in the module - Overall, I am pleased with our end result",Please add some further comments about things that you felt went well,Please add some further comments about things you felt did not go well or that the team could have done better,"On average over the term, how many hours per week outside of the timetabled classes do you think you spent on the project?"
0,3,4.0,4.0,4.0,3.0,3.0,4.0,4.0,4.0,4.0,5.0,5.0,Our supervisor was fantastic.,Not everyone on the team collaborated fully.,10.0
1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,3.0,4.0,5.0,2.0,2.0,5.0,5.0,5.0,4.0,4.0,3.0,Some team members were very involved in the wo...,Some members of the team frequently missed tea...,10.0
3,7,5.0,4.0,4.0,4.0,4.0,5.0,5.0,5.0,5.0,1.0,4.0,The zeal to work in meeting deadlines of submi...,100% Communication was not contributed by all ...,8.0
4,8,4.0,4.0,4.0,2.0,4.0,4.0,3.0,4.0,4.0,3.0,4.0,NaN,NaN,5.0
5,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,14,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,4.0,5.0,5.0,Team collaboration was perfect.,We could attend online meetings instead of off...,6.0
7,18,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,The team showed concerns in one another's pers...,I felt the team could have showed even much be...,6.0
8,22,4.0,4.0,4.0,4.0,5.0,5.0,4.0,5.0,4.0,4.0,4.0,We worked quite well together on trying to get...,One of the group members did not show up at al...,3.0
9,24,5.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,5.0,3.0,5.0,"I feel we were able to worked well as a team, ...",I would have been helpful if our initial surve...,10.0
10,27,4.0,5.0,4.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,NaN,NaN,10.0
11,33,5.0,4.0,4.0,5.0,4.0,4.0,4.0,4.0,5.0,3.0,5.0,I ALSO UNDERSTAND MY WEAKNESS AND STRENGTH,OUR ORIGINAL PROJECT WAS CHANGED AS ARESULT OF...,4.0
12,34,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,All went very nicely and smoothly,Time consuming,15.0
13,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,55,5.0,5.0,5.0,5.0,5.0,4.0,5.0,5.0,4.0,5.0,5.0,We worked well in our group and there was cons...,what the team could have done better is by kee...,14.0
16,58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,60,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,NaN,NaN,3.0
19,61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,67,4.0,4.0,4.0,4.0,4.0,5.0,5.0,5.0,2.0,5.0,5.0,we were stick to original problem and outcome.,"if we would have invloved more ,the result we ...",4.0
22,68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,70,4.0,5.0,5.0,4.0,4.0,3.0,4.0,4.0,5.0,3.0,5.0,"Although we had our differences, the team real...","Well, being from different backgrounds came wi...",4.0
24,71,4.0,4.0,4.0,4.0,3.0,5.0,5.0,5.0,5.0,5.0,5.0,NaN,NaN,8.0
25,74,5.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,1.0,5.0,Team members prompt response to change all thr...,Nothing yet,14.0
26,75,5.0,5.0,5.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,Effective communication and teamwork,"We could have done better, if other team membe...",2.0
27,78,2.0,3.0,4.0,4.0,2.0,4.0,4.0,4.0,2.0,3.0,3.0,gave me an opportunity to learn more about the...,module is bias towards people with data scienc...,10.0
28,81,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,3.0,5.0,It was great experience working in team,data was not available but we managed,10.0
29,83,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,i'm not happy with the project work at all,the fact that everyones grade in the team has ...,42.0
30,86,5.0,3.0,3.0,5.0,5.0,5.0,5.0,5.0,4.0,5.0,5.0,I learned about about open banking which I nev...,Our project management was a disaster. We were...,1.5
31,89,3.0,3.0,2.0,4.0,4.0,5.0,5.0,5.0,3.0,2.0,5.0,The things I felt went well is even the collab...,Somehow I felt that the team are just complain...,40.0
32,97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,109,5.0,5.0,4.0,3.0,4.0,4.0,5.0,5.0,4.0,3.0,5.0,NaN,NaN,5.0

In [6]:
#reading excel with multiple sheets and selecting a specific sheetx
Retrospective = pd.read_excel(xls,'Retrospective',skiprows=1,na_values='NA')
Retrospective

,"Please enter your student ID\n\nWe will use this to connect your data together, but will not share it or use it to identify you personally beyond the end of the study",Please reflect on your team's performance in the module - I really enjoyed working in the team,Please reflect on your team's performance in the module - Team communication was highly effective,Please reflect on your team's performance in the module - Team communication was very frequent,Please reflect on your team's performance in the module - We bonded personally as well as professionally,Please reflect on your team's performance in the module - We tended to collaborate together on the same tasks,Please reflect on your team's performance in the module - We tended to work on separate tasks and link them together later on,Please reflect on your team's performance in the module - I feel I have developed my professional skills as a result of the team project,Please reflect on your team's performance in the module - I feel I have developed my team working skills and my approach to collaboration as a result of the team project,Please reflect on your team's performance in the module - We adjusted the project regularly as we went along,Please reflect on your team's performance in the module - We stuck to our original project plan,"Please reflect on your team's performance in the module - Overall, I am pleased with our end result",Please add some further comments about things that you felt went well,Please add some further comments about things you felt did not go well or that the team could have done better,"On average over the term, how many hours per week outside of the timetabled classes do you think you spent on the project?"
0,3,Somewhat agree,Somewhat agree,Somewhat agree,Neither agree nor disagree,Neither agree nor disagree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Strongly agree,Strongly agree,Our supervisor was fantastic.,Not everyone on the team collaborated fully.,10.0
1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,Neither agree nor disagree,Somewhat agree,Strongly agree,Somewhat disagree,Somewhat disagree,Strongly agree,Strongly agree,Strongly agree,Somewhat agree,Somewhat agree,Neither agree nor disagree,Some team members were very involved in the wo...,Some members of the team frequently missed tea...,10.0
3,7,Strongly agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly disagree,Somewhat agree,The zeal to work in meeting deadlines of submi...,100% Communication was not contributed by all ...,8.0
4,8,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat disagree,Somewhat agree,Somewhat agree,Neither agree nor disagree,Somewhat agree,Somewhat agree,Neither agree nor disagree,Somewhat agree,NaN,NaN,5.0
5,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,14,Strongly agree,Strongly agree,Somewhat agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Somewhat agree,Strongly agree,Strongly agree,Team collaboration was perfect.,We could attend online meetings instead of off...,6.0
7,18,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,The team showed concerns in one another's pers...,I felt the team could have showed even much be...,6.0
8,22,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Strongly agree,Strongly agree,Somewhat agree,Strongly agree,Somewhat agree,Somewhat agree,Somewhat agree,We worked quite well together on trying to get...,One of the group members did not show up at al...,3.0
9,24,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Strongly agree,Neither agree nor disagree,Strongly agree,"I feel we were able to worked well as a team, ...",I would have been helpful if our initial surve...,10.0
10,27,Somewhat agree,Strongly agree,Somewhat agree,Somewhat agree,Somewhat agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,NaN,NaN,10.0
11,33,Strongly agree,Somewhat agree,Somewhat agree,Strongly agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Strongly agree,Neither agree nor disagree,Strongly agree,I ALSO UNDERSTAND MY WEAKNESS AND STRENGTH,OUR ORIGINAL PROJECT WAS CHANGED AS ARESULT OF...,4.0
12,34,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,All went very nicely and smoothly,Time consuming,15.0
13,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,55,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Somewhat agree,Strongly agree,Strongly agree,Somewhat agree,Strongly agree,Strongly agree,We worked well in our group and there was cons...,what the team could have done better is by kee...,14.0
16,58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,60,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,NaN,NaN,3.0
19,61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,67,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Strongly agree,Strongly agree,Strongly agree,Somewhat disagree,Strongly agree,Strongly agree,we were stick to original problem and outcome.,"if we would have invloved more ,the result we ...",4.0
22,68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,70,Somewhat agree,Strongly agree,Strongly agree,Somewhat agree,Somewhat agree,Neither agree nor disagree,Somewhat agree,Somewhat agree,Strongly agree,Neither agree nor disagree,Strongly agree,"Although we had our differences, the team real...","Well, being from different backgrounds came wi...",4.0
24,71,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Neither agree nor disagree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,NaN,NaN,8.0
25,74,Strongly agree,Strongly agree,Strongly agree,Somewhat agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly disagree,Strongly agree,Team members prompt response to change all thr...,Nothing yet,14.0
26,75,Strongly agree,Strongly agree,Strongly agree,Somewhat agree,Somewhat agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Effective communication and teamwork,"We could have done better, if other team membe...",2.0
27,78,Somewhat disagree,Neither agree nor disagree,Somewhat agree,Somewhat agree,Somewhat disagree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat disagree,Neither agree nor disagree,Neither agree nor disagree,gave me an opportunity to learn more about the...,module is bias towards people with data scienc...,10.0
28,81,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,Strongly agree,It was great experience working in team,data was not available but we managed,10.0
29,83,Strongly disagree,Strongly disagree,Strongly disagree,Strongly disagree,Strongly disagree,Strongly disagree,Strongly disagree,Strongly disagree,Strongly disagree,Strongly disagree,Strongly disagree,i'm not happy with the project work at all,the fact that everyones grade in the team has ...,42.0
30,86,Strongly agree,Neither agree nor disagree,Neither agree nor disagree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Somewhat agree,Strongly agree,Strongly agree,I learned about about open banking which I nev...,Our project management was a disaster. We were...,1.5
31,89,Neither agree nor disagree,Neither agree nor disagree,Somewhat disagree,Somewhat agree,Somewhat agree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,Somewhat disagree,Strongly agree,The things I felt went well is even the collab...,Somehow I felt that the team are just complain...,40.0
32,97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,109,Strongly agree,Strongly agree,Somewhat agree,Neither agree nor disagree,Somewhat agree,Somewhat agree,Strongly agree,Strongly agree,Somewhat agree,Neither agree nor disagree,Strongly agree,NaN,NaN,5.0

In [7]:
# renaming columns with spaces and special characters
df1 = pd.read_excel(xls,'Week 1',skiprows=1)
df1.columns = df1.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df1 = df1.iloc[:, 4:]
df1['main_week'] = 'week_one'
df1.drop('unnamed_40', axis=1,inplace=True)

In [8]:
# renaming columns with duplicate names
df1.columns.values[0]  = 'total_marks'
df1.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df1.columns.values[6]  = 'date_range'
df1.columns.values[18] = 'std_act_assignments'
df1.columns.values[19] = 'std_act_learning_materials'
df1.columns.values[20] = 'std_act_module_information_handbook'
df1.columns.values[21] = 'std_act_reading_list'
df1.columns.values[22] = 'std_act_week1'
df1.columns.values[23] = 'std_act_week2'
df1.columns.values[24] = 'no_of_times_accessed_assignments'
df1.columns.values[25] = 'no_of_times_accessed_learning_materials'
df1.columns.values[26] = 'no_of_times_accessed_module_information_handbook'
df1.columns.values[27] = 'no_of_times_accessed_reading_list'
df1.columns.values[28] = 'no_of_times_week1'
df1.columns.values[29] = 'no_of_times_week2'
df1.columns.values[30] = 'initial_access_assignments'
df1.columns.values[31] = 'initial_access_learning_materials'
df1.columns.values[32] = 'initial_access_information_handbook'
df1.columns.values[33] = 'initial_access_reading_list'
df1.columns.values[34] = 'initial_access_week1'
df1.columns.values[35] = 'initial_access_week2'

In [9]:
# renaming columns with spaces and special characters
df2 = pd.read_excel(xls,'Week 2',skiprows=1)
df2.columns=df2.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df2 = df2.iloc[:, 4:]
df2['main_week'] = 'week_two'

In [10]:
# renaming columns with duplicate names
df2.columns.values[0] = 'total_marks'
df2.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df2.columns.values[6]  = 'date_range'
df2.columns.values[18] = 'std_act_assignments'
df2.columns.values[19] = 'std_act_learning_materials'
df2.columns.values[20] = 'std_act_module_information_handbook'
df2.columns.values[21] = 'std_act_reading_list'
df2.columns.values[22] = 'std_act_week1'
df2.columns.values[23] = 'std_act_week2'
df2.columns.values[24] = 'std_act_week3'
df2.columns.values[25] = 'no_of_times_accessed_assignments'
df2.columns.values[26] = 'no_of_times_accessed_learning_materials'
df2.columns.values[27] = 'no_of_times_accessed_module_information_handbook'
df2.columns.values[28] = 'no_of_times_accessed_reading_list'
df2.columns.values[29] = 'no_of_times_week1'
df2.columns.values[30] = 'no_of_times_week2'
df2.columns.values[31] = 'no_of_times_week3'
df2.columns.values[32] = 'initial_access_assignments'
df2.columns.values[33] = 'initial_access_learning_materials'
df2.columns.values[34] = 'initial_access_information_handbook'
df2.columns.values[35] = 'initial_access_reading_list'
df2.columns.values[36] = 'initial_access_week1'
df2.columns.values[37] = 'initial_access_week2'
df2.columns.values[38] = 'initial_access_week3'

In [11]:
merged_df = pd.concat([df1,df2], ignore_index=True,sort=False)
merged_df

,total_marks,list_of_countries,what_is_your_year_of_birth_just_the_year,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range,monday,tuesday,wednesday,...,initial_access_assignments,initial_access_learning_materials,initial_access_information_handbook,initial_access_reading_list,initial_access_week1,initial_access_week2,main_week,std_act_week3,no_of_times_week3,initial_access_week3
0,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",1,03/10/22 - 09/10/22,0.000000,0.005278,0.014722,...,NaN,2022-10-04 15:45:00.718,NaT,NaT,2022-10-04 15:45:03.544,NaT,week_one,NaN,NaN,NaT
1,70.0,Nigeria,1996,Male,CAH07-02\tChemistry,2,03/10/22 - 09/10/22,0.000000,3.117500,0.000000,...,NaN,2022-10-04 15:48:30.421,2022-10-04 14:02:11.582,NaT,2022-10-04 15:48:38.726,NaT,week_one,NaN,NaN,NaT
2,65.0,Nigeria,1990,Female,CAH15-02\tEconomics,3,03/10/22 - 09/10/22,0.019722,1.710833,0.000000,...,NaN,2022-10-04 14:05:35.288,2022-10-03 21:49:58.608,2022-10-04 14:01:58.086,2022-10-04 14:05:37.424,NaT,week_one,NaN,NaN,NaT
3,55.0,Nigeria,1991,Male,CAH15-02\tEconomics,4,03/10/22 - 09/10/22,0.001667,0.018055,0.000000,...,NaN,2022-10-03 11:15:47.910,NaT,NaT,2022-10-03 11:15:50.346,NaT,week_one,NaN,NaN,NaT
4,65.0,Pakistan,1998,Male,CAH17-01\tBusiness and management,5,03/10/22 - 09/10/22,0.000000,2.232222,0.052778,...,NaN,2022-10-04 15:49:31.924,2022-10-05 17:49:47.691,NaT,2022-10-04 15:49:38.697,NaT,week_one,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419,60.4,India,1992,Male,CAH19-01\tEnglish studies,208,09/10/23 - 15/10/23,0.000000,1.403888,0.000000,...,NaN,2023-10-10 14:00:37.642,NaT,NaT,2023-10-10 14:01:00.490,2023-10-10 14:00:39.370,week_two,0.000000,0.0,NaT
420,64.0,Bangladesh,1996,Female,CAH17-01\tBusiness and management,209,09/10/23 - 15/10/23,2.835000,1.852500,0.000000,...,NaN,2023-10-09 22:38:40.351,NaT,2023-10-09 22:38:36.911,2023-10-09 19:59:06.028,2023-10-09 22:39:01.643,week_two,0.000000,1.0,2023-10-16 01:47:34.795
421,73.0,Sri Lanka,1996,Female,CAH11-01\tComputing,210,09/10/23 - 15/10/23,0.000000,1.731112,0.000000,...,NaN,2023-10-10 14:05:59.836,NaT,NaT,2023-10-10 14:06:03.021,2023-10-10 15:37:15.039,week_two,0.063333,2.0,2023-10-10 15:45:54.537
422,61.8,Myanmar,1998,Female,CAH11-01\tComputing,211,09/10/23 - 15/10/23,0.020000,1.141945,0.000000,...,NaN,2023-10-10 12:10:10.035,NaT,NaT,2023-10-10 12:21:11.116,2023-10-10 12:10:14.445,week_two,0.000000,1.0,2023-10-15 16:06:25.528
423,63.0,United States of America,2001,Male,CAH11-01\tComputing,212,09/10/23 - 15/10/23,0.023055,0.080833,0.000000,...,NaN,2023-10-09 18:10:56.032,NaT,NaT,2023-10-09 18:11:00.881,2023-10-10 15:37:36.341,week_two,0.000000,1.0,2023-10-10 15:41:36.312

In [12]:
# renaming columns with spaces and special characters
week3 = pd.read_excel(xls,'Week 3',skiprows=1)
week3.columns=week3.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
week3 =week3.iloc[:, 4:]
week3['main_week'] = 'week_3'

In [13]:
# renaming columns with duplicate names
week3.columns.values[0] = 'total_marks'
week3.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
week3.columns.values[6]  =  'date_range'
week3.columns.values[18] = 'std_act_assignments'
week3.columns.values[19] = 'std_act_learning_materials'
week3.columns.values[20] = 'std_act_module_information_handbook'
week3.columns.values[21] = 'std_act_reading_list'
week3.columns.values[22] = 'std_act_week1'
week3.columns.values[23] = 'std_act_week2'
week3.columns.values[24] = 'std_act_week3'
week3.columns.values[25] = 'std_act_df5'
week3.columns.values[26] = 'no_of_times_accessed_assignments'
week3.columns.values[27] = 'no_of_times_accessed_learning_materials'
week3.columns.values[28] = 'no_of_times_accessed_module_information_handbook'
week3.columns.values[29] = 'no_of_times_accessed_reading_list'
week3.columns.values[30] = 'no_of_times_week1'
week3.columns.values[31] = 'no_of_times_week2'
week3.columns.values[32] = 'no_of_times_week3'
week3.columns.values[33] = 'no_of_times_week4'
week3.columns.values[34] = 'initial_access_assignments'
week3.columns.values[35] = 'initial_access_learning_materials'
week3.columns.values[36] = 'initial_access_information_handbook'
week3.columns.values[37] = 'initial_access_reading_list'
week3.columns.values[38] = 'initial_access_week1'
week3.columns.values[39] = 'initial_access_week2'
week3.columns.values[40] = 'initial_access_week3'
week3.columns.values[41] = 'initial_access_week4'
week3 = week3.copy()

In [14]:
merged_df = pd.concat([merged_df,week3],ignore_index=True,sort=False)
merged_df = merged_df.fillna('NA')
merged_df.shape

(636, 43)

In [15]:
# renaming columns with spaces and special characters
week4 = pd.read_excel(xls,'Week 4',skiprows=1)
week4.columns=week4.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
week4 = week4 =week4.iloc[:, 4:]
week4['main_week'] = 'week5'

In [16]:
# renaming columns with duplicate names
week4.columns.values[0] = 'total_marks'
week4.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
week4.columns.values[6]  = 'date_range'
week4.columns.values[18] = 'std_act_assignments'
week4.columns.values[19] = 'std_act_learning_materials'
week4.columns.values[20] = 'std_act_module_information_handbook'
week4.columns.values[21] = 'std_act_reading_list'
week4.columns.values[22] = 'std_act_week1'
week4.columns.values[23] = 'std_act_week2'
week4.columns.values[24] = 'std_act_week3'
week4.columns.values[25] = 'std_act_week4'
week4.columns.values[26] = 'std_act_week5'
week4.columns.values[27] = 'std_act_week6'
week4.columns.values[28] = 'std_act_week7'
week4.columns.values[29] = 'no_of_times_accessed_assignments'
week4.columns.values[30] = 'no_of_times_accessed_learning_materials'
week4.columns.values[31] = 'no_of_times_accessed_module_information_handbook'
week4.columns.values[32] = 'no_of_times_accessed_reading_list'
week4.columns.values[33] = 'no_of_times_week1'
week4.columns.values[34] = 'no_of_times_week2'
week4.columns.values[35] = 'no_of_times_week3'
week4.columns.values[36] = 'no_of_times_week4'
week4.columns.values[37] = 'no_of_times_week5'
week4.columns.values[38] = 'no_of_times_week6'
week4.columns.values[39] = 'no_of_times_week7'
week4.columns.values[40] = 'initial_access_assignments'
week4.columns.values[41] = 'initial_access_learning_materials'
week4.columns.values[42] = 'initial_access_information_handbook'
week4.columns.values[43] = 'initial_access_reading_list'
week4.columns.values[44] = 'initial_access_week1'
week4.columns.values[45] = 'initial_access_week2'
week4.columns.values[46] = 'initial_access_week3'
week4.columns.values[47] = 'initial_access_week4'
week4.columns.values[48] = 'initial_access_week5'
week4.columns.values[49] = 'initial_access_week6'
week4.columns.values[50] = 'initial_access_week7'

In [17]:
merged_df = pd.concat([merged_df, week4], ignore_index=True,sort=False)
merged_df = merged_df.fillna('NA')
merged_df.shape

(848, 53)

In [18]:
# renaming columns with spaces and special characters
df5 = pd.read_excel(xls,'Week 5',skiprows=1)
df5.columns=df5.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df5 =df5.iloc[:, 4:]
[i for i in enumerate(df5.columns)]
df5['main_week'] = 'week_fve'

In [19]:
# renaming columns with duplicate names
df5.columns.values[0] = 'total_marks'
df5.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df5.columns.values[6]  = 'date_range'
df5.columns.values[18] = 'std_act_assignments'
df5.columns.values[19] = 'std_act_learning_materials'
df5.columns.values[20] = 'std_act_module_information_handbook'
df5.columns.values[21] = 'std_act_reading_list'
df5.columns.values[22] = 'std_act_week1'
df5.columns.values[23] = 'std_act_week2'
df5.columns.values[24] = 'std_act_week3'
df5.columns.values[25] = 'std_act_week4'
df5.columns.values[26] = 'std_act_week5'
df5.columns.values[27] = 'std_act_week6'
df5.columns.values[28] = 'no_of_times_accessed_assignments'
df5.columns.values[29] = 'no_of_times_accessed_learning_materials'
df5.columns.values[30] = 'no_of_times_accessed_module_information_handbook'
df5.columns.values[31] = 'no_of_times_accessed_reading_list'
df5.columns.values[32] = 'no_of_times_week1'
df5.columns.values[33] = 'no_of_times_week2'
df5.columns.values[34] = 'no_of_times_week3'
df5.columns.values[35] = 'no_of_times_week4'
df5.columns.values[36] = 'no_of_times_week5'
df5.columns.values[37] = 'no_of_times_week6'
df5.columns.values[38] = 'initial_access_assignments'
df5.columns.values[39] = 'initial_access_learning_materials'
df5.columns.values[40] = 'initial_access_information_handbook'
df5.columns.values[41] = 'initial_access_reading_list'
df5.columns.values[42] = 'initial_access_week1'
df5.columns.values[43] = 'initial_access_week2'
df5.columns.values[44] = 'initial_access_week3'
df5.columns.values[45] = 'initial_access_week4'
df5.columns.values[46] = 'initial_access_week5'
df5.columns.values[47] = 'initial_access_week6'

In [20]:
merged_df = pd.concat([merged_df,df5],ignore_index=True,sort=False)
merged_df.fillna('NA',inplace=True)
merged_df.shape

(1060, 53)

In [21]:
# renaming columns with spaces and special characters
df6 = pd.read_excel(xls,'Week 6',skiprows=1)
df6.columns=df6.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df6 = df6.iloc[:, 4:]
df6['main_week'] = 'week_six'

In [22]:
# renaming columns with duplicate names
df6.columns.values[0] = 'total_marks'
df6.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df6.columns.values[6]  = 'date_range'
df6.columns.values[18] = 'std_act_assignments'
df6.columns.values[19] = 'std_act_learning_materials'
df6.columns.values[20] = 'std_act_module_information_handbook'
df6.columns.values[21] = 'std_act_reading_list'
df6.columns.values[22] = 'std_act_week1'
df6.columns.values[23] = 'std_act_week2'
df6.columns.values[24] = 'std_act_week3'
df6.columns.values[25] = 'std_act_week4'
df6.columns.values[26] = 'std_act_week5'
df6.columns.values[27] = 'std_act_week6'
df6.columns.values[28] = 'std_act_week7'
df6.columns.values[29] = 'no_of_times_accessed_assignments'
df6.columns.values[30] = 'no_of_times_accessed_learning_materials'
df6.columns.values[31] = 'no_of_times_accessed_module_information_handbook'
df6.columns.values[32] = 'no_of_times_accessed_reading_list'
df6.columns.values[33] = 'no_of_times_week1'
df6.columns.values[34] = 'no_of_times_week2'
df6.columns.values[35] = 'no_of_times_week3'
df6.columns.values[36] = 'no_of_times_week4'
df6.columns.values[37] = 'no_of_times_week5'
df6.columns.values[38] = 'no_of_times_week6'
df6.columns.values[39] = 'no_of_times_week7'
df6.columns.values[40] = 'initial_access_assignments'
df6.columns.values[41] = 'initial_access_learning_materials'
df6.columns.values[42] = 'initial_access_information_handbook'
df6.columns.values[43] = 'initial_access_reading_list'
df6.columns.values[44] = 'initial_access_week1'
df6.columns.values[45] = 'initial_access_week2'
df6.columns.values[46] = 'initial_access_week3'
df6.columns.values[47] = 'initial_access_week4'
df6.columns.values[48] = 'initial_access_week5'
df6.columns.values[49] = 'initial_access_week6'
df6.columns.values[50] = 'initial_access_week7'

In [23]:
merged_df = pd.concat([merged_df,df6],ignore_index=True,sort=False)
merged_df.fillna('NA', inplace=True)
merged_df.shape

(1272, 53)

In [24]:
# renaming columns with spaces and special characters
df7 = pd.read_excel(xls,'Week 7',skiprows=1)
df7.columns=df7.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df7 = df7.iloc[:, 4:]
df7['main_week'] = 'week_seven'
[i for i in enumerate(df7.columns)]

[(0, 'unnamed_4'),
 (1, 'list_of_countries'),
 (2, 'what_is_your_year_of_birth_just_the_year_eg_1995_'),
 (3, 'how_do_you_describe_yourself___selected_choice'),
 (4, 'what_is_your_first_degree_subject_area'),
 (5, 'student_id'),
 (6, 'date_range__week_7'),
 (7, 'monday'),
 (8, 'tuesday'),
 (9, 'wednesday'),
 (10, 'thursday'),
 (11, 'friday'),
 (12, 'saturday'),
 (13, 'sunday'),
 (14, 'student_time_in_course'),
 (15, 'avg_time_per_user'),
 (16, 'total_items'),
 (17, 'total_logins'),
 (18, 'assignments'),
 (19, 'learning_materials'),
 (20, 'module_information_handbook'),
 (21, 'reading_list'),
 (22, 'week_1'),
 (23, 'week_2_'),
 (24, 'week_3'),
 (25, 'week_4'),
 (26, 'week_5'),
 (27, 'week_6'),
 (28, 'week_7'),
 (29, 'week_8'),
 (30, 'assignments1'),
 (31, 'learning_materials1'),
 (32, 'module_information_handbook'),
 (33, 'reading_list1'),
 (34, 'week_11'),
 (35, 'week_2_1'),
 (36, 'week_3'),
 (37, 'week_41'),
 (38, 'week_51'),
 (39, 'week_61'),
 (40, 'week_71'),
 (41, 'week_81'),
 (42, 'assignments2'),
 (43, 'learning_materials2'),
 (44, 'module_information_handbook1'),
 (45, 'reading_list2'),
 (46, 'week_12'),
 (47, 'week_2'),
 (48, 'week_31'),
 (49, 'week_42'),
 (50, 'week_52'),
 (51, 'week_6'),
 (52, 'week_72'),
 (53, 'week_82'),
 (54, 'main_week')]

In [25]:
# renaming columns with duplicate names
df7.columns.values[0] = 'total_marks'
df7.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df7.columns.values[6]  = 'date_range'
df7.columns.values[18] = 'std_act_assignments'
df7.columns.values[19] = 'std_act_learning_materials'
df7.columns.values[20] = 'std_act_module_information_handbook'
df7.columns.values[21] = 'std_act_reading_list'
df7.columns.values[22] = 'std_act_week1'
df7.columns.values[23] = 'std_act_week2'
df7.columns.values[24] = 'std_act_week3'
df7.columns.values[25] = 'std_act_week4'
df7.columns.values[26] = 'std_act_week5'
df7.columns.values[27] = 'std_act_week6'
df7.columns.values[28] = 'std_act_week7'
df7.columns.values[29] = 'std_act_week8'
df7.columns.values[30] = 'no_of_times_accessed_assignments'
df7.columns.values[31] = 'no_of_times_accessed_learning_materials'
df7.columns.values[32] = 'no_of_times_accessed_module_information_handbook'
df7.columns.values[33] = 'no_of_times_accessed_reading_list'
df7.columns.values[34] = 'no_of_times_week1'
df7.columns.values[35] = 'no_of_times_week2'
df7.columns.values[36] = 'no_of_times_week3'
df7.columns.values[37] = 'no_of_times_week4'
df7.columns.values[38] = 'no_of_times_week5'
df7.columns.values[39] = 'no_of_times_week6'
df7.columns.values[40] = 'no_of_times_week7'
df7.columns.values[41] = 'no_of_times_week8'
df7.columns.values[42] = 'initial_access_assignments'
df7.columns.values[43] = 'initial_access_learning_materials'
df7.columns.values[44] = 'initial_access_information_handbook'
df7.columns.values[45] = 'initial_access_reading_list'
df7.columns.values[46] = 'initial_access_week1'
df7.columns.values[47] = 'initial_access_week2'
df7.columns.values[48] = 'initial_access_week3'
df7.columns.values[49] = 'initial_access_week4'
df7.columns.values[50] = 'initial_access_week5'
df7.columns.values[51] = 'initial_access_week6'
df7.columns.values[52] = 'initial_access_week7'
df7.columns.values[53] = 'initial_access_week8'

In [26]:
merged_df = pd.concat([merged_df,df7],ignore_index=True,sort=False)
merged_df.fillna('NA', inplace=True)

In [27]:
# renaming columns with spaces and special characters
df8 = pd.read_excel(xls,'Week 8',skiprows=1)
df8.columns=df8.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df8 = df8.iloc[:, 4:]
df8['main_week'] = 'week_eight'
[i for i in enumerate(df8.columns)]

[(0, 'unnamed_4'),
 (1, 'list_of_countries'),
 (2, 'what_is_your_year_of_birth_just_the_year_eg_1995_'),
 (3, 'how_do_you_describe_yourself___selected_choice'),
 (4, 'what_is_your_first_degree_subject_area'),
 (5, 'student_id'),
 (6, 'date_range__week_8'),
 (7, 'monday'),
 (8, 'tuesday'),
 (9, 'wednesday'),
 (10, 'thursday'),
 (11, 'friday'),
 (12, 'saturday'),
 (13, 'sunday'),
 (14, 'student_time_in_course'),
 (15, 'avg_time_per_user'),
 (16, 'total_items'),
 (17, 'total_logins'),
 (18, 'assignments'),
 (19, 'learning_materials'),
 (20, 'module_information_handbook'),
 (21, 'reading_list'),
 (22, 'week_1'),
 (23, 'week_2_'),
 (24, 'week_3'),
 (25, 'week_4'),
 (26, 'week_5'),
 (27, 'week_6'),
 (28, 'week_7'),
 (29, 'week_8'),
 (30, 'week_9'),
 (31, 'assignments1'),
 (32, 'learning_materials1'),
 (33, 'module_information_handbook'),
 (34, 'reading_list1'),
 (35, 'week_11'),
 (36, 'week_2'),
 (37, 'week_3_'),
 (38, 'week_41'),
 (39, 'week_51'),
 (40, 'week_61'),
 (41, 'week_71'),
 (42, 'week_81'),
 (43, 'week_91'),
 (44, 'assignments2'),
 (45, 'learning_materials2'),
 (46, 'module_information_handbook1'),
 (47, 'reading_list2'),
 (48, 'week_12'),
 (49, 'week_2_1'),
 (50, 'week_31'),
 (51, 'week_42'),
 (52, 'week_52'),
 (53, 'week_62'),
 (54, 'week_72'),
 (55, 'week_82'),
 (56, 'week_92'),
 (57, 'main_week')]

In [28]:
# renaming columns with duplicate names
df8.columns.values[0] = 'total_marks'
df8.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df8.columns.values[6]  = 'date_range'
df8.columns.values[18] = 'std_act_assignments'
df8.columns.values[19] = 'std_act_learning_materials'
df8.columns.values[20] = 'std_act_module_information_handbook'
df8.columns.values[21] = 'std_act_reading_list'
df8.columns.values[22] = 'std_act_week1'
df8.columns.values[23] = 'std_act_week2'
df8.columns.values[24] = 'std_act_week3'
df8.columns.values[25] = 'std_act_week4'
df8.columns.values[26] = 'std_act_week5'
df8.columns.values[27] = 'std_act_week6'
df8.columns.values[28] = 'std_act_week7'
df8.columns.values[29] = 'std_act_week8'
df8.columns.values[30] = 'std_act_week9'
df8.columns.values[31] = 'no_of_times_accessed_assignments'
df8.columns.values[32] = 'no_of_times_accessed_learning_materials'
df8.columns.values[33] = 'no_of_times_accessed_module_information_handbook'
df8.columns.values[34] = 'no_of_times_accessed_reading_list'
df8.columns.values[35] = 'no_of_times_week1'
df8.columns.values[36] = 'no_of_times_week2'
df8.columns.values[37] = 'no_of_times_week3'
df8.columns.values[38] = 'no_of_times_week4'
df8.columns.values[39] = 'no_of_times_week5'
df8.columns.values[40] = 'no_of_times_week6'
df8.columns.values[41] = 'no_of_times_week7'
df8.columns.values[42] = 'no_of_times_week8'
df8.columns.values[43] = 'no_of_times_week9'
df8.columns.values[44] = 'initial_access_assignments'
df8.columns.values[45] = 'initial_access_learning_materials'
df8.columns.values[46] = 'initial_access_information_handbook'
df8.columns.values[47] = 'initial_access_reading_list'
df8.columns.values[48] = 'initial_access_week1'
df8.columns.values[49] = 'initial_access_week2'
df8.columns.values[50] = 'initial_access_week3'
df8.columns.values[51] = 'initial_access_week4'
df8.columns.values[52] = 'initial_access_week5'
df8.columns.values[53] = 'initial_access_week6'
df8.columns.values[54] = 'initial_access_week7'
df8.columns.values[55] = 'initial_access_week8'
df8.columns.values[56] = 'initial_access_week9'

In [29]:
merged_df = pd.concat([merged_df,df8],ignore_index=True,sort=False)
merged_df.fillna('NA', inplace=True)
merged_df

,total_marks,list_of_countries,what_is_your_year_of_birth_just_the_year,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range,monday,tuesday,wednesday,...,no_of_times_week7,initial_access_week5,initial_access_week6,initial_access_week7,std_act_week8,no_of_times_week8,initial_access_week8,std_act_week9,no_of_times_week9,initial_access_week9
0,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",1,03/10/22 - 09/10/22,0.000000,0.005278,0.014722,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
1,70.0,Nigeria,1996,Male,CAH07-02\tChemistry,2,03/10/22 - 09/10/22,0.000000,3.117500,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
2,65.0,Nigeria,1990,Female,CAH15-02\tEconomics,3,03/10/22 - 09/10/22,0.019722,1.710833,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
3,55.0,Nigeria,1991,Male,CAH15-02\tEconomics,4,03/10/22 - 09/10/22,0.001667,0.018055,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
4,65.0,Pakistan,1998,Male,CAH17-01\tBusiness and management,5,03/10/22 - 09/10/22,0.000000,2.232222,0.052778,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1691,60.4,India,1992,Male,CAH19-01\tEnglish studies,208,20/11/23 - 26/11/23,0.000000,0.141667,0.000000,...,1,NA,NA,2023-11-21 14:27:32.190000,0.0,1,2023-11-21 14:28:14.708000,0.0,0.0,NA
1692,64.0,Bangladesh,1996,Female,CAH17-01\tBusiness and management,209,20/11/23 - 26/11/23,0.193888,0.178612,0.000000,...,0,NA,NA,NA,0.0,1,2023-11-21 14:27:40.827000,0.0,0.0,NA
1693,73.0,Sri Lanka,1996,Female,CAH11-01\tComputing,210,20/11/23 - 26/11/23,0.000000,2.178333,0.823612,...,0,NA,NA,NA,1.815555,2,2023-11-21 13:52:08.504000,0.0,0.0,NA
1694,61.8,Myanmar,1998,Female,CAH11-01\tComputing,211,20/11/23 - 26/11/23,2.264443,0.100555,0.000000,...,3,NA,NA,2023-11-20 03:08:19.424000,0.003888,2,2023-11-21 00:37:39.742000,0.0,0.0,NA
1695,63.0,United States of America,2001,Male,CAH11-01\tComputing,212,20/11/23 - 26/11/23,0.000000,0.014167,0.000000,...,0,NA,NA,NA,0.0,1,2023-11-21 14:19:26.822000,0.0,0.0,NA

In [30]:
# renaming columns with spaces and special characters
df9 = pd.read_excel(xls,'Week 9',skiprows=1)
df9.columns=df9.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df9 = df9.iloc[:, 4:]
df9['main_week'] = 'week_nine'

In [31]:
# renaming columns with duplicate names
df9.columns.values[0] = 'total_marks'
df9.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df9.columns.values[6]  = 'date_range'
df9.columns.values[18] = 'std_act_assignments'
df9.columns.values[19] = 'std_act_learning_materials'
df9.columns.values[20] = 'std_act_module_information_handbook'
df9.columns.values[21] = 'std_act_reading_list'
df9.columns.values[22] = 'std_act_week1'
df9.columns.values[23] = 'std_act_week2'
df9.columns.values[24] = 'std_act_week3'
df9.columns.values[25] = 'std_act_week4'
df9.columns.values[26] = 'std_act_week5'
df9.columns.values[27] = 'std_act_week6'
df9.columns.values[28] = 'std_act_week7'
df9.columns.values[29] = 'std_act_week8'
df9.columns.values[30] = 'std_act_week9'
df9.columns.values[31] = 'std_act_week10'
df9.columns.values[32] = 'no_of_times_accessed_assignments'
df9.columns.values[33] = 'no_of_times_accessed_learning_materials'
df9.columns.values[34] = 'no_of_times_accessed_module_information_handbook'
df9.columns.values[35] = 'no_of_times_accessed_reading_list'
df9.columns.values[36] = 'no_of_times_week1'
df9.columns.values[37] = 'no_of_times_week2'
df9.columns.values[38] = 'no_of_times_week3'
df9.columns.values[39] = 'no_of_times_week4'
df9.columns.values[40] = 'no_of_times_week5'
df9.columns.values[41] = 'no_of_times_week6'
df9.columns.values[42] = 'no_of_times_week7'
df9.columns.values[43] = 'no_of_times_week8'
df9.columns.values[44] = 'no_of_times_week9'
df9.columns.values[45] = 'no_of_times_week10'
df9.columns.values[46] = 'initial_access_assignments'
df9.columns.values[47] = 'initial_access_learning_materials'
df9.columns.values[48] = 'initial_access_information_handbook'
df9.columns.values[49] = 'initial_access_reading_list'
df9.columns.values[50] = 'initial_access_week1'
df9.columns.values[51] = 'initial_access_week2'
df9.columns.values[52] = 'initial_access_week3'
df9.columns.values[53] = 'initial_access_week4'
df9.columns.values[54] = 'initial_access_week5'
df9.columns.values[55] = 'initial_access_week6'
df9.columns.values[56] = 'initial_access_week7'
df9.columns.values[57] = 'initial_access_week8'
df9.columns.values[58] = 'initial_access_week9'
df9.columns.values[59] = 'initial_access_week10'

In [32]:
merged_df = pd.concat([merged_df,df9],ignore_index=True,sort=False)
merged_df.fillna('NA', inplace=True)
merged_df

,total_marks,list_of_countries,what_is_your_year_of_birth_just_the_year,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range,monday,tuesday,wednesday,...,initial_access_week7,std_act_week8,no_of_times_week8,initial_access_week8,std_act_week9,no_of_times_week9,initial_access_week9,std_act_week10,no_of_times_week10,initial_access_week10
0,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",1,03/10/22 - 09/10/22,0.000000,0.005278,0.014722,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
1,70.0,Nigeria,1996,Male,CAH07-02\tChemistry,2,03/10/22 - 09/10/22,0.000000,3.117500,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
2,65.0,Nigeria,1990,Female,CAH15-02\tEconomics,3,03/10/22 - 09/10/22,0.019722,1.710833,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
3,55.0,Nigeria,1991,Male,CAH15-02\tEconomics,4,03/10/22 - 09/10/22,0.001667,0.018055,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
4,65.0,Pakistan,1998,Male,CAH17-01\tBusiness and management,5,03/10/22 - 09/10/22,0.000000,2.232222,0.052778,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1903,60.4,India,1992,Male,CAH19-01\tEnglish studies,208,27/11/23 - 03/12/23,0.000000,0.000000,0.185833,...,NA,0.0,0,NA,0.0,0,NA,0.0,0.0,NA
1904,64.0,Bangladesh,1996,Female,CAH17-01\tBusiness and management,209,27/11/23 - 03/12/23,0.000000,0.179722,0.000000,...,NA,0.0,0,NA,0.091112,1,2023-11-28 14:24:39.901000,0.0,0.0,NA
1905,73.0,Sri Lanka,1996,Female,CAH11-01\tComputing,210,27/11/23 - 03/12/23,0.000000,0.592778,0.005833,...,NA,0.0,0,NA,0.004443,4,2023-11-28 11:46:23.507000,0.0,0.0,NA
1906,61.8,Myanmar,1998,Female,CAH11-01\tComputing,211,27/11/23 - 03/12/23,2.553333,0.003612,0.000000,...,NA,0.0,0,NA,0.012778,4,2023-11-27 11:22:05.677000,0.0,0.0,NA
1907,63.0,United States of America,2001,Male,CAH11-01\tComputing,212,27/11/23 - 03/12/23,0.000000,0.001667,0.000000,...,NA,0.0,0,NA,0.0,0,NA,0.0,0.0,NA

In [33]:
# renaming columns with spaces and special characters
df10 = pd.read_excel(xls,'Week 10',skiprows=1)
df10.columns=df10.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df10 = df10.iloc[:, 4:]
df10['main_week'] = 'week_ten'
[i for i in enumerate(df10.columns)]

[(0, 'unnamed_4'),
 (1, 'list_of_countries'),
 (2, 'what_is_your_year_of_birth_just_the_year_eg_1995_'),
 (3, 'how_do_you_describe_yourself___selected_choice'),
 (4, 'what_is_your_first_degree_subject_area'),
 (5, 'student_id'),
 (6, 'date_range__week_10'),
 (7, 'monday'),
 (8, 'tuesday'),
 (9, 'wednesday'),
 (10, 'thursday'),
 (11, 'friday'),
 (12, 'saturday'),
 (13, 'sunday'),
 (14, 'student_time_in_course'),
 (15, 'avg_time_per_user'),
 (16, 'total_items'),
 (17, 'total_logins'),
 (18, 'assignments'),
 (19, 'learning_materials'),
 (20, 'module_information_handbook'),
 (21, 'reading_list'),
 (22, 'week_1'),
 (23, 'week_2'),
 (24, 'week_3_'),
 (25, 'week_4'),
 (26, 'week_5'),
 (27, 'week_6'),
 (28, 'week_7'),
 (29, 'week_8'),
 (30, 'week_9'),
 (31, 'week_10'),
 (32, 'assignments1'),
 (33, 'learning_materials1'),
 (34, 'module_information_handbook'),
 (35, 'reading_list1'),
 (36, 'week_11'),
 (37, 'week_21'),
 (38, 'week_3_'),
 (39, 'week_41'),
 (40, 'week_51'),
 (41, 'week_61'),
 (42, 'week_71'),
 (43, 'week_81'),
 (44, 'week_91'),
 (45, 'week_101'),
 (46, 'assignments2'),
 (47, 'learning_materials2'),
 (48, 'module_information_handbook1'),
 (49, 'reading_list2'),
 (50, 'week_12'),
 (51, 'week_2_'),
 (52, 'week_3_1'),
 (53, 'week_42'),
 (54, 'week_52'),
 (55, 'week_62'),
 (56, 'week_72'),
 (57, 'week_82'),
 (58, 'week_92'),
 (59, 'week_102'),
 (60, 'main_week')]

In [34]:
# renaming columns with duplicate names
df10.columns.values[0] = 'total_marks'
df10.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df10.columns.values[6]  = 'date_range'
df10.columns.values[18] = 'std_act_assignments'
df10.columns.values[19] = 'std_act_learning_materials'
df10.columns.values[20] = 'std_act_module_information_handbook'
df10.columns.values[21] = 'std_act_reading_list'
df10.columns.values[22] = 'std_act_week1'
df10.columns.values[23] = 'std_act_week2'
df10.columns.values[24] = 'std_act_week3'
df10.columns.values[25] = 'std_act_week4'
df10.columns.values[26] = 'std_act_week5'
df10.columns.values[27] = 'std_act_week6'
df10.columns.values[28] = 'std_act_week7'
df10.columns.values[29] = 'std_act_week8'
df10.columns.values[30] = 'std_act_week9'
df10.columns.values[31] = 'std_act_week10'
df10.columns.values[32] = 'no_of_times_accessed_assignments'
df10.columns.values[33] = 'no_of_times_accessed_learning_materials'
df10.columns.values[34] = 'no_of_times_accessed_module_information_handbook'
df10.columns.values[35] = 'no_of_times_accessed_reading_list'
df10.columns.values[36] = 'no_of_times_week1'
df10.columns.values[37] = 'no_of_times_week2'
df10.columns.values[38] = 'no_of_times_week3'
df10.columns.values[39] = 'no_of_times_week4'
df10.columns.values[40] = 'no_of_times_week5'
df10.columns.values[41] = 'no_of_times_week6'
df10.columns.values[42] = 'no_of_times_week7'
df10.columns.values[43] = 'no_of_times_week8'
df10.columns.values[44] = 'no_of_times_week9'
df10.columns.values[45] = 'no_of_times_week10'
df10.columns.values[46] = 'initial_access_assignments'
df10.columns.values[47] = 'initial_access_learning_materials'
df10.columns.values[48] = 'initial_access_information_handbook'
df10.columns.values[49] = 'initial_access_reading_list'
df10.columns.values[50] = 'initial_access_week1'
df10.columns.values[51] = 'initial_access_week2'
df10.columns.values[52] = 'initial_access_week3'
df10.columns.values[53] = 'initial_access_week4'
df10.columns.values[54] = 'initial_access_week5'
df10.columns.values[55] = 'initial_access_week6'
df10.columns.values[56] = 'initial_access_week7'
df10.columns.values[57] = 'initial_access_week8'
df10.columns.values[58] = 'initial_access_week9'
df10.columns.values[59] = 'initial_access_week10'

In [35]:
merged_df = pd.concat([merged_df,df10],ignore_index=True,sort=False)
merged_df.fillna('NA', inplace=True)
merged_df

,total_marks,list_of_countries,what_is_your_year_of_birth_just_the_year,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range,monday,tuesday,wednesday,...,initial_access_week7,std_act_week8,no_of_times_week8,initial_access_week8,std_act_week9,no_of_times_week9,initial_access_week9,std_act_week10,no_of_times_week10,initial_access_week10
0,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",1,03/10/22 - 09/10/22,0.000000,0.005278,0.014722,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
1,70.0,Nigeria,1996,Male,CAH07-02\tChemistry,2,03/10/22 - 09/10/22,0.000000,3.117500,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
2,65.0,Nigeria,1990,Female,CAH15-02\tEconomics,3,03/10/22 - 09/10/22,0.019722,1.710833,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
3,55.0,Nigeria,1991,Male,CAH15-02\tEconomics,4,03/10/22 - 09/10/22,0.001667,0.018055,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
4,65.0,Pakistan,1998,Male,CAH17-01\tBusiness and management,5,03/10/22 - 09/10/22,0.000000,2.232222,0.052778,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2115,60.4,India,1992,Male,CAH19-01\tEnglish studies,208,04/12/23 - 10/12/23,0.108333,0.098888,0.000000,...,NA,0.0,0,NA,0.0,0,NA,0.0,0,NA
2116,64.0,Bangladesh,1996,Female,CAH17-01\tBusiness and management,209,04/12/23 - 10/12/23,0.008333,0.006388,0.000000,...,NA,0.0,0,NA,0.0,0,NA,0.0,0,NA
2117,73.0,Sri Lanka,1996,Female,CAH11-01\tComputing,210,04/12/23 - 10/12/23,3.331112,1.504722,0.008888,...,NA,0.0,0,NA,0.0,0,NA,0.0,1,2023-12-05 12:35:03.715000
2118,61.8,Myanmar,1998,Female,CAH11-01\tComputing,211,04/12/23 - 10/12/23,0.000000,0.583055,0.463055,...,NA,0.0,0,NA,0.0,0,NA,0.0,2,2023-12-05 12:32:54.983000
2119,63.0,United States of America,2001,Male,CAH11-01\tComputing,212,04/12/23 - 10/12/23,0.000000,0.000000,0.000000,...,NA,0.0,0,NA,0.0,0,NA,0.0,0,NA

In [36]:
# renaming columns with spaces and special characters
df11 = pd.read_excel(xls,'Week 11',skiprows=1)
df11.columns=df11.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df11 = df11.iloc[:, 4:]
df11['main_week'] = 'week_eleven'
[i for i in enumerate(df11.columns)]

[(0, 'unnamed_4'),
 (1, 'list_of_countries'),
 (2, 'what_is_your_year_of_birth_just_the_year_eg_1995_'),
 (3, 'how_do_you_describe_yourself___selected_choice'),
 (4, 'what_is_your_first_degree_subject_area'),
 (5, 'student_id'),
 (6, 'date_range__week_11'),
 (7, 'monday'),
 (8, 'tuesday'),
 (9, 'wednesday'),
 (10, 'thursday'),
 (11, 'friday'),
 (12, 'saturday'),
 (13, 'sunday'),
 (14, 'student_time_in_course'),
 (15, 'avg_time_per_user'),
 (16, 'total_items'),
 (17, 'total_logins'),
 (18, 'assignments'),
 (19, 'learning_materials'),
 (20, 'module_information_handbook'),
 (21, 'reading_list'),
 (22, 'week_1'),
 (23, 'week_2_'),
 (24, 'week_3_'),
 (25, 'week_4'),
 (26, 'week_5'),
 (27, 'week_6'),
 (28, 'week_7'),
 (29, 'week_8'),
 (30, 'week_9'),
 (31, 'week_10'),
 (32, 'week_11feedback'),
 (33, 'assignments1'),
 (34, 'learning_materials1'),
 (35, 'module_information_handbook'),
 (36, 'reading_list1'),
 (37, 'week_11'),
 (38, 'week_2_1'),
 (39, 'week_3_'),
 (40, 'week_41'),
 (41, 'week_51'),
 (42, 'week_61'),
 (43, 'week_71'),
 (44, 'week_81'),
 (45, 'week_91'),
 (46, 'week_101'),
 (47, 'week_11feedback1'),
 (48, 'assignments2'),
 (49, 'learning_materials2'),
 (50, 'module_information_handbook1'),
 (51, 'reading_list2'),
 (52, 'week_12'),
 (53, 'week_2_2'),
 (54, 'week_3'),
 (55, 'week_42'),
 (56, 'week_52'),
 (57, 'week_62'),
 (58, 'week_72'),
 (59, 'week_82'),
 (60, 'week_92'),
 (61, 'week_102'),
 (62, 'week_11feedback2'),
 (63, 'main_week')]

In [37]:
# renaming columns with duplicate names
df11.columns.values[0] = 'total_marks'
df11.columns.values[2]  = 'what_is_your_year_of_birth_just_the_year'
df11.columns.values[6]  = 'date_range'
df11.columns.values[18] = 'std_act_assignments'
df11.columns.values[19] = 'std_act_learning_materials'
df11.columns.values[20] = 'std_act_module_information_handbook'
df11.columns.values[21] = 'std_act_reading_list'
df11.columns.values[22] = 'std_act_week1'
df11.columns.values[23] = 'std_act_week2'
df11.columns.values[24] = 'std_act_week3'
df11.columns.values[25] = 'std_act_week4'
df11.columns.values[26] = 'std_act_week5'
df11.columns.values[27] = 'std_act_week6'
df11.columns.values[28] = 'std_act_week7'
df11.columns.values[29] = 'std_act_week8'
df11.columns.values[30] = 'std_act_week9'
df11.columns.values[31] = 'std_act_week10'
df11.columns.values[32] = 'std_act_week_11_feedback'
df11.columns.values[33] = 'no_of_times_accessed_assignments'
df11.columns.values[34] = 'no_of_times_accessed_learning_materials'
df11.columns.values[35] = 'no_of_times_accessed_module_information_handbook'
df11.columns.values[36] = 'no_of_times_accessed_reading_list'
df11.columns.values[37] = 'no_of_times_week1'
df11.columns.values[38] = 'no_of_times_week2'
df11.columns.values[39] = 'no_of_times_week3'
df11.columns.values[40] = 'no_of_times_week4'
df11.columns.values[41] = 'no_of_times_week5'
df11.columns.values[42] = 'no_of_times_week6'
df11.columns.values[43] = 'no_of_times_week7'
df11.columns.values[44] = 'no_of_times_week8'
df11.columns.values[45] = 'no_of_times_week9'
df11.columns.values[46] = 'no_of_times_week10'
df11.columns.values[47] = 'no_of_times_week11_feedback'
df11.columns.values[48] = 'initial_access_assignments'
df11.columns.values[49] = 'initial_access_learning_materials'
df11.columns.values[50] = 'initial_access_information_handbook'
df11.columns.values[51] = 'initial_access_reading_list'
df11.columns.values[52] = 'initial_access_week1'
df11.columns.values[53] = 'initial_access_week2'
df11.columns.values[54] = 'initial_access_week3'
df11.columns.values[55] = 'initial_access_week4'
df11.columns.values[56] = 'initial_access_week5'
df11.columns.values[57] = 'initial_access_week6'
df11.columns.values[58] = 'initial_access_week7'
df11.columns.values[59] = 'initial_access_week8'
df11.columns.values[60] = 'initial_access_week9'
df11.columns.values[61] = 'initial_access_week10'
df11.columns.values[62] = 'initial_access_week11_feedback'

In [38]:
merged_df = pd.concat([merged_df,df11],ignore_index=True,sort=False)
merged_df.fillna('NA', inplace=True)
merged_df

,total_marks,list_of_countries,what_is_your_year_of_birth_just_the_year,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range,monday,tuesday,wednesday,...,initial_access_week8,std_act_week9,no_of_times_week9,initial_access_week9,std_act_week10,no_of_times_week10,initial_access_week10,std_act_week_11_feedback,no_of_times_week11_feedback,initial_access_week11_feedback
0,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",1,03/10/22 - 09/10/22,0.000000,0.005278,0.014722,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
1,70.0,Nigeria,1996,Male,CAH07-02\tChemistry,2,03/10/22 - 09/10/22,0.000000,3.117500,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
2,65.0,Nigeria,1990,Female,CAH15-02\tEconomics,3,03/10/22 - 09/10/22,0.019722,1.710833,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
3,55.0,Nigeria,1991,Male,CAH15-02\tEconomics,4,03/10/22 - 09/10/22,0.001667,0.018055,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
4,65.0,Pakistan,1998,Male,CAH17-01\tBusiness and management,5,03/10/22 - 09/10/22,0.000000,2.232222,0.052778,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2327,60.4,India,1992,Male,CAH19-01\tEnglish studies,208,11/12/23 - 17/12/23,0.000000,0.000000,0.301667,...,NA,0.0,0,NA,0.0,0,NA,0.0,0.0,NA
2328,64.0,Bangladesh,1996,Female,CAH17-01\tBusiness and management,209,11/12/23 - 17/12/23,0.000000,0.017778,0.022778,...,NA,0.0,0,NA,0.0,0,NA,0.013612,1.0,2023-12-12 14:30:47.321000
2329,73.0,Sri Lanka,1996,Female,CAH11-01\tComputing,210,11/12/23 - 17/12/23,3.059722,2.752778,0.000000,...,NA,0.0,0,NA,0.0,0,NA,0.014445,1.0,2023-12-12 14:16:13.475000
2330,61.8,Myanmar,1998,Female,CAH11-01\tComputing,211,11/12/23 - 17/12/23,0.016667,0.113888,0.000000,...,NA,0.0,0,NA,0.0,0,NA,0.008888,4.0,2023-12-11 20:07:31.608000
2331,63.0,United States of America,2001,Male,CAH11-01\tComputing,212,11/12/23 - 17/12/23,0.000000,1.459445,0.000000,...,NA,0.0,0,NA,0.0,0,NA,0.251388,1.0,2023-12-12 14:17:38.059000

In [39]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2332 entries, 0 to 2331
Data columns (total 65 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   total_marks                                       2332 non-null   float64
 1   list_of_countries                                 2332 non-null   object
 2   what_is_your_year_of_birth_just_the_year          2332 non-null   int64
 3   how_do_you_describe_yourself___selected_choice    2332 non-null   object
 4   what_is_your_first_degree_subject_area            2332 non-null   object
 5   student_id                                        2332 non-null   int64
 6   date_range                                        2332 non-null   object
 7   monday                                            2332 non-null   float64
 8   tuesday                                           2332 non-null   float64
 9   wednesday                                         2332 non-null   float64
 10  thursday                                          2332 non-null   float64
 11  friday                                            2332 non-null   float64
 12  saturday                                          2332 non-null   float64
 13  sunday                                            2332 non-null   float64
 14  student_time_in_course                            2332 non-null   object
 15  avg_time_per_user                                 2332 non-null   object
 16  total_items                                       2332 non-null   int64
 17  total_logins                                      2332 non-null   int64
 18  std_act_assignments                               2332 non-null   float64
 19  std_act_learning_materials                        2332 non-null   float64
 20  std_act_module_information_handbook               2332 non-null   float64
 21  std_act_reading_list                              2332 non-null   float64
 22  std_act_week1                                     2332 non-null   float64
 23  std_act_week2                                     2332 non-null   float64
 24  no_of_times_accessed_assignments                  2332 non-null   int64
 25  no_of_times_accessed_learning_materials           2332 non-null   int64
 26  no_of_times_accessed_module_information_handbook  2332 non-null   int64
 27  no_of_times_accessed_reading_list                 2332 non-null   int64
 28  no_of_times_week1                                 2332 non-null   int64
 29  no_of_times_week2                                 2332 non-null   int64
 30  initial_access_assignments                        2332 non-null   object
 31  initial_access_learning_materials                 2332 non-null   object
 32  initial_access_information_handbook               2332 non-null   object
 33  initial_access_reading_list                       2332 non-null   object
 34  initial_access_week1                              2332 non-null   object
 35  initial_access_week2                              2332 non-null   object
 36  main_week                                         2332 non-null   object
 37  std_act_week3                                     2332 non-null   object
 38  no_of_times_week3                                 2332 non-null   object
 39  initial_access_week3                              2332 non-null   object
 40  std_act_df5                                       2332 non-null   object
 41  no_of_times_week4                                 2332 non-null   object
 42  initial_access_week4                              2332 non-null   object
 43  std_act_week4                                     2332 non-null   object
 44  std_act_week5                                     2332 non-null   object
 45  std_act_week6                                     2332 non-null   object
 46  std_act_week7                                     2332 non-null   object
 47  no_of_times_week5                                 2332 non-null   object
 48  no_of_times_week6                                 2332 non-null   object
 49  no_of_times_week7                                 2332 non-null   object
 50  initial_access_week5                              2332 non-null   object
 51  initial_access_week6                              2332 non-null   object
 52  initial_access_week7                              2332 non-null   object
 53  std_act_week8                                     2332 non-null   object
 54  no_of_times_week8                                 2332 non-null   object
 55  initial_access_week8                              2332 non-null   object
 56  std_act_week9                                     2332 non-null   object
 57  no_of_times_week9                                 2332 non-null   object
 58  initial_access_week9                              2332 non-null   object
 59  std_act_week10                                    2332 non-null   object
 60  no_of_times_week10                                2332 non-null   object
 61  initial_access_week10                             2332 non-null   object
 62  std_act_week_11_feedback                          2332 non-null   object
 63  no_of_times_week11_feedback                       2332 non-null   object
 64  initial_access_week11_feedback                    2332 non-null   object
dtypes: float64(14), int64(10), object(41)
memory usage: 1.2+ MB

In [40]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2332 entries, 0 to 2331
Data columns (total 65 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   total_marks                                       2332 non-null   float64
 1   list_of_countries                                 2332 non-null   object
 2   what_is_your_year_of_birth_just_the_year          2332 non-null   int64
 3   how_do_you_describe_yourself___selected_choice    2332 non-null   object
 4   what_is_your_first_degree_subject_area            2332 non-null   object
 5   student_id                                        2332 non-null   int64
 6   date_range                                        2332 non-null   object
 7   monday                                            2332 non-null   float64
 8   tuesday                                           2332 non-null   float64
 9   wednesday                                         2332 non-null   float64
 10  thursday                                          2332 non-null   float64
 11  friday                                            2332 non-null   float64
 12  saturday                                          2332 non-null   float64
 13  sunday                                            2332 non-null   float64
 14  student_time_in_course                            2332 non-null   object
 15  avg_time_per_user                                 2332 non-null   object
 16  total_items                                       2332 non-null   int64
 17  total_logins                                      2332 non-null   int64
 18  std_act_assignments                               2332 non-null   float64
 19  std_act_learning_materials                        2332 non-null   float64
 20  std_act_module_information_handbook               2332 non-null   float64
 21  std_act_reading_list                              2332 non-null   float64
 22  std_act_week1                                     2332 non-null   float64
 23  std_act_week2                                     2332 non-null   float64
 24  no_of_times_accessed_assignments                  2332 non-null   int64
 25  no_of_times_accessed_learning_materials           2332 non-null   int64
 26  no_of_times_accessed_module_information_handbook  2332 non-null   int64
 27  no_of_times_accessed_reading_list                 2332 non-null   int64
 28  no_of_times_week1                                 2332 non-null   int64
 29  no_of_times_week2                                 2332 non-null   int64
 30  initial_access_assignments                        2332 non-null   object
 31  initial_access_learning_materials                 2332 non-null   object
 32  initial_access_information_handbook               2332 non-null   object
 33  initial_access_reading_list                       2332 non-null   object
 34  initial_access_week1                              2332 non-null   object
 35  initial_access_week2                              2332 non-null   object
 36  main_week                                         2332 non-null   object
 37  std_act_week3                                     2332 non-null   object
 38  no_of_times_week3                                 2332 non-null   object
 39  initial_access_week3                              2332 non-null   object
 40  std_act_df5                                       2332 non-null   object
 41  no_of_times_week4                                 2332 non-null   object
 42  initial_access_week4                              2332 non-null   object
 43  std_act_week4                                     2332 non-null   object
 44  std_act_week5                                     2332 non-null   object
 45  std_act_week6                                     2332 non-null   object
 46  std_act_week7                                     2332 non-null   object
 47  no_of_times_week5                                 2332 non-null   object
 48  no_of_times_week6                                 2332 non-null   object
 49  no_of_times_week7                                 2332 non-null   object
 50  initial_access_week5                              2332 non-null   object
 51  initial_access_week6                              2332 non-null   object
 52  initial_access_week7                              2332 non-null   object
 53  std_act_week8                                     2332 non-null   object
 54  no_of_times_week8                                 2332 non-null   object
 55  initial_access_week8                              2332 non-null   object
 56  std_act_week9                                     2332 non-null   object
 57  no_of_times_week9                                 2332 non-null   object
 58  initial_access_week9                              2332 non-null   object
 59  std_act_week10                                    2332 non-null   object
 60  no_of_times_week10                                2332 non-null   object
 61  initial_access_week10                             2332 non-null   object
 62  std_act_week_11_feedback                          2332 non-null   object
 63  no_of_times_week11_feedback                       2332 non-null   object
 64  initial_access_week11_feedback                    2332 non-null   object
dtypes: float64(14), int64(10), object(41)
memory usage: 1.2+ MB

In [41]:
merged_df

,total_marks,list_of_countries,what_is_your_year_of_birth_just_the_year,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range,monday,tuesday,wednesday,...,initial_access_week8,std_act_week9,no_of_times_week9,initial_access_week9,std_act_week10,no_of_times_week10,initial_access_week10,std_act_week_11_feedback,no_of_times_week11_feedback,initial_access_week11_feedback
0,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",1,03/10/22 - 09/10/22,0.000000,0.005278,0.014722,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
1,70.0,Nigeria,1996,Male,CAH07-02\tChemistry,2,03/10/22 - 09/10/22,0.000000,3.117500,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
2,65.0,Nigeria,1990,Female,CAH15-02\tEconomics,3,03/10/22 - 09/10/22,0.019722,1.710833,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
3,55.0,Nigeria,1991,Male,CAH15-02\tEconomics,4,03/10/22 - 09/10/22,0.001667,0.018055,0.000000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
4,65.0,Pakistan,1998,Male,CAH17-01\tBusiness and management,5,03/10/22 - 09/10/22,0.000000,2.232222,0.052778,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2327,60.4,India,1992,Male,CAH19-01\tEnglish studies,208,11/12/23 - 17/12/23,0.000000,0.000000,0.301667,...,NA,0.0,0,NA,0.0,0,NA,0.0,0.0,NA
2328,64.0,Bangladesh,1996,Female,CAH17-01\tBusiness and management,209,11/12/23 - 17/12/23,0.000000,0.017778,0.022778,...,NA,0.0,0,NA,0.0,0,NA,0.013612,1.0,2023-12-12 14:30:47.321000
2329,73.0,Sri Lanka,1996,Female,CAH11-01\tComputing,210,11/12/23 - 17/12/23,3.059722,2.752778,0.000000,...,NA,0.0,0,NA,0.0,0,NA,0.014445,1.0,2023-12-12 14:16:13.475000
2330,61.8,Myanmar,1998,Female,CAH11-01\tComputing,211,11/12/23 - 17/12/23,0.016667,0.113888,0.000000,...,NA,0.0,0,NA,0.0,0,NA,0.008888,4.0,2023-12-11 20:07:31.608000
2331,63.0,United States of America,2001,Male,CAH11-01\tComputing,212,11/12/23 - 17/12/23,0.000000,1.459445,0.000000,...,NA,0.0,0,NA,0.0,0,NA,0.251388,1.0,2023-12-12 14:17:38.059000

In [44]:
df_cate = merged_df.select_dtypes(include=['object'])
df_num = merged_df.select_dtypes(include=['number'])
df_cate

,list_of_countries,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,date_range,student_time_in_course,avg_time_per_user,initial_access_assignments,initial_access_learning_materials,initial_access_information_handbook,initial_access_reading_list,...,initial_access_week8,std_act_week9,no_of_times_week9,initial_access_week9,std_act_week10,no_of_times_week10,initial_access_week10,std_act_week_11_feedback,no_of_times_week11_feedback,initial_access_week11_feedback
0,Nigeria,Male,"CAH13-01\tArchitecture, building and planning",03/10/22 - 09/10/22,00:02:37,01:19:38,NA,2022-10-04 15:45:00.718000,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
1,Nigeria,Male,CAH07-02\tChemistry,03/10/22 - 09/10/22,03:07:03,01:19:38,NA,2022-10-04 15:48:30.421000,2022-10-04 14:02:11.582000,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
2,Nigeria,Female,CAH15-02\tEconomics,03/10/22 - 09/10/22,01:43:50,01:19:38,NA,2022-10-04 14:05:35.288000,2022-10-03 21:49:58.608000,2022-10-04 14:01:58.086000,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
3,Nigeria,Male,CAH15-02\tEconomics,03/10/22 - 09/10/22,00:01:11,01:19:38,NA,2022-10-03 11:15:47.910000,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
4,Pakistan,Male,CAH17-01\tBusiness and management,03/10/22 - 09/10/22,02:17:06,01:19:38,NA,2022-10-04 15:49:31.924000,2022-10-05 17:49:47.691000,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2327,India,Male,CAH19-01\tEnglish studies,11/12/23 - 17/12/23,00:18:50,00:43:49,2023-12-13 20:32:19.084000,NA,NA,NA,...,NA,0.0,0,NA,0.0,0,NA,0.0,0.0,NA
2328,Bangladesh,Female,CAH17-01\tBusiness and management,11/12/23 - 17/12/23,00:02:26,00:43:49,2023-12-12 14:31:36.570000,2023-12-12 14:30:43.095000,NA,NA,...,NA,0.0,0,NA,0.0,0,NA,0.013612,1.0,2023-12-12 14:30:47.321000
2329,Sri Lanka,Female,CAH11-01\tComputing,11/12/23 - 17/12/23,05:48:45,00:43:49,2023-12-11 17:20:00.518000,2023-12-12 14:13:06.800000,NA,2023-12-11 17:19:58.522000,...,NA,0.0,0,NA,0.0,0,NA,0.014445,1.0,2023-12-12 14:16:13.475000
2330,Myanmar,Female,CAH11-01\tComputing,11/12/23 - 17/12/23,00:07:56,00:43:49,2023-12-16 13:08:03.264000,2023-12-11 20:07:19.576000,NA,NA,...,NA,0.0,0,NA,0.0,0,NA,0.008888,4.0,2023-12-11 20:07:31.608000
2331,United States of America,Male,CAH11-01\tComputing,11/12/23 - 17/12/23,01:27:34,00:43:49,NA,2023-12-12 14:17:35.205000,NA,NA,...,NA,0.0,0,NA,0.0,0,NA,0.251388,1.0,2023-12-12 14:17:38.059000

In [45]:
df_cate.drop(columns=['date_range','avg_time_per_user','initial_access_learning_materials',
                      'initial_access_information_handbook','initial_access_reading_list','initial_access_week1','initial_access_week2','initial_access_week5','initial_access_week7', 
                      'initial_access_week8','std_act_week9','no_of_times_week9','initial_access_week9','initial_access_week10','initial_access_week11_feedback'], inplace=True)

In [46]:
df_cate = df_cate[['list_of_countries','how_do_you_describe_yourself___selected_choice','what_is_your_first_degree_subject_area']]
cols = list(df_cate.columns)

In [50]:

def cat_num(col):
    for i in col:
        df_cate[i]= pd.get_dummies(df_cate[i], drop_first=True)
        
cat_num(col = cols)

ValueError: Columns must be same length as key

In [ ]:
def time_to_seconds(time_str):
    try:
        h, m, s = map(int, time_str.split(':'))
        return h * 3600 + m * 60 + s
    except:
        return 0

merged_df['student_time_in_course'] = merged_df['student_time_in_course'].apply(time_to_seconds)
merged_df['avg_time_per_user'] = merged_df['avg_time_per_user'].apply(time_to_seconds)

# Step 2: Convert object columns that should be numeric
numeric_object_cols = [
    'no_of_times_accessed_reading_list', 'no_of_times_week3', 'no_of_times_week4',
    'no_of_times_week5', 'no_of_times_week6', 'no_of_times_week7', 'no_of_times_week8',
    'no_of_times_week9', 'no_of_times_week10', 'no_of_times_week11_feedback',
    'std_act_week3', 'std_act_week4', 'std_act_week5', 'std_act_week6', 'std_act_week7',
    'std_act_week8', 'std_act_week9', 'std_act_week10', 'std_act_week_11_feedback', 'std_act_df5'
]
for col in numeric_object_cols:
    merged_df[col] = pd.to_numeric(merged_df[col], errors='coerce').fillna(0)

# Step 3: Convert initial_access_* to binary (1 if accessed, 0 if NA)
initial_access_cols = [col for col in merged_df.columns if 'initial_access' in col]
for col in initial_access_cols:
    merged_df[col] = merged_df[col].apply(lambda x: 0 if x == 'NA' else 1)

# Step 4: Select numeric columns for correlation
numeric_cols = merged_df.select_dtypes(include=['float64', 'int64']).columns.tolist()
if 'total_marks' not in numeric_cols:
    numeric_cols.append('total_marks')  # Ensure target is included
else:
    numeric_cols = [col for col in numeric_cols if col != 'student_id']  # Exclude student_id

# Step 5: Compute correlation with total_marks
correlations = merged_df[numeric_cols].corr()['total_marks'].sort_values(key=abs, ascending=False)

# Step 6: Display top correlated columns
print("Top 10 Columns Most Correlated with total_marks:")
print(correlations.head(11))  # Including total_marks itself (corr=1)

Top 10 Columns Most Correlated with total_marks:
total_marks                                         1.000000
tuesday                                             0.136714
initial_access_learning_materials                   0.114851
student_time_in_course                              0.105479
total_items                                         0.102897
no_of_times_accessed_module_information_handbook    0.083994
total_logins                                        0.075542
initial_access_week4                                0.075348
no_of_times_accessed_learning_materials             0.074068
std_act_week5                                       0.069746
initial_access_information_handbook                 0.065413
Name: total_marks, dtype: float64