In [1]:
#importing libraries
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as matplot
import re
import logging
import os

In [ ]:
#reading excel with multiple sheets and selecting a specific sheet
xls = pd.ExcelFile('csv_data/data1.xlsx')
demo_df = pd.read_excel(xls,'Demographics',skiprows=1)
demo_df

,"Performance Analytics in Data Science Teams \n\n\n\nThank you in advance for taking the time to read this information and considering your participation in this study.\n\nPlease ensure that you have read and understood the information contained in the Participant Information Sheet and asked any questions before you sign this form. If you have any questions please contact a member of the research team, whose details are set out on the Participant Information Sheet.\n\nPlease confirm\n\n\n\t\n\t\t\n\t\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\tI have read and understood the information in the Participant Information Sheet \n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\n\t\t\n\t\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\tI am aware of what my participation will involve and the data collected will remain confidential and no information that identifies me will be made publicly available.\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\n\t\t\n\t\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\tI understand that my participation is voluntary, is not connected to my assessment and that I am free to withdraw from the study at any time, without having to give a reason and without consequences;",List of Countries,"What is your year of birth (Just the year, e.g. 1995) ?",How do you describe yourself? - Selected Choice,How do you describe yourself? - Prefer to self-describe - Text,What is your first degree subject area?,How many years work experience do you have?,What sectors have you worked in?,Previous experiences of team working in study and work,"Based on experience or feeling, my expectations for this module are that: - I will enjoy working in the team",...,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 7. Because it is something that I have to do,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 8. I am doing this module but I am not sure if it is worth it,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 9. Because this module looks fun,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 10. By personal decision,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 11. Because I don’t have any choice,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 12. I don’t know; I don’t see what this module brings me,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 13. Because I feel good about this module,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 14. Because I believe that this module is important for me,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 15. Because I feel that I have to do it,"Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 16. I am doing this module, but I am not sure it is a good thing to pursue it"
0,1,Nigeria,1996,Male,NaN,"CAH13-01\tArchitecture, building and planning",5,"CONSTRUCTION,REAL ESTATE ACTIVITIES",I have some experience,Strongly agree,...,Exactly,Enough,Exactly,Exactly,Not At All,Moderately,Exactly,Exactly,Exactly,A Little
1,2,Nigeria,1996,Male,NaN,CAH07-02\tChemistry,3,INFORMATION AND COMMUNICATION,I have extensive experience of teamworking,Strongly agree,...,Exactly,Not At All,A Little,Not At All,Moderately,Not At All,Enough,A Lot,Moderately,Not At All
2,3,Nigeria,1990,Female,NaN,CAH15-02\tEconomics,2,"ARTS, ENTERTAINMENT AND RECREATION",I have some experience,Somewhat agree,...,Moderately,Not At All,Moderately,A Lot,Not At All,Not At All,Moderately,A Lot,Moderately,Not At All
3,4,Nigeria,1991,Male,NaN,CAH15-02\tEconomics,6,"INFORMATION AND COMMUNICATION,ADMINISTRATIVE A...",I have experience of teamworking and have also...,Strongly agree,...,Not At All,Not At All,Exactly,Exactly,Not At All,Not At All,Exactly,Exactly,Moderately,Not At All
4,5,Pakistan,1998,Male,NaN,CAH17-01\tBusiness and management,0,NaN,I have some experience,Neither agree nor disagree,...,A Very Little,A Little,Enough,Moderately,Moderately,Moderately,Moderately,Moderately,Moderately,Moderately
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,208,India,1992,Male,NaN,CAH19-01\tEnglish studies,10,"FINANCIAL AND INSURANCE ACTIVITIES,HUMAN HEALT...",I have experience of teamworking and have also...,Strongly agree,...,Exactly,A Lot,Exactly,Enough,Not At All,Not At All,A Lot,Exactly,Enough,Not At All
208,209,Bangladesh,1996,Female,NaN,CAH17-01\tBusiness and management,4,FINANCIAL AND INSURANCE ACTIVITIES,I have extensive experience of teamworking,Somewhat agree,...,A Very Little,A Very Little,Moderately,A Lot,Not At All,A Very Little,Enough,Exactly,Exactly,Not At All
209,210,Sri Lanka,1996,Female,NaN,CAH11-01\tComputing,1,"PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES",I have some experience,Somewhat disagree,...,A Little,A Little,A Little,A Little,A Little,A Little,A Little,A Little,A Little,A Little
210,211,Myanmar,1998,Female,NaN,CAH11-01\tComputing,1,OTHER SERVICE ACTIVITIES,I have extensive experience of teamworking,Strongly agree,...,Exactly,Not At All,A Lot,Exactly,Not At All,Not At All,A Lot,Exactly,A Lot,Not At All
211,212,United States of America,2001,Male,NaN,CAH11-01\tComputing,2,"INFORMATION AND COMMUNICATION,FINANCIAL AND IN...",I have experience of teamworking and have also...,Somewhat agree,...,Not At All,Not At All,Moderately,Exactly,Not At All,Not At All,Enough,Exactly,Enough,Not At All

In [ ]:
#reading excel with multiple sheets and selecting a specific sheet
xls = pd.ExcelFile('csv_data/data1.xlsx')
demo_df_numeric = pd.read_excel(xls,'Numeric Demographic',skiprows=1)
demo_df_numeric

,ID,List of Countries,"What is your year of birth (Just the year, e.g. 1995) ?",How do you describe yourself? - Selected Choice,How do you describe yourself? - Prefer to self-describe - Text,What is your first degree subject area?,How many years work experience do you have?,What sectors have you worked in?,Previous experiences of team working in study and work,"Based on experience or feeling, my expectations for this module are that: - I will enjoy working in the team",...,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 7. Because it is something that I have to do,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 8. I am doing this module but I am not sure if it is worth it,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 9. Because this module looks fun,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 10. By personal decision,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 11. Because I don’t have any choice,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 12. I don’t know; I don’t see what this module brings me,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 13. Because I feel good about this module,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 14. Because I believe that this module is important for me,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 15. Because I feel that I have to do it,"Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 16. I am doing this module, but I am not sure it is a good thing to pursue it"
0,1,126,1996,1,NaN,18.0,5.0,"6,12",2.0,5.0,...,7.0,5.0,7.0,7.0,1.0,4.0,7.0,7.0,7.0,3.0
1,2,126,1996,1,NaN,12.0,3.0,10,3.0,5.0,...,7.0,1.0,3.0,1.0,4.0,1.0,5.0,6.0,4.0,1.0
2,3,126,1990,2,NaN,20.0,2.0,18,2.0,4.0,...,4.0,1.0,4.0,6.0,1.0,1.0,4.0,6.0,4.0,1.0
3,4,126,1991,1,NaN,20.0,6.0,"10,14",4.0,5.0,...,1.0,1.0,7.0,7.0,1.0,1.0,7.0,7.0,4.0,1.0
4,5,130,1998,1,NaN,24.0,0.0,NaN,2.0,3.0,...,2.0,3.0,5.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,208,78,1992,1,NaN,25.0,10.0,"11,17",4.0,5.0,...,7.0,6.0,7.0,5.0,1.0,1.0,6.0,7.0,5.0,1.0
208,209,14,1996,2,NaN,24.0,4.0,11,3.0,4.0,...,2.0,2.0,4.0,6.0,1.0,2.0,5.0,7.0,7.0,1.0
209,210,164,1996,2,NaN,17.0,1.0,13,2.0,2.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
210,211,118,1998,2,NaN,17.0,1.0,19,3.0,5.0,...,7.0,1.0,6.0,7.0,1.0,1.0,6.0,7.0,6.0,1.0
211,212,187,2001,1,NaN,17.0,2.0,"10,11,17,19",4.0,4.0,...,1.0,1.0,4.0,7.0,1.0,1.0,5.0,7.0,5.0,1.0

In [4]:
#reading excel with multiple sheets and selecting a specific sheet
xls = pd.ExcelFile('csv_data/data1.xlsx')
Retro_numeric = pd.read_excel(xls,'Retro numeric',skiprows=1)
Retro_numeric

,"Please enter your student ID\n\nWe will use this to connect your data together, but will not share it or use it to identify you personally beyond the end of the study",Please reflect on your team's performance in the module - I really enjoyed working in the team,Please reflect on your team's performance in the module - Team communication was highly effective,Please reflect on your team's performance in the module - Team communication was very frequent,Please reflect on your team's performance in the module - We bonded personally as well as professionally,Please reflect on your team's performance in the module - We tended to collaborate together on the same tasks,Please reflect on your team's performance in the module - We tended to work on separate tasks and link them together later on,Please reflect on your team's performance in the module - I feel I have developed my professional skills as a result of the team project,Please reflect on your team's performance in the module - I feel I have developed my team working skills and my approach to collaboration as a result of the team project,Please reflect on your team's performance in the module - We adjusted the project regularly as we went along,Please reflect on your team's performance in the module - We stuck to our original project plan,"Please reflect on your team's performance in the module - Overall, I am pleased with our end result",Please add some further comments about things that you felt went well,Please add some further comments about things you felt did not go well or that the team could have done better,"On average over the term, how many hours per week outside of the timetabled classes do you think you spent on the project?"
0,3,4.0,4.0,4.0,3.0,3.0,4.0,4.0,4.0,4.0,5.0,5.0,Our supervisor was fantastic.,Not everyone on the team collaborated fully.,10.0
1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,3.0,4.0,5.0,2.0,2.0,5.0,5.0,5.0,4.0,4.0,3.0,Some team members were very involved in the wo...,Some members of the team frequently missed tea...,10.0
3,7,5.0,4.0,4.0,4.0,4.0,5.0,5.0,5.0,5.0,1.0,4.0,The zeal to work in meeting deadlines of submi...,100% Communication was not contributed by all ...,8.0
4,8,4.0,4.0,4.0,2.0,4.0,4.0,3.0,4.0,4.0,3.0,4.0,NaN,NaN,5.0
5,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,14,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,4.0,5.0,5.0,Team collaboration was perfect.,We could attend online meetings instead of off...,6.0
7,18,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,The team showed concerns in one another's pers...,I felt the team could have showed even much be...,6.0
8,22,4.0,4.0,4.0,4.0,5.0,5.0,4.0,5.0,4.0,4.0,4.0,We worked quite well together on trying to get...,One of the group members did not show up at al...,3.0
9,24,5.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,5.0,3.0,5.0,"I feel we were able to worked well as a team, ...",I would have been helpful if our initial surve...,10.0
10,27,4.0,5.0,4.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,NaN,NaN,10.0
11,33,5.0,4.0,4.0,5.0,4.0,4.0,4.0,4.0,5.0,3.0,5.0,I ALSO UNDERSTAND MY WEAKNESS AND STRENGTH,OUR ORIGINAL PROJECT WAS CHANGED AS ARESULT OF...,4.0
12,34,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,All went very nicely and smoothly,Time consuming,15.0
13,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,55,5.0,5.0,5.0,5.0,5.0,4.0,5.0,5.0,4.0,5.0,5.0,We worked well in our group and there was cons...,what the team could have done better is by kee...,14.0
16,58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,60,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,NaN,NaN,3.0
19,61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,67,4.0,4.0,4.0,4.0,4.0,5.0,5.0,5.0,2.0,5.0,5.0,we were stick to original problem and outcome.,"if we would have invloved more ,the result we ...",4.0
22,68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,70,4.0,5.0,5.0,4.0,4.0,3.0,4.0,4.0,5.0,3.0,5.0,"Although we had our differences, the team real...","Well, being from different backgrounds came wi...",4.0
24,71,4.0,4.0,4.0,4.0,3.0,5.0,5.0,5.0,5.0,5.0,5.0,NaN,NaN,8.0
25,74,5.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,1.0,5.0,Team members prompt response to change all thr...,Nothing yet,14.0
26,75,5.0,5.0,5.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,Effective communication and teamwork,"We could have done better, if other team membe...",2.0
27,78,2.0,3.0,4.0,4.0,2.0,4.0,4.0,4.0,2.0,3.0,3.0,gave me an opportunity to learn more about the...,module is bias towards people with data scienc...,10.0
28,81,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,3.0,5.0,It was great experience working in team,data was not available but we managed,10.0
29,83,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,i'm not happy with the project work at all,the fact that everyones grade in the team has ...,42.0
30,86,5.0,3.0,3.0,5.0,5.0,5.0,5.0,5.0,4.0,5.0,5.0,I learned about about open banking which I nev...,Our project management was a disaster. We were...,1.5
31,89,3.0,3.0,2.0,4.0,4.0,5.0,5.0,5.0,3.0,2.0,5.0,The things I felt went well is even the collab...,Somehow I felt that the team are just complain...,40.0
32,97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,109,5.0,5.0,4.0,3.0,4.0,4.0,5.0,5.0,4.0,3.0,5.0,NaN,NaN,5.0

In [3]:
#reading excel with multiple sheets and selecting a specific sheetx
ls = pd.ExcelFile('csv_data/data1.xlsx')
Retrospective = pd.read_excel(xls,'Retrospective',skiprows=1)
Retrospective

NameError: name 'xls' is not defined

In [ ]:
Please reflect on your team's performance in the module - I really enjoyed working in the team

In [16]:
# renaming columns with spaces and special characters
week1_democo2 = pd.read_excel(xls,'Week 1',skiprows=1)
week1_democo2.columns=week1_democo2.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
week1_democo2 =week1_democo2.iloc[:, 4:]
df = week1_democo2

for i in enumerate(df):
    print(i)

(0, 'unnamed_4')
(1, 'list_of_countries')
(2, 'what_is_your_year_of_birth_just_the_year_eg_1995_')
(3, 'how_do_you_describe_yourself___selected_choice')
(4, 'what_is_your_first_degree_subject_area')
(5, 'student_id')
(6, 'date_range__week_1')
(7, 'monday')
(8, 'tuesday')
(9, 'wednesday')
(10, 'thursday')
(11, 'friday')
(12, 'saturday')
(13, 'sunday')
(14, 'student_time_in_course')
(15, 'avg_time_per_user')
(16, 'total_items')
(17, 'total_logins')
(18, 'assignments')
(19, 'learning_materials')
(20, 'module_information_handbook')
(21, 'reading_list')
(22, 'week_1')
(23, 'week_2')
(24, 'assignments1')
(25, 'learning_materials1')
(26, 'module_information_handbook')
(27, 'reading_list1')
(28, 'week_11')
(29, 'week_21')
(30, 'assignments2')
(31, 'learning_materials2')
(32, 'module_information_handbook1')
(33, 'reading_list2')
(34, 'week_12')
(35, 'week_22')
(36, 'unnamed_40')

In [ ]:
df.columns.val

In [14]:
# renaming columns with duplicate names
df.columns.values[0] = 'total_marks'
df.columns.values[18] = 'std_act_assignments'
df.columns.values[19] = 'std_act_learning_materials'
df.columns.values[20] = 'std_act_module_information_handbook1'
df.columns.values[21] = 'std_act_reading_list'
df.columns.values[22] = 'std_act_week1'
df.columns.values[23] = 'std_act_week2'
df.columns.values[24] = 'no_of_times_accessed_assignments'
df.columns.values[25] = 'no_of_times_accessed_learning_materials'
df.columns.values[26] = 'no_of_times_accessed_module_information_handbook1'
df.columns.values[27] = 'no_of_times_accessedreading_list'
df.columns.values[28] = 'no_of_times_week1'
df.columns.values[29] = 'no_of_times_week2'
df.columns.values[30] = 'initial_access_assignments'
df.columns.values[31] = 'initial_access_learning_materials'
df.columns.values[32] = 'initial_access_information_handbook1'
df.columns.values[33] = 'initial_access_reading_list'
df.columns.values[34] = 'initial_access_week1'
df.columns.values[35] = 'initial_access_week2'

In [17]:
df

,unnamed_4,list_of_countries,what_is_your_year_of_birth_just_the_year_eg_1995_,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range__week_1,monday,tuesday,wednesday,...,reading_list1,week_11,week_21,assignments2,learning_materials2,module_information_handbook1,reading_list2,week_12,week_22,unnamed_40
0,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",1,03/10/22 - 09/10/22,0.000000,0.005278,0.014722,...,0,2,0,NaN,2022-10-04 15:45:00.718,NaT,NaT,2022-10-04 15:45:03.544,NaT,NaT
1,70.0,Nigeria,1996,Male,CAH07-02\tChemistry,2,03/10/22 - 09/10/22,0.000000,3.117500,0.000000,...,0,2,0,NaN,2022-10-04 15:48:30.421,2022-10-04 14:02:11.582,NaT,2022-10-04 15:48:38.726,NaT,NaT
2,65.0,Nigeria,1990,Female,CAH15-02\tEconomics,3,03/10/22 - 09/10/22,0.019722,1.710833,0.000000,...,2,4,0,NaN,2022-10-04 14:05:35.288,2022-10-03 21:49:58.608,2022-10-04 14:01:58.086,2022-10-04 14:05:37.424,NaT,NaT
3,55.0,Nigeria,1991,Male,CAH15-02\tEconomics,4,03/10/22 - 09/10/22,0.001667,0.018055,0.000000,...,0,2,0,NaN,2022-10-03 11:15:47.910,NaT,NaT,2022-10-03 11:15:50.346,NaT,NaT
4,65.0,Pakistan,1998,Male,CAH17-01\tBusiness and management,5,03/10/22 - 09/10/22,0.000000,2.232222,0.052778,...,0,2,0,NaN,2022-10-04 15:49:31.924,2022-10-05 17:49:47.691,NaT,2022-10-04 15:49:38.697,NaT,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,60.4,India,1992,Male,CAH19-01\tEnglish studies,208,02/10/23 - 08/10/23,0.000000,2.428612,0.000000,...,1,2,0,NaN,2023-10-03 11:47:50.171,NaT,2023-10-03 11:48:03.025,2023-10-03 11:47:55.897,NaT,NaT
208,64.0,Bangladesh,1996,Female,CAH17-01\tBusiness and management,209,02/10/23 - 08/10/23,0.759445,2.084722,0.000000,...,4,8,0,NaN,2023-10-02 22:59:12.332,NaT,2023-10-02 23:02:02.141,2023-10-02 22:59:16.144,NaT,NaT
209,73.0,Sri Lanka,1996,Female,CAH11-01\tComputing,210,02/10/23 - 08/10/23,0.020000,0.699445,0.000000,...,1,1,0,NaN,2023-10-03 15:06:40.247,NaT,2023-10-03 15:06:42.334,2023-10-03 15:07:15.788,NaT,NaT
210,61.8,Myanmar,1998,Female,CAH11-01\tComputing,211,02/10/23 - 08/10/23,2.346667,1.959722,0.024445,...,5,3,0,NaN,2023-10-02 22:53:45.622,NaT,2023-10-03 00:37:55.125,2023-10-02 22:53:48.748,NaT,NaT
211,63.0,United States of America,2001,Male,CAH11-01\tComputing,212,02/10/23 - 08/10/23,0.000000,0.002778,0.000000,...,0,1,0,NaN,2023-10-03 14:20:54.595,NaT,NaT,2023-10-03 14:20:57.278,NaT,NaT

In [15]:
#bringing first week from columns into the rows
try:
  df = pd.melt(df, id_vars=['total_marks', 'list_of_countries',
       'what_is_your_year_of_birth_just_the_year_eg_1995_',
       'how_do_you_describe_yourself___selected_choice',
       'what_is_your_first_degree_subject_area', 'student_id',
       'date_range__week_1', 'monday', 'tuesday', 'wednesday', 'thursday',
       'friday', 'saturday', 'sunday', 'student_time_in_course',
       'avg_time_per_user', 'total_items', 'total_logins',
       'std_act_assignments', 'std_act_learning_materials',
       'std_act_module_information_handbook1', 'std_act_reading_list',
       'no_of_times_accessed_assignments',
       'no_of_times_accessed_learning_materials',
       'no_of_times_accessed_module_information_handbook1',
       'no_of_times_accessedreading_list', 'no_of_times_week1',
       'no_of_times_week2', 'initial_access_assignments',
       'initial_access_learning_materials',
       'initial_access_information_handbook1', 'initial_access_reading_list',
       'initial_access_week1', 'initial_access_week2', 'unnamed_40'
      ],
          value_vars=['std_act_week1', 'std_act_week2'], var_name='week', value_name='hours_spent')
except Exception as e:
  print("Error in melting the DataFrame:", e)
  raise

In [10]:
df

,total_marks,list_of_countries,what_is_your_year_of_birth_just_the_year_eg_1995_,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range__week_1,monday,tuesday,wednesday,...,no_of_times_week2,initial_access_assignments,initial_access_learning_materials,initial_access_information_handbook1,initial_access_reading_list,initial_access_week1,initial_access_week2,unnamed_40,std_act_Week,hours_spent
0,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",1,03/10/22 - 09/10/22,0.000000,0.005278,0.014722,...,0,NaN,2022-10-04 15:45:00.718,NaT,NaT,2022-10-04 15:45:03.544,NaT,NaT,std_act_week1,0.016388
1,70.0,Nigeria,1996,Male,CAH07-02\tChemistry,2,03/10/22 - 09/10/22,0.000000,3.117500,0.000000,...,0,NaN,2022-10-04 15:48:30.421,2022-10-04 14:02:11.582,NaT,2022-10-04 15:48:38.726,NaT,NaT,std_act_week1,1.330555
2,65.0,Nigeria,1990,Female,CAH15-02\tEconomics,3,03/10/22 - 09/10/22,0.019722,1.710833,0.000000,...,0,NaN,2022-10-04 14:05:35.288,2022-10-03 21:49:58.608,2022-10-04 14:01:58.086,2022-10-04 14:05:37.424,NaT,NaT,std_act_week1,1.628055
3,55.0,Nigeria,1991,Male,CAH15-02\tEconomics,4,03/10/22 - 09/10/22,0.001667,0.018055,0.000000,...,0,NaN,2022-10-03 11:15:47.910,NaT,NaT,2022-10-03 11:15:50.346,NaT,NaT,std_act_week1,0.000000
4,65.0,Pakistan,1998,Male,CAH17-01\tBusiness and management,5,03/10/22 - 09/10/22,0.000000,2.232222,0.052778,...,0,NaN,2022-10-04 15:49:31.924,2022-10-05 17:49:47.691,NaT,2022-10-04 15:49:38.697,NaT,NaT,std_act_week1,2.241667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419,60.4,India,1992,Male,CAH19-01\tEnglish studies,208,02/10/23 - 08/10/23,0.000000,2.428612,0.000000,...,0,NaN,2023-10-03 11:47:50.171,NaT,2023-10-03 11:48:03.025,2023-10-03 11:47:55.897,NaT,NaT,std_act_week2,0.000000
420,64.0,Bangladesh,1996,Female,CAH17-01\tBusiness and management,209,02/10/23 - 08/10/23,0.759445,2.084722,0.000000,...,0,NaN,2023-10-02 22:59:12.332,NaT,2023-10-02 23:02:02.141,2023-10-02 22:59:16.144,NaT,NaT,std_act_week2,0.000000
421,73.0,Sri Lanka,1996,Female,CAH11-01\tComputing,210,02/10/23 - 08/10/23,0.020000,0.699445,0.000000,...,0,NaN,2023-10-03 15:06:40.247,NaT,2023-10-03 15:06:42.334,2023-10-03 15:07:15.788,NaT,NaT,std_act_week2,0.000000
422,61.8,Myanmar,1998,Female,CAH11-01\tComputing,211,02/10/23 - 08/10/23,2.346667,1.959722,0.024445,...,0,NaN,2023-10-02 22:53:45.622,NaT,2023-10-03 00:37:55.125,2023-10-02 22:53:48.748,NaT,NaT,std_act_week2,0.000000
423,63.0,United States of America,2001,Male,CAH11-01\tComputing,212,02/10/23 - 08/10/23,0.000000,0.002778,0.000000,...,0,NaN,2023-10-03 14:20:54.595,NaT,NaT,2023-10-03 14:20:57.278,NaT,NaT,std_act_week2,0.000000

In [331]:
#bringing first week from columns into the rows
try:
  df = pd.melt(df, id_vars=['total_marks', 'list_of_countries',
       'what_is_your_year_of_birth_just_the_year_eg_1995_',
       'how_do_you_describe_yourself___selected_choice',
       'what_is_your_first_degree_subject_area', 'student_id',
       'date_range__week_1', 'monday', 'tuesday', 'wednesday', 'thursday',
       'friday', 'saturday', 'sunday', 'student_time_in_course',
       'avg_time_per_user', 'total_items', 'total_logins',
       'std_act_assignments', 'std_act_learning_materials',
       'std_act_module_information_handbook1', 'std_act_reading_list',
       'no_of_times_accessed_assignments',
       'no_of_times_accessed_learning_materials',
       'no_of_times_accessed_module_information_handbook1',
       'no_of_times_accessedreading_list',
       'initial_access_assignments',
       'initial_access_learning_materials',
       'initial_access_information_handbook1', 'initial_access_reading_list',
       'initial_access_week1', 'initial_access_week2', 'unnamed_40',
       'hours_spent','std_act_Week'
      ],
          value_vars=['no_of_times_week1', 'no_of_times_week2'], var_name='no_of_times_week', value_name='no_of_times_accessed')
except Exception as e:
  print("Error in melting the DataFrame:", e)
  raise

In [332]:
#bringing first week from columns into the rows
try:
  df = pd.melt(df, id_vars=['total_marks', 'list_of_countries',
       'what_is_your_year_of_birth_just_the_year_eg_1995_',
       'how_do_you_describe_yourself___selected_choice',
       'what_is_your_first_degree_subject_area', 'student_id',
       'date_range__week_1', 'monday', 'tuesday', 'wednesday', 'thursday',
       'friday', 'saturday', 'sunday', 'student_time_in_course',
       'avg_time_per_user', 'total_items', 'total_logins',
       'std_act_assignments', 'std_act_learning_materials',
       'std_act_module_information_handbook1', 'std_act_reading_list',
       'no_of_times_accessed_assignments',
       'no_of_times_accessed_learning_materials',
       'no_of_times_accessed_module_information_handbook1',
       'no_of_times_accessedreading_list',
       'initial_access_assignments',
       'initial_access_learning_materials',
       'initial_access_information_handbook1', 'initial_access_reading_list', 'unnamed_40',
       'hours_spent','std_act_Week', 'no_of_times_accessed', 'no_of_times_week'
      ],
          value_vars=['initial_access_week2', 'initial_access_week1'], var_name='initial_access_week', value_name='initial_access_date')
except Exception as e:
  print("Error in melting the DataFrame:", e)
  raise

In [342]:
# renaming columns with spaces and special characters
week2_democo2 = pd.read_excel(xls,'Week 2',skiprows=1)
week2_democo2.columns=week2_democo2.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
week2_democo2 =week2_democo2.iloc[:, 4:]
for i in enumerate(week2_democo2):
    print(i)

(0, 'unnamed_4')
(1, 'list_of_countries')
(2, 'what_is_your_year_of_birth_just_the_year_eg_1995_')
(3, 'how_do_you_describe_yourself___selected_choice')
(4, 'what_is_your_first_degree_subject_area')
(5, 'student_id')
(6, 'date_range__week_2')
(7, 'monday')
(8, 'tuesday')
(9, 'wednesday')
(10, 'thursday')
(11, 'friday')
(12, 'saturday')
(13, 'sunday')
(14, 'student_time_in_course')
(15, 'avg_time_per_user')
(16, 'total_items')
(17, 'total_logins')
(18, 'assignments')
(19, 'learning_materials')
(20, 'module_information_handbook')
(21, 'reading_list')
(22, 'week_1')
(23, 'week_2')
(24, 'week_3_')
(25, 'assignments1')
(26, 'learning_materials1')
(27, 'module_information_handbook')
(28, 'reading_list1')
(29, 'week_11')
(30, 'week_2_')
(31, 'week_3')
(32, 'assignments2')
(33, 'learning_materials2')
(34, 'module_information_handbook1')
(35, 'reading_list2')
(36, 'week_12')
(37, 'week_21')
(38, 'week_3')

In [ ]:
# renaming columns with duplicate names
df.columns.values[0] = 'total_marks'
df.columns.values[18] = 'std_act_assignments'
df.columns.values[19] = 'std_act_learning_materials'
df.columns.values[20] = 'std_act_module_information_handbook1'
df.columns.values[21] = 'std_act_reading_list'
df.columns.values[22] = 'std_act_week1'
df.columns.values[23] = 'std_act_week2'
df.columns.values[24] = 'no_of_times_accessed_assignments'
df.columns.values[25] = 'no_of_times_accessed_learning_materials'
df.columns.values[26] = 'no_of_times_accessed_module_information_handbook1'
df.columns.values[27] = 'no_of_times_accessedreading_list'
df.columns.values[28] = 'no_of_times_week1'
df.columns.values[29] = 'no_of_times_week2'
df.columns.values[30] = 'initial_access_assignments'
df.columns.values[31] = 'initial_access_learning_materials'
df.columns.values[32] = 'initial_access_information_handbook1'
df.columns.values[33] = 'initial_access_reading_list'
df.columns.values[34] = 'initial_access_week1'
df.columns.values[35] = 'initial_access_week2'